// Generated by Trellis. Do not edit.
//! Thin typed client helpers for `demo.service@v1`.
use trellis_rs::generated::TrellisClientError;
/// Typed API wrapper for the `demo.service@v1` contract.
pub struct DemoServiceClient<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> DemoServiceClient<'a> {
    /// Wrap an already connected low-level Trellis client.
    pub fn new(inner: &'a trellis_rs::generated::Caller) -> Self {
        Self { inner }
    }
    /// Access typed RPC calls.
    pub fn rpc(&self) -> Rpc<'a> {
        Rpc { _inner: self.inner }
    }
    /// Access typed events.
    pub fn event(&self) -> Event<'a> {
        Event { _inner: self.inner }
    }
    /// Access typed feeds.
    pub fn feed(&self) -> Feed<'a> {
        Feed { _inner: self.inner }
    }
    /// Access typed operations.
    pub fn operation(&self) -> Operation<'a> {
        Operation { _inner: self.inner }
    }
}
/// Typed RPC surface.
pub struct Rpc<'a> {
    pub(super) _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Rpc<'a> {
    /// Access the `assignments` RPC group.
    pub fn assignments(&self) -> AssignmentsRpc<'a> {
        AssignmentsRpc { inner: self._inner }
    }
    /// Access the `evidence` RPC group.
    pub fn evidence(&self) -> EvidenceRpc<'a> {
        EvidenceRpc { inner: self._inner }
    }
    /// Access the `reports` RPC group.
    pub fn reports(&self) -> ReportsRpc<'a> {
        ReportsRpc { inner: self._inner }
    }
    /// Access the `sites` RPC group.
    pub fn sites(&self) -> SitesRpc<'a> {
        SitesRpc { inner: self._inner }
    }
}
/// Typed RPC methods in the `assignments` group.
pub struct AssignmentsRpc<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> AssignmentsRpc<'a> {
    /// Call `Assignments.List`.
    pub async fn list(
        &self,
        input: &super::types::AssignmentsListRequest,
    ) -> Result<
        super::types::AssignmentsListResponse,
        trellis_rs::generated::CallError<super::rpc::AssignmentsListError>,
    > {
        self.inner
            .call_typed::<super::rpc::AssignmentsListRpc, super::rpc::AssignmentsListError>(input)
            .await
    }
}
/// Typed RPC methods in the `evidence` group.
pub struct EvidenceRpc<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> EvidenceRpc<'a> {
    /// Call `Evidence.Delete`.
    pub async fn delete(
        &self,
        input: &super::types::EvidenceDeleteRequest,
    ) -> Result<
        super::types::EvidenceDeleteResponse,
        trellis_rs::generated::CallError<super::rpc::EvidenceDeleteError>,
    > {
        self.inner
            .call_typed::<super::rpc::EvidenceDeleteRpc, super::rpc::EvidenceDeleteError>(input)
            .await
    }
    /// Call `Evidence.Download`.
    pub async fn download(
        &self,
        input: &super::types::EvidenceDownloadRequest,
    ) -> Result<
        super::types::EvidenceDownloadResponse,
        trellis_rs::generated::CallError<super::rpc::EvidenceDownloadError>,
    > {
        self.inner
            .call_typed::<super::rpc::EvidenceDownloadRpc, super::rpc::EvidenceDownloadError>(input)
            .await
    }
    /// Call `Evidence.List`.
    pub async fn list(
        &self,
        input: &super::types::EvidenceListRequest,
    ) -> Result<
        super::types::EvidenceListResponse,
        trellis_rs::generated::CallError<super::rpc::EvidenceListError>,
    > {
        self.inner
            .call_typed::<super::rpc::EvidenceListRpc, super::rpc::EvidenceListError>(input)
            .await
    }
}
/// Typed RPC methods in the `reports` group.
pub struct ReportsRpc<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> ReportsRpc<'a> {
    /// Call `Reports.List`.
    pub async fn list(
        &self,
        input: &super::types::ReportsListRequest,
    ) -> Result<
        super::types::ReportsListResponse,
        trellis_rs::generated::CallError<super::rpc::ReportsListError>,
    > {
        self.inner
            .call_typed::<super::rpc::ReportsListRpc, super::rpc::ReportsListError>(input)
            .await
    }
}
/// Typed RPC methods in the `sites` group.
pub struct SitesRpc<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> SitesRpc<'a> {
    /// Call `Sites.Get`.
    pub async fn get(
        &self,
        input: &super::types::SitesGetRequest,
    ) -> Result<
        super::types::SitesGetResponse,
        trellis_rs::generated::CallError<super::rpc::SitesGetError>,
    > {
        self.inner
            .call_typed::<super::rpc::SitesGetRpc, super::rpc::SitesGetError>(input)
            .await
    }
    /// Call `Sites.List`.
    pub async fn list(
        &self,
        input: &super::types::SitesListRequest,
    ) -> Result<
        super::types::SitesListResponse,
        trellis_rs::generated::CallError<super::rpc::SitesListError>,
    > {
        self.inner
            .call_typed::<super::rpc::SitesListRpc, super::rpc::SitesListError>(input)
            .await
    }
}
/// Typed event surface.
pub struct Event<'a> {
    pub(super) _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Event<'a> {
    /// Access the `audit` event group.
    pub fn audit(&self) -> AuditEvent<'a> {
        AuditEvent { inner: self._inner }
    }
    /// Access the `evidence` event group.
    pub fn evidence(&self) -> EvidenceEvent<'a> {
        EvidenceEvent { inner: self._inner }
    }
    /// Access the `reports` event group.
    pub fn reports(&self) -> ReportsEvent<'a> {
        ReportsEvent { inner: self._inner }
    }
    /// Access the `sites` event group.
    pub fn sites(&self) -> SitesEvent<'a> {
        SitesEvent { inner: self._inner }
    }
}
/// Typed events in the `audit` group.
pub struct AuditEvent<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> AuditEvent<'a> {
    /// Access `Audit.Recorded`.
    pub fn recorded(&self) -> AuditRecordedEvent<'a> {
        AuditRecordedEvent { inner: self.inner }
    }
}
/// Typed `Audit.Recorded` event operations.
pub struct AuditRecordedEvent<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> AuditRecordedEvent<'a> {
    /// Publish `Audit.Recorded`.
    pub async fn publish(
        &self,
        event: &super::types::AuditRecordedEvent,
    ) -> Result<(), TrellisClientError> {
        self.inner
            .publish::<super::events::AuditRecordedEventDescriptor>(event)
            .await
    }
    /// Listen for live `Audit.Recorded` events.
    pub async fn listen<F, Fut>(&self, handler: F) -> Result<(), TrellisClientError>
    where
        F: Fn(super::types::AuditRecordedEvent) -> Fut,
        Fut: std::future::Future<Output = Result<(), TrellisClientError>>,
    {
        let mut stream = self
            .inner
            .subscribe::<super::events::AuditRecordedEventDescriptor>()
            .await?;
        while let Some(event) = futures_util::StreamExt::next(&mut stream).await {
            handler(event?).await?;
        }
        Ok(())
    }
}
/// Typed events in the `evidence` group.
pub struct EvidenceEvent<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> EvidenceEvent<'a> {
    /// Access `Evidence.Uploaded`.
    pub fn uploaded(&self) -> EvidenceUploadedEvent<'a> {
        EvidenceUploadedEvent { inner: self.inner }
    }
}
/// Typed `Evidence.Uploaded` event operations.
pub struct EvidenceUploadedEvent<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> EvidenceUploadedEvent<'a> {
    /// Publish `Evidence.Uploaded`.
    pub async fn publish(
        &self,
        event: &super::types::EvidenceUploadedEvent,
    ) -> Result<(), TrellisClientError> {
        self.inner
            .publish::<super::events::EvidenceUploadedEventDescriptor>(event)
            .await
    }
    /// Listen for live `Evidence.Uploaded` events.
    pub async fn listen<F, Fut>(&self, handler: F) -> Result<(), TrellisClientError>
    where
        F: Fn(super::types::EvidenceUploadedEvent) -> Fut,
        Fut: std::future::Future<Output = Result<(), TrellisClientError>>,
    {
        let mut stream = self
            .inner
            .subscribe::<super::events::EvidenceUploadedEventDescriptor>()
            .await?;
        while let Some(event) = futures_util::StreamExt::next(&mut stream).await {
            handler(event?).await?;
        }
        Ok(())
    }
}
/// Typed events in the `reports` group.
pub struct ReportsEvent<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> ReportsEvent<'a> {
    /// Access `Reports.Published`.
    pub fn published(&self) -> ReportsPublishedEvent<'a> {
        ReportsPublishedEvent { inner: self.inner }
    }
}
/// Typed `Reports.Published` event operations.
pub struct ReportsPublishedEvent<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> ReportsPublishedEvent<'a> {
    /// Publish `Reports.Published`.
    pub async fn publish(
        &self,
        event: &super::types::ReportsPublishedEvent,
    ) -> Result<(), TrellisClientError> {
        self.inner
            .publish::<super::events::ReportsPublishedEventDescriptor>(event)
            .await
    }
    /// Listen for live `Reports.Published` events.
    pub async fn listen<F, Fut>(&self, handler: F) -> Result<(), TrellisClientError>
    where
        F: Fn(super::types::ReportsPublishedEvent) -> Fut,
        Fut: std::future::Future<Output = Result<(), TrellisClientError>>,
    {
        let mut stream = self
            .inner
            .subscribe::<super::events::ReportsPublishedEventDescriptor>()
            .await?;
        while let Some(event) = futures_util::StreamExt::next(&mut stream).await {
            handler(event?).await?;
        }
        Ok(())
    }
}
/// Typed events in the `sites` group.
pub struct SitesEvent<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> SitesEvent<'a> {
    /// Access `Sites.Refreshed`.
    pub fn refreshed(&self) -> SitesRefreshedEvent<'a> {
        SitesRefreshedEvent { inner: self.inner }
    }
}
/// Typed `Sites.Refreshed` event operations.
pub struct SitesRefreshedEvent<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> SitesRefreshedEvent<'a> {
    /// Publish `Sites.Refreshed`.
    pub async fn publish(
        &self,
        event: &super::types::SitesRefreshedEvent,
    ) -> Result<(), TrellisClientError> {
        self.inner
            .publish::<super::events::SitesRefreshedEventDescriptor>(event)
            .await
    }
    /// Listen for live `Sites.Refreshed` events.
    pub async fn listen<F, Fut>(&self, handler: F) -> Result<(), TrellisClientError>
    where
        F: Fn(super::types::SitesRefreshedEvent) -> Fut,
        Fut: std::future::Future<Output = Result<(), TrellisClientError>>,
    {
        let mut stream = self
            .inner
            .subscribe::<super::events::SitesRefreshedEventDescriptor>()
            .await?;
        while let Some(event) = futures_util::StreamExt::next(&mut stream).await {
            handler(event?).await?;
        }
        Ok(())
    }
}
/// Typed feed surface.
pub struct Feed<'a> {
    pub(super) _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Feed<'a> {
    /// Access the `audit` feed group.
    pub fn audit(&self) -> AuditFeed<'a> {
        AuditFeed { inner: self._inner }
    }
}
/// Typed feeds in the `audit` group.
pub struct AuditFeed<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> AuditFeed<'a> {
    /// Subscribe to `Audit.Feed`.
    pub async fn feed(
        &self,
    ) -> Result<
        futures_util::stream::BoxStream<
            'static,
            Result<super::types::AuditFeedEvent, TrellisClientError>,
        >,
        TrellisClientError,
    > {
        self.inner
            .feed::<super::feeds::AuditFeedFeedDescriptor>(&super::rpc::Empty {})
            .await
    }
}
/// Typed operation surface.
pub struct Operation<'a> {
    pub(super) _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Operation<'a> {
    /// Access the `evidence` operation group.
    pub fn evidence(&self) -> EvidenceOperation<'a> {
        EvidenceOperation { inner: self._inner }
    }
    /// Access the `reports` operation group.
    pub fn reports(&self) -> ReportsOperation<'a> {
        ReportsOperation { inner: self._inner }
    }
    /// Access the `sites` operation group.
    pub fn sites(&self) -> SitesOperation<'a> {
        SitesOperation { inner: self._inner }
    }
}
/// Typed operations in the `evidence` group.
pub struct EvidenceOperation<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> EvidenceOperation<'a> {
    /// Access `Evidence.Upload`.
    pub fn upload(&self) -> EvidenceUploadOperation<'a> {
        EvidenceUploadOperation { inner: self.inner }
    }
}
/// Typed `Evidence.Upload` operation controls.
pub struct EvidenceUploadOperation<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> EvidenceUploadOperation<'a> {
    /// Start `Evidence.Upload`.
    pub async fn start(
        &self,
        input: &super::types::EvidenceUploadInput,
    ) -> Result<
        trellis_rs::generated::OperationRef<
            'a,
            trellis_rs::generated::Caller,
            super::operations::EvidenceUploadOperation,
        >,
        TrellisClientError,
    > {
        self.inner
            .operation::<super::operations::EvidenceUploadOperation>()
            .start(input)
            .await
    }
}
/// Typed operations in the `reports` group.
pub struct ReportsOperation<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> ReportsOperation<'a> {
    /// Access `Reports.Generate`.
    pub fn generate(&self) -> ReportsGenerateOperation<'a> {
        ReportsGenerateOperation { inner: self.inner }
    }
}
/// Typed `Reports.Generate` operation controls.
pub struct ReportsGenerateOperation<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> ReportsGenerateOperation<'a> {
    /// Start `Reports.Generate`.
    pub async fn start(
        &self,
        input: &super::types::ReportsGenerateInput,
    ) -> Result<
        trellis_rs::generated::OperationRef<
            'a,
            trellis_rs::generated::Caller,
            super::operations::ReportsGenerateOperation,
        >,
        TrellisClientError,
    > {
        self.inner
            .operation::<super::operations::ReportsGenerateOperation>()
            .start(input)
            .await
    }
}
/// Typed operations in the `sites` group.
pub struct SitesOperation<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> SitesOperation<'a> {
    /// Access `Sites.Refresh`.
    pub fn refresh(&self) -> SitesRefreshOperation<'a> {
        SitesRefreshOperation { inner: self.inner }
    }
}
/// Typed `Sites.Refresh` operation controls.
pub struct SitesRefreshOperation<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> SitesRefreshOperation<'a> {
    /// Start `Sites.Refresh`.
    pub async fn start(
        &self,
        input: &super::types::SitesRefreshInput,
    ) -> Result<
        trellis_rs::generated::OperationRef<
            'a,
            trellis_rs::generated::Caller,
            super::operations::SitesRefreshOperation,
        >,
        TrellisClientError,
    > {
        self.inner
            .operation::<super::operations::SitesRefreshOperation>()
            .start(input)
            .await
    }
}
