// Generated by Trellis. Do not edit.
//! Typed event descriptors for `demo.service@v1`.
use trellis_rs::generated::EventDescriptor;
/// Descriptor for `Audit.Recorded`.
pub struct AuditRecordedEventDescriptor;
impl EventDescriptor for AuditRecordedEventDescriptor {
    type Event = super::types::AuditRecordedEvent;
    const KEY: &'static str = "Audit.Recorded";
    const SUBJECT: &'static str = "events.v1.Audit.Recorded";
    const SUBSCRIBE_SUBJECT: &'static str = "events.v1.Audit.Recorded";
    const EVENT_SCHEMA_JSON: &'static str = super::schemas::AUDIT_RECORDED_EVENT_SCHEMA_JSON;
    const PUBLISH_CAPABILITIES: &'static [&'static str] = &[];
    const DELEGATED_PUBLISH: bool = false;
    const SUBSCRIBE_CAPABILITIES: &'static [&'static str] = &[];
}
/// Descriptor for `Evidence.Uploaded`.
pub struct EvidenceUploadedEventDescriptor;
impl EventDescriptor for EvidenceUploadedEventDescriptor {
    type Event = super::types::EvidenceUploadedEvent;
    const KEY: &'static str = "Evidence.Uploaded";
    const SUBJECT: &'static str = "events.v1.Evidence.Uploaded";
    const SUBSCRIBE_SUBJECT: &'static str = "events.v1.Evidence.Uploaded";
    const EVENT_SCHEMA_JSON: &'static str = super::schemas::EVIDENCE_UPLOADED_EVENT_SCHEMA_JSON;
    const PUBLISH_CAPABILITIES: &'static [&'static str] = &[];
    const DELEGATED_PUBLISH: bool = false;
    const SUBSCRIBE_CAPABILITIES: &'static [&'static str] = &[];
}
/// Descriptor for `Reports.Published`.
pub struct ReportsPublishedEventDescriptor;
impl EventDescriptor for ReportsPublishedEventDescriptor {
    type Event = super::types::ReportsPublishedEvent;
    const KEY: &'static str = "Reports.Published";
    const SUBJECT: &'static str = "events.v1.Reports.Published";
    const SUBSCRIBE_SUBJECT: &'static str = "events.v1.Reports.Published";
    const EVENT_SCHEMA_JSON: &'static str = super::schemas::REPORTS_PUBLISHED_EVENT_SCHEMA_JSON;
    const PUBLISH_CAPABILITIES: &'static [&'static str] = &[];
    const DELEGATED_PUBLISH: bool = false;
    const SUBSCRIBE_CAPABILITIES: &'static [&'static str] = &[];
}
/// Descriptor for `Sites.Refreshed`.
pub struct SitesRefreshedEventDescriptor;
impl EventDescriptor for SitesRefreshedEventDescriptor {
    type Event = super::types::SitesRefreshedEvent;
    const KEY: &'static str = "Sites.Refreshed";
    const SUBJECT: &'static str = "events.v1.Sites.Refreshed";
    const SUBSCRIBE_SUBJECT: &'static str = "events.v1.Sites.Refreshed";
    const EVENT_SCHEMA_JSON: &'static str = super::schemas::SITES_REFRESHED_EVENT_SCHEMA_JSON;
    const PUBLISH_CAPABILITIES: &'static [&'static str] = &[];
    const DELEGATED_PUBLISH: bool = false;
    const SUBSCRIBE_CAPABILITIES: &'static [&'static str] = &[];
}
