// Generated by Trellis. Do not edit.
//! Typed feed descriptors for `demo.service@v1`.
use trellis_rs::generated::FeedDescriptor;
/// Descriptor for `Audit.Feed`.
pub struct AuditFeedFeedDescriptor;
impl FeedDescriptor for AuditFeedFeedDescriptor {
    type Input = super::rpc::Empty;
    type Event = super::types::AuditFeedEvent;
    const INPUT_SCHEMA_JSON: &'static str = super::schemas::AUDIT_FEED_INPUT_SCHEMA_JSON;
    const EVENT_SCHEMA_JSON: &'static str = super::schemas::AUDIT_FEED_EVENT_SCHEMA_JSON;
    const KEY: &'static str = "Audit.Feed";
    const SUBJECT: &'static str = "feed.v1.Audit.Feed";
    const SUBSCRIBE_CAPABILITIES: &'static [&'static str] = &[];
}
