// Generated by Trellis. Do not edit.
//! User-authenticated connection entry point for this participant.
use super::participant::{PARTICIPANT_DIGEST, PARTICIPANT_ID};
use super::Client;
use std::sync::Arc;
use trellis_rs::generated::{
    AuthorizationContextStore, AuthorizationInstallation, Caller, TrellisClientError,
    UserAuthorizationContext, UserConnectOptions, UserSessionCredentials,
};
/// User-authenticated participant connection options.
pub struct ConnectOptions<'a> {
    trellis_url: &'a str,
    session_key_seed_base64url: &'a str,
    initial: AuthorizationInstallation,
    timeout_ms: u64,
    authorization_context_store: Arc<dyn AuthorizationContextStore>,
}
impl<'a> ConnectOptions<'a> {
    /// Create user-authenticated connection options.
    pub fn new(
        trellis_url: &'a str,
        session_key_seed_base64url: &'a str,
        initial: AuthorizationInstallation,
        timeout_ms: u64,
        authorization_context_store: Arc<dyn AuthorizationContextStore>,
    ) -> Self {
        Self {
            trellis_url,
            session_key_seed_base64url,
            initial,
            timeout_ms,
            authorization_context_store,
        }
    }
}
/// Connected caller facade for this participant contract.
pub struct ConnectedClient {
    inner: Caller,
}
impl ConnectedClient {
    /// Access only the contract surfaces declared by this participant.
    pub fn client(&self) -> Client<'_> {
        Client::new(&self.inner)
    }
}
/// Connect this participant with a user-authenticated session.
pub async fn connect(opts: ConnectOptions<'_>) -> Result<ConnectedClient, TrellisClientError> {
    let origin = trellis_rs::client::canonical_trellis_origin(opts.trellis_url)?;
    Ok(ConnectedClient {
        inner: Caller::connect_user(UserConnectOptions::new(
            opts.trellis_url,
            opts.timeout_ms,
            UserSessionCredentials {
                session_key_seed_base64url: opts.session_key_seed_base64url,
            },
            UserAuthorizationContext {
                initial: Some(opts.initial),
                binding: format!(
                    "installation:{}:{}:{}",
                    origin, PARTICIPANT_ID, PARTICIPANT_DIGEST,
                ),
                store: opts.authorization_context_store,
            },
        ))
        .await?,
    })
}
impl ConnectedClient {
    /// Access the `events` dependency surface.
    pub fn events(&self) -> super::uses::events::Client<'_> {
        super::Client::new(&self.inner).events()
    }
}
