// Generated by Trellis. Do not edit.
//! Typed event descriptors for `test.runtime@v1`.
use trellis_rs::generated::EventDescriptor;
/// Descriptor for `Changed`.
pub struct ChangedEventDescriptor;
impl EventDescriptor for ChangedEventDescriptor {
    type Event = super::types::ChangedEvent;
    const KEY: &'static str = "Changed";
    const SUBJECT: &'static str = "events.v1.Changed";
    const SUBSCRIBE_SUBJECT: &'static str = "events.v1.Changed";
    const EVENT_SCHEMA_JSON: &'static str = super::schemas::CHANGED_EVENT_SCHEMA_JSON;
    const PUBLISH_CAPABILITIES: &'static [&'static str] = &[];
    const DELEGATED_PUBLISH: bool = false;
    const SUBSCRIBE_CAPABILITIES: &'static [&'static str] = &[];
}
