// Generated by Trellis. Do not edit.
//! JSON Schema constants for `test.runtime@v1`.
/// Generated JSON Schema constant `ECHO_INPUT_SCHEMA_JSON`.
pub const ECHO_INPUT_SCHEMA_JSON: &str =
    r#"{"properties":{"value":{"type":"string"}},"required":["value"],"type":"object"}"#;
/// Generated JSON Schema constant `ECHO_OUTPUT_SCHEMA_JSON`.
pub const ECHO_OUTPUT_SCHEMA_JSON: &str =
    r#"{"properties":{"value":{"type":"string"}},"required":["value"],"type":"object"}"#;
/// Generated JSON Schema constant `UPLOAD_INPUT_SCHEMA_JSON`.
pub const UPLOAD_INPUT_SCHEMA_JSON: &str =
    r#"{"properties":{"value":{"type":"string"}},"required":["value"],"type":"object"}"#;
/// Generated JSON Schema constant `UPLOAD_PROGRESS_SCHEMA_JSON`.
pub const UPLOAD_PROGRESS_SCHEMA_JSON: Option<&str> = None;
/// Generated JSON Schema constant `UPLOAD_OUTPUT_SCHEMA_JSON`.
pub const UPLOAD_OUTPUT_SCHEMA_JSON: &str =
    r#"{"properties":{"value":{"type":"string"}},"required":["value"],"type":"object"}"#;
/// Generated JSON Schema constant `UPLOAD_SIGNAL_INPUT_SCHEMAS_JSON`.
pub const UPLOAD_SIGNAL_INPUT_SCHEMAS_JSON: &str = r#"{}"#;
/// Generated JSON Schema constant `WORK_INPUT_SCHEMA_JSON`.
pub const WORK_INPUT_SCHEMA_JSON: &str =
    r#"{"properties":{"value":{"type":"string"}},"required":["value"],"type":"object"}"#;
/// Generated JSON Schema constant `WORK_PROGRESS_SCHEMA_JSON`.
pub const WORK_PROGRESS_SCHEMA_JSON: Option<&str> = None;
/// Generated JSON Schema constant `WORK_OUTPUT_SCHEMA_JSON`.
pub const WORK_OUTPUT_SCHEMA_JSON: &str =
    r#"{"properties":{"value":{"type":"string"}},"required":["value"],"type":"object"}"#;
/// Generated JSON Schema constant `WORK_SIGNAL_INPUT_SCHEMAS_JSON`.
pub const WORK_SIGNAL_INPUT_SCHEMAS_JSON: &str = r#"{}"#;
/// Generated JSON Schema constant `CHANGED_EVENT_SCHEMA_JSON`.
pub const CHANGED_EVENT_SCHEMA_JSON: &str =
    r#"{"properties":{"value":{"type":"string"}},"required":["value"],"type":"object"}"#;
/// Generated JSON Schema constant `WATCH_INPUT_SCHEMA_JSON`.
pub const WATCH_INPUT_SCHEMA_JSON: &str = r#"{"properties":{},"type":"object"}"#;
/// Generated JSON Schema constant `WATCH_EVENT_SCHEMA_JSON`.
pub const WATCH_EVENT_SCHEMA_JSON: &str =
    r#"{"properties":{"value":{"type":"string"}},"required":["value"],"type":"object"}"#;
