// Generated by Trellis. Do not edit.
// Generated from trellis.health@v1
import { eventActions, feedAction, rpcAction, schema } from "@qlever-llc/trellis";
import * as Types from "./types.js";
declare const API_ID: "trellis.health@v1";
declare const __HealthInspectDescriptor: {
	readonly subject: "rpc.v1.Health.Inspect";
	readonly permission: {
		readonly apiId: "trellis.health@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Health.Inspect";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.HealthInspectInput>>;
	readonly output: ReturnType<typeof schema<Types.HealthInspectOutput>>;
	readonly callerCapabilities: readonly ["trellis.health::read"];
	readonly errors: readonly ["NotFoundError", "UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["NotFoundError", "UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "NotFoundError";
		readonly schema: ReturnType<typeof schema<Types.NotFoundErrorData>>;
		readonly fromSerializable: typeof Types.NotFoundError.fromSerializable;
	}, {
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const HealthInspect: ReturnType<typeof rpcAction<typeof API_ID, "Health.Inspect", typeof __HealthInspectDescriptor>>;
declare const __HealthMetricsDescriptor: {
	readonly subject: "rpc.v1.Health.Metrics";
	readonly permission: {
		readonly apiId: "trellis.health@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Health.Metrics";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.HealthMetricsInput>>;
	readonly output: ReturnType<typeof schema<Types.HealthMetricsOutput>>;
	readonly callerCapabilities: readonly ["trellis.health::read"];
	readonly errors: readonly ["UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const HealthMetrics: ReturnType<typeof rpcAction<typeof API_ID, "Health.Metrics", typeof __HealthMetricsDescriptor>>;
declare const __HealthQueryDescriptor: {
	readonly subject: "rpc.v1.Health.Query";
	readonly permission: {
		readonly apiId: "trellis.health@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Health.Query";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.HealthQueryInput>>;
	readonly output: ReturnType<typeof schema<Types.HealthQueryOutput>>;
	readonly callerCapabilities: readonly ["trellis.health::read"];
	readonly errors: readonly ["UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const HealthQuery: ReturnType<typeof rpcAction<typeof API_ID, "Health.Query", typeof __HealthQueryDescriptor>>;
declare const __HealthStatusChangedDescriptor: {
	readonly subject: "events.v1.Health.StatusChanged";
	readonly publishPermission: {
		readonly apiId: "trellis.health@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Health.StatusChanged";
		readonly action: "publish";
	};
	readonly subscribePermission: {
		readonly apiId: "trellis.health@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Health.StatusChanged";
		readonly action: "subscribe";
	};
	readonly event: ReturnType<typeof schema<Types.HealthStatusChangedEvent>>;
	readonly publishCapabilities: readonly [];
	readonly subscribeCapabilities: readonly ["trellis.health::read"];
};
export declare const HealthStatusChanged: ReturnType<typeof eventActions<typeof API_ID, "Health.StatusChanged", typeof __HealthStatusChangedDescriptor, true>>;
declare const __HealthWatchDescriptor: {
	readonly subject: "feed.v1.Health.Watch";
	readonly permission: {
		readonly apiId: "trellis.health@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "feed";
		readonly surfaceName: "Health.Watch";
		readonly action: "subscribe";
	};
	readonly input: ReturnType<typeof schema<Types.HealthWatchInput>>;
	readonly event: ReturnType<typeof schema<Types.HealthWatchEvent>>;
	readonly subscribeCapabilities: readonly ["trellis.health::read"];
};
export declare const HealthWatch: ReturnType<typeof feedAction<typeof API_ID, "Health.Watch", typeof __HealthWatchDescriptor>>;
export declare const ACTIONS: {
	readonly "Health.Inspect": typeof HealthInspect;
	readonly "Health.Metrics": typeof HealthMetrics;
	readonly "Health.Query": typeof HealthQuery;
	readonly "Health.StatusChanged": typeof HealthStatusChanged;
	readonly "Health.Watch": typeof HealthWatch;
};
export {};
