// Generated by Trellis. Do not edit.
// Generated from demo.service@v1
export declare const API_ID: "demo.service@v1";
export declare const API_DIGEST: "qu_P04zYsryJycTKpriGBJIOAZ9N0xDwYZj8p9BR8eg";
export declare const API: {
	readonly description: "Consolidated Field Ops demo service for Trellis concepts.";
	readonly displayName: "Field Ops Demo Service";
	readonly docs: {
		readonly markdown: "Provides assignments, site summaries, evidence transfer, report generation, and audit activity for the Field Ops demo.";
		readonly summary: "Field operations demo APIs.";
	};
	readonly errors: {
		readonly TransferError: {};
		readonly UnexpectedError: {};
	};
	readonly events: {
		readonly "Audit.Recorded": {
			readonly event: {
				readonly schema: "AuditRecordedEvent";
			};
			readonly version: "v1";
		};
		readonly "Evidence.Uploaded": {
			readonly event: {
				readonly schema: "EvidenceUploadedEvent";
			};
			readonly version: "v1";
		};
		readonly "Reports.Published": {
			readonly event: {
				readonly schema: "ReportsPublishedEvent";
			};
			readonly version: "v1";
		};
		readonly "Sites.Refreshed": {
			readonly event: {
				readonly schema: "SitesRefreshedEvent";
			};
			readonly version: "v1";
		};
	};
	readonly exports: {
		readonly schemas: readonly ["EvidenceRecord", "InspectionAssignment", "ReportRecord", "SiteRefreshJobPayload", "SiteSummary"];
	};
	readonly feeds: {
		readonly "Audit.Feed": {
			readonly docs: {
				readonly markdown: "Subscribes to live activity records from audit, evidence, report, and site refresh events.";
				readonly summary: "Stream audit activity.";
			};
			readonly event: {
				readonly schema: "ActivityLiveFeedEvent";
			};
			readonly input: {
				readonly schema: "ActivityLiveFeedRequest";
			};
			readonly version: "v1";
		};
	};
	readonly format: "trellis.api.v1";
	readonly id: "demo.service@v1";
	readonly operations: {
		readonly "Evidence.Upload": {
			readonly input: {
				readonly schema: "EvidenceUploadRequest";
			};
			readonly output: {
				readonly schema: "EvidenceUploadResponse";
			};
			readonly progress: {
				readonly schema: "EvidenceUploadProgress";
			};
			readonly transfer: {
				readonly direction: "send";
			};
			readonly version: "v1";
		};
		readonly "Reports.Generate": {
			readonly cancel: true;
			readonly input: {
				readonly schema: "ReportsGenerateRequest";
			};
			readonly output: {
				readonly schema: "ReportsGenerateResponse";
			};
			readonly progress: {
				readonly schema: "ReportsGenerateProgress";
			};
			readonly version: "v1";
		};
		readonly "Sites.Refresh": {
			readonly docs: {
				readonly markdown: "Runs a caller-visible workflow that updates the site summary cache.";
				readonly summary: "Refresh site data.";
			};
			readonly input: {
				readonly schema: "SitesRefreshRequest";
			};
			readonly output: {
				readonly schema: "SitesRefreshResponse";
			};
			readonly progress: {
				readonly schema: "SitesRefreshProgress";
			};
			readonly version: "v1";
		};
	};
	readonly rpc: {
		readonly "Assignments.List": {
			readonly docs: {
				readonly markdown: "Returns inspection assignments available to the caller.";
				readonly summary: "List assignments.";
			};
			readonly errors: readonly ["UnexpectedError"];
			readonly input: {
				readonly schema: "AssignmentsListRequest";
			};
			readonly output: {
				readonly schema: "AssignmentsListResponse";
			};
			readonly version: "v1";
		};
		readonly "Evidence.Delete": {
			readonly errors: readonly ["UnexpectedError"];
			readonly input: {
				readonly schema: "EvidenceDeleteRequest";
			};
			readonly output: {
				readonly schema: "EvidenceDeleteResponse";
			};
			readonly version: "v1";
		};
		readonly "Evidence.Download": {
			readonly errors: readonly ["TransferError", "UnexpectedError"];
			readonly input: {
				readonly schema: "EvidenceDownloadRequest";
			};
			readonly output: {
				readonly schema: "EvidenceDownloadResponse";
			};
			readonly transfer: {
				readonly direction: "receive";
			};
			readonly version: "v1";
		};
		readonly "Evidence.List": {
			readonly errors: readonly ["UnexpectedError"];
			readonly input: {
				readonly schema: "EvidenceListRequest";
			};
			readonly output: {
				readonly schema: "EvidenceListResponse";
			};
			readonly version: "v1";
		};
		readonly "Reports.List": {
			readonly errors: readonly ["UnexpectedError"];
			readonly input: {
				readonly schema: "ReportsListRequest";
			};
			readonly output: {
				readonly schema: "ReportsListResponse";
			};
			readonly version: "v1";
		};
		readonly "Sites.Get": {
			readonly errors: readonly ["UnexpectedError"];
			readonly input: {
				readonly schema: "SitesGetRequest";
			};
			readonly output: {
				readonly schema: "SitesGetResponse";
			};
			readonly version: "v1";
		};
		readonly "Sites.List": {
			readonly errors: readonly ["UnexpectedError"];
			readonly input: {
				readonly schema: "SitesListRequest";
			};
			readonly output: {
				readonly schema: "SitesListResponse";
			};
			readonly version: "v1";
		};
	};
	readonly schemas: {
		readonly ActivityLiveFeedEvent: {
			readonly anyOf: readonly [{
				readonly properties: {
					readonly event: {
						readonly properties: {
							readonly activityId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly kind: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly message: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly occurredAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly relatedInspectionId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly relatedSiteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["activityId", "kind", "message", "occurredAt"];
						readonly type: "object";
					};
					readonly name: {
						readonly const: "Audit.Recorded";
						readonly type: "string";
					};
				};
				readonly required: readonly ["name", "event"];
				readonly type: "object";
			}, {
				readonly properties: {
					readonly event: {
						readonly properties: {
							readonly inspectionId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly publishedAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly reportId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["reportId", "inspectionId", "publishedAt"];
						readonly type: "object";
					};
					readonly name: {
						readonly const: "Reports.Published";
						readonly type: "string";
					};
				};
				readonly required: readonly ["name", "event"];
				readonly type: "object";
			}, {
				readonly properties: {
					readonly event: {
						readonly properties: {
							readonly contentType: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly evidenceId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly evidenceType: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly fileName: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly key: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly size: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly uploadedAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
						readonly type: "object";
					};
					readonly name: {
						readonly const: "Evidence.Uploaded";
						readonly type: "string";
					};
				};
				readonly required: readonly ["name", "event"];
				readonly type: "object";
			}, {
				readonly properties: {
					readonly event: {
						readonly properties: {
							readonly refreshId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly refreshedAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly site: {
								readonly properties: {
									readonly lastReportAt: {
										readonly minLength: 1;
										readonly type: "string";
									};
									readonly latestStatus: {
										readonly minLength: 1;
										readonly type: "string";
									};
									readonly openInspections: {
										readonly minimum: 0;
										readonly type: "integer";
									};
									readonly overdueInspections: {
										readonly minimum: 0;
										readonly type: "integer";
									};
									readonly siteId: {
										readonly minLength: 1;
										readonly type: "string";
									};
									readonly siteName: {
										readonly minLength: 1;
										readonly type: "string";
									};
								};
								readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
								readonly type: "object";
							};
						};
						readonly required: readonly ["refreshId", "site", "refreshedAt"];
						readonly type: "object";
					};
					readonly name: {
						readonly const: "Sites.Refreshed";
						readonly type: "string";
					};
				};
				readonly required: readonly ["name", "event"];
				readonly type: "object";
			}];
		};
		readonly ActivityLiveFeedRequest: {
			readonly properties: {};
			readonly type: "object";
		};
		readonly AssignmentsListRequest: {
			readonly properties: {
				readonly limit: {
					readonly maximum: 500;
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly offset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
			};
			readonly required: readonly ["limit"];
			readonly type: "object";
		};
		readonly AssignmentsListResponse: {
			readonly properties: {
				readonly count: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly entries: {
					readonly items: {
						readonly properties: {
							readonly assetName: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly checklistName: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly inspectionId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly priority: {
								readonly anyOf: readonly [{
									readonly const: "high";
									readonly type: "string";
								}, {
									readonly const: "medium";
									readonly type: "string";
								}, {
									readonly const: "low";
									readonly type: "string";
								}];
							};
							readonly scheduledFor: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteName: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["inspectionId", "siteId", "siteName", "assetName", "checklistName", "priority", "scheduledFor"];
						readonly type: "object";
					};
					readonly type: "array";
				};
				readonly limit: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly nextOffset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly offset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
			};
			readonly required: readonly ["entries", "count", "offset", "limit"];
			readonly type: "object";
		};
		readonly AuditFeedItem: {
			readonly properties: {
				readonly event: {
					readonly properties: {
						readonly activityId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly kind: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly message: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly occurredAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly relatedInspectionId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly relatedSiteId: {
							readonly minLength: 1;
							readonly type: "string";
						};
					};
					readonly required: readonly ["activityId", "kind", "message", "occurredAt"];
					readonly type: "object";
				};
				readonly name: {
					readonly const: "Audit.Recorded";
					readonly type: "string";
				};
			};
			readonly required: readonly ["name", "event"];
			readonly type: "object";
		};
		readonly AuditRecordedEvent: {
			readonly properties: {
				readonly activityId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly kind: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly message: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly occurredAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly relatedInspectionId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly relatedSiteId: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["activityId", "kind", "message", "occurredAt"];
			readonly type: "object";
		};
		readonly EvidenceDeleteRequest: {
			readonly properties: {
				readonly key: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["key"];
			readonly type: "object";
		};
		readonly EvidenceDeleteResponse: {
			readonly properties: {
				readonly deleted: {
					readonly type: "boolean";
				};
				readonly key: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["key", "deleted"];
			readonly type: "object";
		};
		readonly EvidenceDownloadGrant: {
			readonly properties: {
				readonly chunkBytes: {
					readonly minimum: 1;
					readonly type: "integer";
				};
				readonly direction: {
					readonly const: "receive";
					readonly type: "string";
				};
				readonly expiresAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly info: {
					readonly properties: {
						readonly contentType: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly digest: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly key: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly metadata: {
							readonly additionalProperties: {
								readonly type: "string";
							};
							readonly type: "object";
						};
						readonly size: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly updatedAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
					};
					readonly required: readonly ["key", "size", "updatedAt", "digest", "metadata"];
					readonly type: "object";
				};
				readonly service: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly sessionKey: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly subject: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly transferId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly type: {
					readonly const: "TransferGrant";
					readonly type: "string";
				};
			};
			readonly required: readonly ["type", "direction", "service", "sessionKey", "transferId", "subject", "expiresAt", "chunkBytes", "info"];
			readonly type: "object";
		};
		readonly EvidenceDownloadInfo: {
			readonly properties: {
				readonly contentType: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly digest: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly key: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly metadata: {
					readonly additionalProperties: {
						readonly type: "string";
					};
					readonly type: "object";
				};
				readonly size: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly updatedAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["key", "size", "updatedAt", "digest", "metadata"];
			readonly type: "object";
		};
		readonly EvidenceDownloadRequest: {
			readonly properties: {
				readonly key: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["key"];
			readonly type: "object";
		};
		readonly EvidenceDownloadResponse: {
			readonly properties: {
				readonly transfer: {
					readonly properties: {
						readonly chunkBytes: {
							readonly minimum: 1;
							readonly type: "integer";
						};
						readonly direction: {
							readonly const: "receive";
							readonly type: "string";
						};
						readonly expiresAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly info: {
							readonly properties: {
								readonly contentType: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly digest: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly key: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly metadata: {
									readonly additionalProperties: {
										readonly type: "string";
									};
									readonly type: "object";
								};
								readonly size: {
									readonly minimum: 0;
									readonly type: "integer";
								};
								readonly updatedAt: {
									readonly minLength: 1;
									readonly type: "string";
								};
							};
							readonly required: readonly ["key", "size", "updatedAt", "digest", "metadata"];
							readonly type: "object";
						};
						readonly service: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly sessionKey: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly subject: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly transferId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly type: {
							readonly const: "TransferGrant";
							readonly type: "string";
						};
					};
					readonly required: readonly ["type", "direction", "service", "sessionKey", "transferId", "subject", "expiresAt", "chunkBytes", "info"];
					readonly type: "object";
				};
			};
			readonly required: readonly ["transfer"];
			readonly type: "object";
		};
		readonly EvidenceFeedItem: {
			readonly properties: {
				readonly event: {
					readonly properties: {
						readonly contentType: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly evidenceId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly evidenceType: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly fileName: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly key: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly size: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly uploadedAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
					};
					readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
					readonly type: "object";
				};
				readonly name: {
					readonly const: "Evidence.Uploaded";
					readonly type: "string";
				};
			};
			readonly required: readonly ["name", "event"];
			readonly type: "object";
		};
		readonly EvidenceFileInfo: {
			readonly properties: {
				readonly contentType: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly digest: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly key: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly metadata: {
					readonly additionalProperties: {
						readonly type: "string";
					};
					readonly type: "object";
				};
				readonly size: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly updatedAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["key", "size", "updatedAt", "metadata"];
			readonly type: "object";
		};
		readonly EvidenceListRequest: {
			readonly properties: {
				readonly limit: {
					readonly maximum: 500;
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly offset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly prefix: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["limit"];
			readonly type: "object";
		};
		readonly EvidenceListResponse: {
			readonly properties: {
				readonly count: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly entries: {
					readonly items: {
						readonly properties: {
							readonly contentType: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly evidenceId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly evidenceType: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly fileName: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly key: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly size: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly uploadedAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
						readonly type: "object";
					};
					readonly type: "array";
				};
				readonly limit: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly nextOffset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly offset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
			};
			readonly required: readonly ["entries", "count", "offset", "limit"];
			readonly type: "object";
		};
		readonly EvidenceRecord: {
			readonly properties: {
				readonly contentType: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly evidenceId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly evidenceType: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly fileName: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly key: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly size: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly uploadedAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
			readonly type: "object";
		};
		readonly EvidenceUploadProgress: {
			readonly properties: {
				readonly message: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly stage: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["stage", "message"];
			readonly type: "object";
		};
		readonly EvidenceUploadRequest: {
			readonly properties: {
				readonly contentType: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly evidenceType: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly key: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly metadata: {
					readonly additionalProperties: {
						readonly type: "string";
					};
					readonly type: "object";
				};
			};
			readonly required: readonly ["key", "evidenceType"];
			readonly type: "object";
		};
		readonly EvidenceUploadResponse: {
			readonly properties: {
				readonly contentType: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly disposition: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly evidenceId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly fileName: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly key: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly size: {
					readonly minimum: 0;
					readonly type: "integer";
				};
			};
			readonly required: readonly ["evidenceId", "key", "size", "disposition"];
			readonly type: "object";
		};
		readonly EvidenceUploadedEvent: {
			readonly properties: {
				readonly contentType: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly evidenceId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly evidenceType: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly fileName: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly key: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly size: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly uploadedAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
			readonly type: "object";
		};
		readonly InspectionAssignment: {
			readonly properties: {
				readonly assetName: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly checklistName: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly inspectionId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly priority: {
					readonly anyOf: readonly [{
						readonly const: "high";
						readonly type: "string";
					}, {
						readonly const: "medium";
						readonly type: "string";
					}, {
						readonly const: "low";
						readonly type: "string";
					}];
				};
				readonly scheduledFor: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly siteId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly siteName: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["inspectionId", "siteId", "siteName", "assetName", "checklistName", "priority", "scheduledFor"];
			readonly type: "object";
		};
		readonly NonEmptyString: {
			readonly minLength: 1;
			readonly type: "string";
		};
		readonly NonWhitespaceString: {
			readonly minLength: 1;
			readonly pattern: "\\S";
			readonly type: "string";
		};
		readonly Priority: {
			readonly anyOf: readonly [{
				readonly const: "high";
				readonly type: "string";
			}, {
				readonly const: "medium";
				readonly type: "string";
			}, {
				readonly const: "low";
				readonly type: "string";
			}];
		};
		readonly ReportRecord: {
			readonly properties: {
				readonly assetName: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly evidenceStatus: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly inspectionId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly publishedAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly readiness: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly reportComment: {
					readonly minLength: 1;
					readonly pattern: "\\S";
					readonly type: "string";
				};
				readonly reportId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly siteId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly siteName: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly status: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly summary: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["reportId", "inspectionId", "siteName", "assetName", "status", "publishedAt", "reportComment", "summary", "readiness", "evidenceStatus"];
			readonly type: "object";
		};
		readonly ReportsFeedItem: {
			readonly properties: {
				readonly event: {
					readonly properties: {
						readonly inspectionId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly publishedAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly reportId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly siteId: {
							readonly minLength: 1;
							readonly type: "string";
						};
					};
					readonly required: readonly ["reportId", "inspectionId", "publishedAt"];
					readonly type: "object";
				};
				readonly name: {
					readonly const: "Reports.Published";
					readonly type: "string";
				};
			};
			readonly required: readonly ["name", "event"];
			readonly type: "object";
		};
		readonly ReportsGenerateProgress: {
			readonly properties: {
				readonly message: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly stage: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["stage", "message"];
			readonly type: "object";
		};
		readonly ReportsGenerateRequest: {
			readonly properties: {
				readonly inspectionId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly reportComment: {
					readonly minLength: 1;
					readonly pattern: "\\S";
					readonly type: "string";
				};
			};
			readonly required: readonly ["inspectionId", "reportComment"];
			readonly type: "object";
		};
		readonly ReportsGenerateResponse: {
			readonly properties: {
				readonly inspectionId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly reportId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly status: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["reportId", "inspectionId", "status"];
			readonly type: "object";
		};
		readonly ReportsListRequest: {
			readonly properties: {
				readonly limit: {
					readonly maximum: 500;
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly offset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
			};
			readonly required: readonly ["limit"];
			readonly type: "object";
		};
		readonly ReportsListResponse: {
			readonly properties: {
				readonly count: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly entries: {
					readonly items: {
						readonly properties: {
							readonly assetName: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly evidenceStatus: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly inspectionId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly publishedAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly readiness: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly reportComment: {
								readonly minLength: 1;
								readonly pattern: "\\S";
								readonly type: "string";
							};
							readonly reportId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteName: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly status: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly summary: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["reportId", "inspectionId", "siteName", "assetName", "status", "publishedAt", "reportComment", "summary", "readiness", "evidenceStatus"];
						readonly type: "object";
					};
					readonly type: "array";
				};
				readonly limit: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly nextOffset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly offset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
			};
			readonly required: readonly ["entries", "count", "offset", "limit"];
			readonly type: "object";
		};
		readonly ReportsPublishedEvent: {
			readonly properties: {
				readonly inspectionId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly publishedAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly reportId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly siteId: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["reportId", "inspectionId", "publishedAt"];
			readonly type: "object";
		};
		readonly SiteRefreshJobPayload: {
			readonly properties: {
				readonly siteId: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["siteId"];
			readonly type: "object";
		};
		readonly SiteRefreshJobResult: {
			readonly properties: {
				readonly refreshId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly site: {
					readonly properties: {
						readonly lastReportAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly latestStatus: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly openInspections: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly overdueInspections: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly siteId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly siteName: {
							readonly minLength: 1;
							readonly type: "string";
						};
					};
					readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
					readonly type: "object";
				};
				readonly status: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["refreshId", "site", "status"];
			readonly type: "object";
		};
		readonly SiteSummary: {
			readonly properties: {
				readonly lastReportAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly latestStatus: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly openInspections: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly overdueInspections: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly siteId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly siteName: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
			readonly type: "object";
		};
		readonly SitesFeedItem: {
			readonly properties: {
				readonly event: {
					readonly properties: {
						readonly refreshId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly refreshedAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly site: {
							readonly properties: {
								readonly lastReportAt: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly latestStatus: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly openInspections: {
									readonly minimum: 0;
									readonly type: "integer";
								};
								readonly overdueInspections: {
									readonly minimum: 0;
									readonly type: "integer";
								};
								readonly siteId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly siteName: {
									readonly minLength: 1;
									readonly type: "string";
								};
							};
							readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
							readonly type: "object";
						};
					};
					readonly required: readonly ["refreshId", "site", "refreshedAt"];
					readonly type: "object";
				};
				readonly name: {
					readonly const: "Sites.Refreshed";
					readonly type: "string";
				};
			};
			readonly required: readonly ["name", "event"];
			readonly type: "object";
		};
		readonly SitesGetRequest: {
			readonly properties: {
				readonly siteId: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["siteId"];
			readonly type: "object";
		};
		readonly SitesGetResponse: {
			readonly properties: {
				readonly site: {
					readonly properties: {
						readonly lastReportAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly latestStatus: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly openInspections: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly overdueInspections: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly siteId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly siteName: {
							readonly minLength: 1;
							readonly type: "string";
						};
					};
					readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
					readonly type: "object";
				};
			};
			readonly type: "object";
		};
		readonly SitesListRequest: {
			readonly properties: {
				readonly limit: {
					readonly maximum: 500;
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly offset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
			};
			readonly required: readonly ["limit"];
			readonly type: "object";
		};
		readonly SitesListResponse: {
			readonly properties: {
				readonly count: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly entries: {
					readonly items: {
						readonly properties: {
							readonly lastReportAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly latestStatus: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly openInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly overdueInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly siteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteName: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
						readonly type: "object";
					};
					readonly type: "array";
				};
				readonly limit: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly nextOffset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
				readonly offset: {
					readonly minimum: 0;
					readonly type: "integer";
				};
			};
			readonly required: readonly ["entries", "count", "offset", "limit"];
			readonly type: "object";
		};
		readonly SitesRefreshProgress: {
			readonly properties: {
				readonly message: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly stage: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["stage", "message"];
			readonly type: "object";
		};
		readonly SitesRefreshRequest: {
			readonly properties: {
				readonly siteId: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["siteId"];
			readonly type: "object";
		};
		readonly SitesRefreshResponse: {
			readonly properties: {
				readonly refreshId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly site: {
					readonly properties: {
						readonly lastReportAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly latestStatus: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly openInspections: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly overdueInspections: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly siteId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly siteName: {
							readonly minLength: 1;
							readonly type: "string";
						};
					};
					readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
					readonly type: "object";
				};
				readonly status: {
					readonly minLength: 1;
					readonly type: "string";
				};
			};
			readonly required: readonly ["refreshId", "site", "status"];
			readonly type: "object";
		};
		readonly SitesRefreshedEvent: {
			readonly properties: {
				readonly refreshId: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly refreshedAt: {
					readonly minLength: 1;
					readonly type: "string";
				};
				readonly site: {
					readonly properties: {
						readonly lastReportAt: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly latestStatus: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly openInspections: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly overdueInspections: {
							readonly minimum: 0;
							readonly type: "integer";
						};
						readonly siteId: {
							readonly minLength: 1;
							readonly type: "string";
						};
						readonly siteName: {
							readonly minLength: 1;
							readonly type: "string";
						};
					};
					readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
					readonly type: "object";
				};
			};
			readonly required: readonly ["refreshId", "site", "refreshedAt"];
			readonly type: "object";
		};
	};
	readonly version: "1.0.0";
};
