// Generated by Trellis. Do not edit.
// @ts-self-types="./schemas.d.ts"
// Generated from demo.service@v1
export const ActivityLiveFeedEventSchema = { "anyOf": [
	{
		"properties": {
			"event": {
				"properties": {
					"activityId": {
						"minLength": 1,
						"type": "string"
					},
					"kind": {
						"minLength": 1,
						"type": "string"
					},
					"message": {
						"minLength": 1,
						"type": "string"
					},
					"occurredAt": {
						"minLength": 1,
						"type": "string"
					},
					"relatedInspectionId": {
						"minLength": 1,
						"type": "string"
					},
					"relatedSiteId": {
						"minLength": 1,
						"type": "string"
					}
				},
				"required": [
					"activityId",
					"kind",
					"message",
					"occurredAt"
				],
				"type": "object"
			},
			"name": {
				"const": "Audit.Recorded",
				"type": "string"
			}
		},
		"required": ["name", "event"],
		"type": "object"
	},
	{
		"properties": {
			"event": {
				"properties": {
					"inspectionId": {
						"minLength": 1,
						"type": "string"
					},
					"publishedAt": {
						"minLength": 1,
						"type": "string"
					},
					"reportId": {
						"minLength": 1,
						"type": "string"
					},
					"siteId": {
						"minLength": 1,
						"type": "string"
					}
				},
				"required": [
					"reportId",
					"inspectionId",
					"publishedAt"
				],
				"type": "object"
			},
			"name": {
				"const": "Reports.Published",
				"type": "string"
			}
		},
		"required": ["name", "event"],
		"type": "object"
	},
	{
		"properties": {
			"event": {
				"properties": {
					"contentType": {
						"minLength": 1,
						"type": "string"
					},
					"evidenceId": {
						"minLength": 1,
						"type": "string"
					},
					"evidenceType": {
						"minLength": 1,
						"type": "string"
					},
					"fileName": {
						"minLength": 1,
						"type": "string"
					},
					"key": {
						"minLength": 1,
						"type": "string"
					},
					"size": {
						"minimum": 0,
						"type": "integer"
					},
					"uploadedAt": {
						"minLength": 1,
						"type": "string"
					}
				},
				"required": [
					"evidenceId",
					"key",
					"size",
					"evidenceType",
					"uploadedAt"
				],
				"type": "object"
			},
			"name": {
				"const": "Evidence.Uploaded",
				"type": "string"
			}
		},
		"required": ["name", "event"],
		"type": "object"
	},
	{
		"properties": {
			"event": {
				"properties": {
					"refreshId": {
						"minLength": 1,
						"type": "string"
					},
					"refreshedAt": {
						"minLength": 1,
						"type": "string"
					},
					"site": {
						"properties": {
							"lastReportAt": {
								"minLength": 1,
								"type": "string"
							},
							"latestStatus": {
								"minLength": 1,
								"type": "string"
							},
							"openInspections": {
								"minimum": 0,
								"type": "integer"
							},
							"overdueInspections": {
								"minimum": 0,
								"type": "integer"
							},
							"siteId": {
								"minLength": 1,
								"type": "string"
							},
							"siteName": {
								"minLength": 1,
								"type": "string"
							}
						},
						"required": [
							"siteId",
							"siteName",
							"openInspections",
							"overdueInspections",
							"latestStatus",
							"lastReportAt"
						],
						"type": "object"
					}
				},
				"required": [
					"refreshId",
					"site",
					"refreshedAt"
				],
				"type": "object"
			},
			"name": {
				"const": "Sites.Refreshed",
				"type": "string"
			}
		},
		"required": ["name", "event"],
		"type": "object"
	}
] };
export const ActivityLiveFeedRequestSchema = {
	"properties": {},
	"type": "object"
};
export const AssignmentsListRequestSchema = {
	"properties": {
		"limit": {
			"maximum": 500,
			"minimum": 0,
			"type": "integer"
		},
		"offset": {
			"minimum": 0,
			"type": "integer"
		}
	},
	"required": ["limit"],
	"type": "object"
};
export const AssignmentsListResponseSchema = {
	"properties": {
		"count": {
			"minimum": 0,
			"type": "integer"
		},
		"entries": {
			"items": {
				"properties": {
					"assetName": {
						"minLength": 1,
						"type": "string"
					},
					"checklistName": {
						"minLength": 1,
						"type": "string"
					},
					"inspectionId": {
						"minLength": 1,
						"type": "string"
					},
					"priority": { "anyOf": [
						{
							"const": "high",
							"type": "string"
						},
						{
							"const": "medium",
							"type": "string"
						},
						{
							"const": "low",
							"type": "string"
						}
					] },
					"scheduledFor": {
						"minLength": 1,
						"type": "string"
					},
					"siteId": {
						"minLength": 1,
						"type": "string"
					},
					"siteName": {
						"minLength": 1,
						"type": "string"
					}
				},
				"required": [
					"inspectionId",
					"siteId",
					"siteName",
					"assetName",
					"checklistName",
					"priority",
					"scheduledFor"
				],
				"type": "object"
			},
			"type": "array"
		},
		"limit": {
			"minimum": 0,
			"type": "integer"
		},
		"nextOffset": {
			"minimum": 0,
			"type": "integer"
		},
		"offset": {
			"minimum": 0,
			"type": "integer"
		}
	},
	"required": [
		"entries",
		"count",
		"offset",
		"limit"
	],
	"type": "object"
};
export const AuditRecordedEventSchema = {
	"properties": {
		"activityId": {
			"minLength": 1,
			"type": "string"
		},
		"kind": {
			"minLength": 1,
			"type": "string"
		},
		"message": {
			"minLength": 1,
			"type": "string"
		},
		"occurredAt": {
			"minLength": 1,
			"type": "string"
		},
		"relatedInspectionId": {
			"minLength": 1,
			"type": "string"
		},
		"relatedSiteId": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"activityId",
		"kind",
		"message",
		"occurredAt"
	],
	"type": "object"
};
export const EvidenceDeleteRequestSchema = {
	"properties": { "key": {
		"minLength": 1,
		"type": "string"
	} },
	"required": ["key"],
	"type": "object"
};
export const EvidenceDeleteResponseSchema = {
	"properties": {
		"deleted": { "type": "boolean" },
		"key": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": ["key", "deleted"],
	"type": "object"
};
export const EvidenceDownloadRequestSchema = {
	"properties": { "key": {
		"minLength": 1,
		"type": "string"
	} },
	"required": ["key"],
	"type": "object"
};
export const EvidenceDownloadResponseSchema = {
	"properties": { "transfer": {
		"properties": {
			"chunkBytes": {
				"minimum": 1,
				"type": "integer"
			},
			"direction": {
				"const": "receive",
				"type": "string"
			},
			"expiresAt": {
				"minLength": 1,
				"type": "string"
			},
			"info": {
				"properties": {
					"contentType": {
						"minLength": 1,
						"type": "string"
					},
					"digest": {
						"minLength": 1,
						"type": "string"
					},
					"key": {
						"minLength": 1,
						"type": "string"
					},
					"metadata": {
						"additionalProperties": { "type": "string" },
						"type": "object"
					},
					"size": {
						"minimum": 0,
						"type": "integer"
					},
					"updatedAt": {
						"minLength": 1,
						"type": "string"
					}
				},
				"required": [
					"key",
					"size",
					"updatedAt",
					"digest",
					"metadata"
				],
				"type": "object"
			},
			"service": {
				"minLength": 1,
				"type": "string"
			},
			"sessionKey": {
				"minLength": 1,
				"type": "string"
			},
			"subject": {
				"minLength": 1,
				"type": "string"
			},
			"transferId": {
				"minLength": 1,
				"type": "string"
			},
			"type": {
				"const": "TransferGrant",
				"type": "string"
			}
		},
		"required": [
			"type",
			"direction",
			"service",
			"sessionKey",
			"transferId",
			"subject",
			"expiresAt",
			"chunkBytes",
			"info"
		],
		"type": "object"
	} },
	"required": ["transfer"],
	"type": "object"
};
export const EvidenceListRequestSchema = {
	"properties": {
		"limit": {
			"maximum": 500,
			"minimum": 0,
			"type": "integer"
		},
		"offset": {
			"minimum": 0,
			"type": "integer"
		},
		"prefix": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": ["limit"],
	"type": "object"
};
export const EvidenceListResponseSchema = {
	"properties": {
		"count": {
			"minimum": 0,
			"type": "integer"
		},
		"entries": {
			"items": {
				"properties": {
					"contentType": {
						"minLength": 1,
						"type": "string"
					},
					"evidenceId": {
						"minLength": 1,
						"type": "string"
					},
					"evidenceType": {
						"minLength": 1,
						"type": "string"
					},
					"fileName": {
						"minLength": 1,
						"type": "string"
					},
					"key": {
						"minLength": 1,
						"type": "string"
					},
					"size": {
						"minimum": 0,
						"type": "integer"
					},
					"uploadedAt": {
						"minLength": 1,
						"type": "string"
					}
				},
				"required": [
					"evidenceId",
					"key",
					"size",
					"evidenceType",
					"uploadedAt"
				],
				"type": "object"
			},
			"type": "array"
		},
		"limit": {
			"minimum": 0,
			"type": "integer"
		},
		"nextOffset": {
			"minimum": 0,
			"type": "integer"
		},
		"offset": {
			"minimum": 0,
			"type": "integer"
		}
	},
	"required": [
		"entries",
		"count",
		"offset",
		"limit"
	],
	"type": "object"
};
export const EvidenceRecordSchema = {
	"properties": {
		"contentType": {
			"minLength": 1,
			"type": "string"
		},
		"evidenceId": {
			"minLength": 1,
			"type": "string"
		},
		"evidenceType": {
			"minLength": 1,
			"type": "string"
		},
		"fileName": {
			"minLength": 1,
			"type": "string"
		},
		"key": {
			"minLength": 1,
			"type": "string"
		},
		"size": {
			"minimum": 0,
			"type": "integer"
		},
		"uploadedAt": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"evidenceId",
		"key",
		"size",
		"evidenceType",
		"uploadedAt"
	],
	"type": "object"
};
export const EvidenceUploadProgressSchema = {
	"properties": {
		"message": {
			"minLength": 1,
			"type": "string"
		},
		"stage": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": ["stage", "message"],
	"type": "object"
};
export const EvidenceUploadRequestSchema = {
	"properties": {
		"contentType": {
			"minLength": 1,
			"type": "string"
		},
		"evidenceType": {
			"minLength": 1,
			"type": "string"
		},
		"key": {
			"minLength": 1,
			"type": "string"
		},
		"metadata": {
			"additionalProperties": { "type": "string" },
			"type": "object"
		}
	},
	"required": ["key", "evidenceType"],
	"type": "object"
};
export const EvidenceUploadResponseSchema = {
	"properties": {
		"contentType": {
			"minLength": 1,
			"type": "string"
		},
		"disposition": {
			"minLength": 1,
			"type": "string"
		},
		"evidenceId": {
			"minLength": 1,
			"type": "string"
		},
		"fileName": {
			"minLength": 1,
			"type": "string"
		},
		"key": {
			"minLength": 1,
			"type": "string"
		},
		"size": {
			"minimum": 0,
			"type": "integer"
		}
	},
	"required": [
		"evidenceId",
		"key",
		"size",
		"disposition"
	],
	"type": "object"
};
export const EvidenceUploadedEventSchema = {
	"properties": {
		"contentType": {
			"minLength": 1,
			"type": "string"
		},
		"evidenceId": {
			"minLength": 1,
			"type": "string"
		},
		"evidenceType": {
			"minLength": 1,
			"type": "string"
		},
		"fileName": {
			"minLength": 1,
			"type": "string"
		},
		"key": {
			"minLength": 1,
			"type": "string"
		},
		"size": {
			"minimum": 0,
			"type": "integer"
		},
		"uploadedAt": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"evidenceId",
		"key",
		"size",
		"evidenceType",
		"uploadedAt"
	],
	"type": "object"
};
export const InspectionAssignmentSchema = {
	"properties": {
		"assetName": {
			"minLength": 1,
			"type": "string"
		},
		"checklistName": {
			"minLength": 1,
			"type": "string"
		},
		"inspectionId": {
			"minLength": 1,
			"type": "string"
		},
		"priority": { "anyOf": [
			{
				"const": "high",
				"type": "string"
			},
			{
				"const": "medium",
				"type": "string"
			},
			{
				"const": "low",
				"type": "string"
			}
		] },
		"scheduledFor": {
			"minLength": 1,
			"type": "string"
		},
		"siteId": {
			"minLength": 1,
			"type": "string"
		},
		"siteName": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"inspectionId",
		"siteId",
		"siteName",
		"assetName",
		"checklistName",
		"priority",
		"scheduledFor"
	],
	"type": "object"
};
export const ReportRecordSchema = {
	"properties": {
		"assetName": {
			"minLength": 1,
			"type": "string"
		},
		"evidenceStatus": {
			"minLength": 1,
			"type": "string"
		},
		"inspectionId": {
			"minLength": 1,
			"type": "string"
		},
		"publishedAt": {
			"minLength": 1,
			"type": "string"
		},
		"readiness": {
			"minLength": 1,
			"type": "string"
		},
		"reportComment": {
			"minLength": 1,
			"pattern": "\\S",
			"type": "string"
		},
		"reportId": {
			"minLength": 1,
			"type": "string"
		},
		"siteId": {
			"minLength": 1,
			"type": "string"
		},
		"siteName": {
			"minLength": 1,
			"type": "string"
		},
		"status": {
			"minLength": 1,
			"type": "string"
		},
		"summary": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"reportId",
		"inspectionId",
		"siteName",
		"assetName",
		"status",
		"publishedAt",
		"reportComment",
		"summary",
		"readiness",
		"evidenceStatus"
	],
	"type": "object"
};
export const ReportsGenerateProgressSchema = {
	"properties": {
		"message": {
			"minLength": 1,
			"type": "string"
		},
		"stage": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": ["stage", "message"],
	"type": "object"
};
export const ReportsGenerateRequestSchema = {
	"properties": {
		"inspectionId": {
			"minLength": 1,
			"type": "string"
		},
		"reportComment": {
			"minLength": 1,
			"pattern": "\\S",
			"type": "string"
		}
	},
	"required": ["inspectionId", "reportComment"],
	"type": "object"
};
export const ReportsGenerateResponseSchema = {
	"properties": {
		"inspectionId": {
			"minLength": 1,
			"type": "string"
		},
		"reportId": {
			"minLength": 1,
			"type": "string"
		},
		"status": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"reportId",
		"inspectionId",
		"status"
	],
	"type": "object"
};
export const ReportsListRequestSchema = {
	"properties": {
		"limit": {
			"maximum": 500,
			"minimum": 0,
			"type": "integer"
		},
		"offset": {
			"minimum": 0,
			"type": "integer"
		}
	},
	"required": ["limit"],
	"type": "object"
};
export const ReportsListResponseSchema = {
	"properties": {
		"count": {
			"minimum": 0,
			"type": "integer"
		},
		"entries": {
			"items": {
				"properties": {
					"assetName": {
						"minLength": 1,
						"type": "string"
					},
					"evidenceStatus": {
						"minLength": 1,
						"type": "string"
					},
					"inspectionId": {
						"minLength": 1,
						"type": "string"
					},
					"publishedAt": {
						"minLength": 1,
						"type": "string"
					},
					"readiness": {
						"minLength": 1,
						"type": "string"
					},
					"reportComment": {
						"minLength": 1,
						"pattern": "\\S",
						"type": "string"
					},
					"reportId": {
						"minLength": 1,
						"type": "string"
					},
					"siteId": {
						"minLength": 1,
						"type": "string"
					},
					"siteName": {
						"minLength": 1,
						"type": "string"
					},
					"status": {
						"minLength": 1,
						"type": "string"
					},
					"summary": {
						"minLength": 1,
						"type": "string"
					}
				},
				"required": [
					"reportId",
					"inspectionId",
					"siteName",
					"assetName",
					"status",
					"publishedAt",
					"reportComment",
					"summary",
					"readiness",
					"evidenceStatus"
				],
				"type": "object"
			},
			"type": "array"
		},
		"limit": {
			"minimum": 0,
			"type": "integer"
		},
		"nextOffset": {
			"minimum": 0,
			"type": "integer"
		},
		"offset": {
			"minimum": 0,
			"type": "integer"
		}
	},
	"required": [
		"entries",
		"count",
		"offset",
		"limit"
	],
	"type": "object"
};
export const ReportsPublishedEventSchema = {
	"properties": {
		"inspectionId": {
			"minLength": 1,
			"type": "string"
		},
		"publishedAt": {
			"minLength": 1,
			"type": "string"
		},
		"reportId": {
			"minLength": 1,
			"type": "string"
		},
		"siteId": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"reportId",
		"inspectionId",
		"publishedAt"
	],
	"type": "object"
};
export const SiteRefreshJobPayloadSchema = {
	"properties": { "siteId": {
		"minLength": 1,
		"type": "string"
	} },
	"required": ["siteId"],
	"type": "object"
};
export const SiteSummarySchema = {
	"properties": {
		"lastReportAt": {
			"minLength": 1,
			"type": "string"
		},
		"latestStatus": {
			"minLength": 1,
			"type": "string"
		},
		"openInspections": {
			"minimum": 0,
			"type": "integer"
		},
		"overdueInspections": {
			"minimum": 0,
			"type": "integer"
		},
		"siteId": {
			"minLength": 1,
			"type": "string"
		},
		"siteName": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"siteId",
		"siteName",
		"openInspections",
		"overdueInspections",
		"latestStatus",
		"lastReportAt"
	],
	"type": "object"
};
export const SitesGetRequestSchema = {
	"properties": { "siteId": {
		"minLength": 1,
		"type": "string"
	} },
	"required": ["siteId"],
	"type": "object"
};
export const SitesGetResponseSchema = {
	"properties": { "site": {
		"properties": {
			"lastReportAt": {
				"minLength": 1,
				"type": "string"
			},
			"latestStatus": {
				"minLength": 1,
				"type": "string"
			},
			"openInspections": {
				"minimum": 0,
				"type": "integer"
			},
			"overdueInspections": {
				"minimum": 0,
				"type": "integer"
			},
			"siteId": {
				"minLength": 1,
				"type": "string"
			},
			"siteName": {
				"minLength": 1,
				"type": "string"
			}
		},
		"required": [
			"siteId",
			"siteName",
			"openInspections",
			"overdueInspections",
			"latestStatus",
			"lastReportAt"
		],
		"type": "object"
	} },
	"type": "object"
};
export const SitesListRequestSchema = {
	"properties": {
		"limit": {
			"maximum": 500,
			"minimum": 0,
			"type": "integer"
		},
		"offset": {
			"minimum": 0,
			"type": "integer"
		}
	},
	"required": ["limit"],
	"type": "object"
};
export const SitesListResponseSchema = {
	"properties": {
		"count": {
			"minimum": 0,
			"type": "integer"
		},
		"entries": {
			"items": {
				"properties": {
					"lastReportAt": {
						"minLength": 1,
						"type": "string"
					},
					"latestStatus": {
						"minLength": 1,
						"type": "string"
					},
					"openInspections": {
						"minimum": 0,
						"type": "integer"
					},
					"overdueInspections": {
						"minimum": 0,
						"type": "integer"
					},
					"siteId": {
						"minLength": 1,
						"type": "string"
					},
					"siteName": {
						"minLength": 1,
						"type": "string"
					}
				},
				"required": [
					"siteId",
					"siteName",
					"openInspections",
					"overdueInspections",
					"latestStatus",
					"lastReportAt"
				],
				"type": "object"
			},
			"type": "array"
		},
		"limit": {
			"minimum": 0,
			"type": "integer"
		},
		"nextOffset": {
			"minimum": 0,
			"type": "integer"
		},
		"offset": {
			"minimum": 0,
			"type": "integer"
		}
	},
	"required": [
		"entries",
		"count",
		"offset",
		"limit"
	],
	"type": "object"
};
export const SitesRefreshProgressSchema = {
	"properties": {
		"message": {
			"minLength": 1,
			"type": "string"
		},
		"stage": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": ["stage", "message"],
	"type": "object"
};
export const SitesRefreshRequestSchema = {
	"properties": { "siteId": {
		"minLength": 1,
		"type": "string"
	} },
	"required": ["siteId"],
	"type": "object"
};
export const SitesRefreshResponseSchema = {
	"properties": {
		"refreshId": {
			"minLength": 1,
			"type": "string"
		},
		"site": {
			"properties": {
				"lastReportAt": {
					"minLength": 1,
					"type": "string"
				},
				"latestStatus": {
					"minLength": 1,
					"type": "string"
				},
				"openInspections": {
					"minimum": 0,
					"type": "integer"
				},
				"overdueInspections": {
					"minimum": 0,
					"type": "integer"
				},
				"siteId": {
					"minLength": 1,
					"type": "string"
				},
				"siteName": {
					"minLength": 1,
					"type": "string"
				}
			},
			"required": [
				"siteId",
				"siteName",
				"openInspections",
				"overdueInspections",
				"latestStatus",
				"lastReportAt"
			],
			"type": "object"
		},
		"status": {
			"minLength": 1,
			"type": "string"
		}
	},
	"required": [
		"refreshId",
		"site",
		"status"
	],
	"type": "object"
};
export const SitesRefreshedEventSchema = {
	"properties": {
		"refreshId": {
			"minLength": 1,
			"type": "string"
		},
		"refreshedAt": {
			"minLength": 1,
			"type": "string"
		},
		"site": {
			"properties": {
				"lastReportAt": {
					"minLength": 1,
					"type": "string"
				},
				"latestStatus": {
					"minLength": 1,
					"type": "string"
				},
				"openInspections": {
					"minimum": 0,
					"type": "integer"
				},
				"overdueInspections": {
					"minimum": 0,
					"type": "integer"
				},
				"siteId": {
					"minLength": 1,
					"type": "string"
				},
				"siteName": {
					"minLength": 1,
					"type": "string"
				}
			},
			"required": [
				"siteId",
				"siteName",
				"openInspections",
				"overdueInspections",
				"latestStatus",
				"lastReportAt"
			],
			"type": "object"
		}
	},
	"required": [
		"refreshId",
		"site",
		"refreshedAt"
	],
	"type": "object"
};
