// Generated by Trellis. Do not edit.
// @ts-self-types="./types.d.ts"
import { TrellisError } from "@qlever-llc/trellis";
export class TransferError extends TrellisError {
	name = "TransferError";
	data;
	constructor(data) {
		super(data.message, {
			id: data.id,
			...data.context !== undefined ? { context: data.context } : {}
		});
		this.data = data;
	}
	static fromSerializable(data) {
		return new TransferError(data);
	}
	toSerializable() {
		return this.data;
	}
}
export class UnexpectedError extends TrellisError {
	name = "UnexpectedError";
	data;
	constructor(data) {
		super(data.message, {
			id: data.id,
			...data.context !== undefined ? { context: data.context } : {}
		});
		this.data = data;
	}
	static fromSerializable(data) {
		return new UnexpectedError(data);
	}
	toSerializable() {
		return this.data;
	}
}
