[package]
name = "trellis-contracts"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Native API and participant authoring for Trellis."
readme = "../../README.md"

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
trellis-protocol.workspace = true
