// Generated by Trellis. Do not edit.
//! Activated-device connection entry point for this participant.
use super::Client;
use std::sync::Arc;
use trellis_rs::generated::{
    AuthorizationContextStore, Caller, DeviceConnectOptions, TrellisClientError,
};
/// Exact generated participant and API evidence used for device bootstrap.
pub struct Participant;
impl trellis_rs::service::GeneratedServiceParticipant for Participant {
    const PARTICIPANT_ID: &'static str = super::participant::PARTICIPANT_ID;
    const PARTICIPANT_DIGEST: &'static str = super::participant::PARTICIPANT_DIGEST;
    const PARTICIPANT_NEEDS_DIGEST: &'static str = super::participant::PARTICIPANT_NEEDS_DIGEST;
    const PARTICIPANT_JSON: &'static str = super::participant::PARTICIPANT;
    const API_JSON: &'static str = super::participant::API_JSON;
    const API_DIGEST: &'static str = super::participant::API_DIGEST;
    const REFERENCED_API_ARTIFACTS: &'static [(&'static str, &'static str)] =
        super::participant::REFERENCED_API_ARTIFACTS;
}
/// Activated-device participant connection options.
pub struct ConnectOptions<'a> {
    trellis_url: &'a str,
    deployment_id: &'a str,
    instance_id: &'a str,
    public_identity_key: &'a str,
    identity_seed_base64url: &'a str,
    timeout_ms: u64,
    authorization_context_store: Arc<dyn AuthorizationContextStore>,
}
impl<'a> ConnectOptions<'a> {
    /// Create activated-device connection options.
    pub fn new(
        trellis_url: &'a str,
        deployment_id: &'a str,
        instance_id: &'a str,
        public_identity_key: &'a str,
        identity_seed_base64url: &'a str,
        timeout_ms: u64,
        authorization_context_store: Arc<dyn AuthorizationContextStore>,
    ) -> Self {
        Self {
            trellis_url,
            deployment_id,
            instance_id,
            public_identity_key,
            identity_seed_base64url,
            timeout_ms,
            authorization_context_store,
        }
    }
}
/// Connected caller facade for this participant contract.
pub struct ConnectedClient {
    inner: Caller,
}
impl ConnectedClient {
    /// Access only the contract surfaces declared by this participant.
    pub fn client(&self) -> Client<'_> {
        Client::new(&self.inner)
    }
    /// Connect using the exact ready bootstrap evidence returned by device activation.
    pub async fn connect_activated(
        options: trellis_rs::auth::DeviceActivationOptions<'_, Participant>,
        session: trellis_rs::auth::DeviceActivationSession,
    ) -> Result<Self, trellis_rs::auth::DeviceActivationError> {
        Ok(Self {
            inner: Caller::connect_device(options.into_connect_options(session)?).await?,
        })
    }
}
/// Connect this activated device.
pub async fn connect(opts: ConnectOptions<'_>) -> Result<ConnectedClient, TrellisClientError> {
    Ok(ConnectedClient {
        inner: Caller::connect_device(
            DeviceConnectOptions::<Participant>::new(
                opts.trellis_url,
                opts.deployment_id,
                opts.instance_id,
                opts.public_identity_key,
                opts.identity_seed_base64url,
                opts.authorization_context_store,
            )
            .with_timeout_ms(opts.timeout_ms),
        )
        .await?,
    })
}
impl ConnectedClient {
    /// Access the `fieldOps` dependency surface.
    pub fn field_ops(&self) -> super::uses::field_ops::Client<'_> {
        super::Client::new(&self.inner).field_ops()
    }
}
