// Generated by Trellis. Do not edit.
//! Generated Rust participant facade crate.
const _: () = trellis_rs::generated::assert_abi(1);
pub mod connect;
pub mod participant;
include!("facade.rs");
pub use connect::{connect, ConnectOptions, ConnectedClient, Participant};
