// Generated by Trellis. Do not edit.
// Generated from test.runtime@v1
export declare const EmptySchema: {
	readonly properties: {};
	readonly type: "object";
};
export declare const ValueSchema: {
	readonly properties: {
		readonly value: {
			readonly type: "string";
		};
	};
	readonly required: readonly ["value"];
	readonly type: "object";
};
