// Generated by Trellis. Do not edit.
// Generated from test.runtime@v1
export type EchoInput = {
	value: string;
};
export type EchoOutput = {
	value: string;
};
export type UploadInput = {
	value: string;
};
export type UploadOutput = {
	value: string;
};
export type WorkInput = {
	value: string;
};
export type WorkOutput = {
	value: string;
};
export type ChangedEvent = {
	value: string;
};
export type WatchInput = {};
export type WatchEvent = {
	value: string;
};
