// Generated by Trellis. Do not edit.
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_EVENT_CONSUMERS_METADATA, PARTICIPANT_RUNTIME, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/test-events/mod.js";
declare const __ownedActions: readonly [typeof Api0.ACTIONS["Alpha"]["publish"], typeof Api0.ACTIONS["Alpha"]["subscribe"], typeof Api0.ACTIONS["Beta"]["publish"], typeof Api0.ACTIONS["Beta"]["subscribe"], typeof Api0.ACTIONS["DropAlpha"], typeof Api0.ACTIONS["Observed"]];
declare const __usedActions: readonly [];
declare const __allActions: readonly [typeof Api0.ACTIONS["Alpha"]["publish"], typeof Api0.ACTIONS["Alpha"]["subscribe"], typeof Api0.ACTIONS["Beta"]["publish"], typeof Api0.ACTIONS["Beta"]["subscribe"], typeof Api0.ACTIONS["DropAlpha"], typeof Api0.ACTIONS["Observed"]];
declare const __participant: {
	readonly id: "test.events";
	readonly digest: "o3awyoDoCj895_YcwEsP2GCbnvtVXz8JaWmvErHfy58";
	readonly artifact: {
		readonly description: "Distinct publisher authority on one consumer.";
		readonly displayName: "Durable event acceptance";
		readonly eventConsumers: {
			readonly events: {
				readonly events: {
					readonly self: readonly ["Alpha", "Beta"];
				};
			};
		};
		readonly format: "trellis.participant.v1";
		readonly id: "test.events";
		readonly implements: {
			readonly self: {
				readonly api: "test.events@v1";
				readonly apiDigest: "D2ZBsIpJt42ku6yDI4xFynOUY2UI7YkxadXfTqQpm0g";
			};
		};
		readonly kind: "service";
		readonly schemas: {
			readonly Empty: {
				readonly properties: {};
				readonly type: "object";
			};
			readonly Observed: {
				readonly properties: {
					readonly values: {
						readonly items: {
							readonly type: "string";
						};
						readonly type: "array";
					};
				};
				readonly required: readonly ["values"];
				readonly type: "object";
			};
			readonly Sample: {
				readonly properties: {
					readonly site: {
						readonly type: "string";
					};
					readonly value: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["site", "value"];
				readonly type: "object";
			};
		};
	};
	readonly api: typeof Api0.API;
	readonly apiDigest: typeof Api0.API_DIGEST;
	readonly referencedApis: readonly [];
	readonly Alpha: typeof Api0.ACTIONS["Alpha"];
	readonly Beta: typeof Api0.ACTIONS["Beta"];
	readonly DropAlpha: typeof Api0.ACTIONS["DropAlpha"];
	readonly Observed: typeof Api0.ACTIONS["Observed"];
};
declare const __metadata: {
	readonly PARTICIPANT_RUNTIME: {
		readonly ownedApi: ReturnType<typeof runtimeApiFromActions<typeof __ownedActions>>;
		readonly usedApi: ReturnType<typeof runtimeApiFromActions<typeof __usedActions>>;
		readonly api: ReturnType<typeof runtimeApiFromActions<typeof __allActions>>;
		readonly actions: readonly [{
			readonly action: typeof Api0.ACTIONS["Alpha"]["publish"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Alpha"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Beta"]["publish"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Beta"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["DropAlpha"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Observed"];
			readonly optional: false;
		}];
	};
	readonly PARTICIPANT_EVENT_CONSUMERS_METADATA: {
		readonly events: {
			readonly self: readonly ["Alpha", "Beta"];
		};
	};
};
export declare const participant: typeof __participant & {
	readonly [PARTICIPANT_RUNTIME]: typeof __metadata.PARTICIPANT_RUNTIME;
	readonly [PARTICIPANT_EVENT_CONSUMERS_METADATA]: typeof __metadata.PARTICIPANT_EVENT_CONSUMERS_METADATA;
};
export default participant;
