// Generated by Trellis. Do not edit.
//! API metadata for `demo.device@v1`.
//! Generated from demo.device@v1
/// Canonical Trellis API id.
pub const API_ID: &str = "demo.device@v1";
/// Stable digest for the canonical API JSON.
pub const API_DIGEST: &str = "mEmDg58k8Xb_TdI_j8-cQK5KsPvLzxdYD3Hmm0O4yL8";
/// Human-readable API name.
pub const API_NAME: &str = "Field Device Demo";
/// Canonical API JSON embedded in the SDK crate.
pub const API_JSON: &str = "{\"description\":\"Activated Field Device TUI for the consolidated demo.\",\"displayName\":\"Field Device Demo\",\"docs\":{\"markdown\":\"Declares the Field Device demo's service usage and local state for selected sites and draft inspections.\",\"summary\":\"Activated field device demo.\"},\"exports\":{\"schemas\":[\"DraftInspectionState\",\"SelectedSiteState\"]},\"format\":\"trellis.api.v1\",\"id\":\"demo.device@v1\",\"schemas\":{\"DraftInspectionState\":{\"properties\":{\"checklistName\":{\"type\":\"string\"},\"inspectionId\":{\"type\":\"string\"},\"notes\":{\"type\":\"string\"},\"siteId\":{\"type\":\"string\"},\"updatedAt\":{\"type\":\"string\"}},\"required\":[\"inspectionId\",\"siteId\",\"checklistName\",\"notes\",\"updatedAt\"],\"type\":\"object\"},\"SelectedSiteState\":{\"properties\":{\"selectedAt\":{\"type\":\"string\"},\"siteId\":{\"type\":\"string\"},\"siteName\":{\"type\":\"string\"}},\"required\":[\"siteId\",\"siteName\",\"selectedAt\"],\"type\":\"object\"}},\"version\":\"1.0.0\"}";
/// Deserialize the embedded API artifact as JSON.
pub fn api_artifact() -> serde_json::Value {
    serde_json::from_str(API_JSON).expect("generated API JSON")
}
/// Register every generated RPC descriptor as router metadata.
pub fn register_rpc_metadata(router: &mut trellis_rs::service::Router) {
    router.set_api_id(API_ID);
}
