// Generated by Trellis. Do not edit.
// Generated from trellis-app.portal@v1
export declare const API_ID: "trellis-app.portal@v1";
export declare const API_DIGEST: "DReps_YCRCgd9JCCgTEKtxr7S9AunoqhMR-cz-rObg4";
export declare const API: {
	readonly description: "Trellis built-in app for authenticated device activation over the Auth.DeviceUserAuthorities.Resolve operation.";
	readonly displayName: "Trellis Device Activation";
	readonly format: "trellis.api.v1";
	readonly id: "trellis-app.portal@v1";
	readonly version: "1.0.0";
};
