// Generated by Trellis. Do not edit.
// @ts-self-types="./mod.d.ts"
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_RUNTIME, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/test-client/mod.js";
import * as Api1 from "../../apis/test-events/mod.js";
function typeOnly() {
	return undefined;
}
const __ownedActions = [];
const __usedActions = [Api1.ACTIONS["Beta"]["publish"]];
const __allActions = [Api1.ACTIONS["Beta"]["publish"]];
const __participant = {
	id: "test.beta",
	digest: "p_HZjQU57Cm9uGfYC3CsHsm5ZzIocS7hYwtUnn4bZV8",
	artifact: {
		"description": "Caller-owned state.",
		"displayName": "Runtime caller",
		"format": "trellis.participant.v1",
		"id": "test.beta",
		"implements": { "self": {
			"api": "test.client@v1",
			"apiDigest": "o8El02dTOgwoMQysX9wgZj3Tp4RHGljAroEj0Q1fGPw"
		} },
		"kind": "app",
		"schemas": { "Saved": {
			"properties": { "value": { "type": "string" } },
			"required": ["value"],
			"type": "object"
		} },
		"uses": { "required": { "events": {
			"api": "test.events@v1",
			"apiDigest": "D2ZBsIpJt42ku6yDI4xFynOUY2UI7YkxadXfTqQpm0g",
			"events": { "publish": ["Beta"] }
		} } }
	},
	api: Api0.API,
	apiDigest: Api0.API_DIGEST,
	referencedApis: [Api1.API]
};
const __metadata = { PARTICIPANT_RUNTIME: {
	ownedApi: runtimeApiFromActions(__ownedActions, {}),
	usedApi: runtimeApiFromActions(__usedActions),
	api: runtimeApiFromActions(__allActions, {}),
	actions: [{
		action: Api1.ACTIONS["Beta"]["publish"],
		optional: false
	}]
} };
export const participant = {
	...__participant,
	[PARTICIPANT_RUNTIME]: __metadata.PARTICIPANT_RUNTIME
};
export default participant;
