<script lang="ts">
  import { browser } from "$app/environment";
  import { onMount } from "svelte";
  import PortalBrand from "$lib/components/PortalBrand.svelte";
  import { trellisUrl } from "$lib/config";
  import {
    adminBootstrapFlowId,
    accountFlowProviderLoginUrl,
    completeAdminBootstrap,
    hasLocalProvider,
    loadAccountFlowState,
    parseAccountFlowOAuthCompletion,
    unavailableProviders,
    type AccountFlowState,
    type AdminBootstrapSuccess,
  } from "./page_state";

  let username = $state("");
  let password = $state("");
  let name = $state("");
  let email = $state("");
  let flowId = $state<string | null>(null);
  let flowState = $state.raw<AccountFlowState | null>(null);
  let loading = $state(true);
  let error = $state<string | null>(null);
  let submitting = $state(false);
  let completion = $state<AdminBootstrapSuccess | null>(null);

  const active = $derived(flowState?.status === "active" ? flowState : null);
  const loadedTerminalFlow = $derived(flowState?.status === "expired" || flowState?.status === "consumed");
  const localAvailable = $derived(active ? hasLocalProvider(active) : flowState === null);
  const canSubmit = $derived(
    Boolean(flowId) && !loadedTerminalFlow && localAvailable && username.trim().length > 0 && password.length > 0 && !submitting && !completion,
  );

  function currentFlowId(): string | null {
    if (!browser) return null;
    return adminBootstrapFlowId(new URL(window.location.href));
  }

  function currentOAuthCompletion(): AdminBootstrapSuccess | null {
    if (!browser) return null;
    const completionState = parseAccountFlowOAuthCompletion(new URL(window.location.href));
    return completionState ? { status: "created", userId: completionState.userId } : null;
  }

  function refreshFlowId(): string | null {
    flowId = currentFlowId();
    if (!flowId) {
      error = "Missing bootstrap flow id. Open the bootstrap link generated by Trellis.";
    }
    return flowId;
  }

  async function loadFlow(): Promise<void> {
    const oauthCompletion = currentOAuthCompletion();
    if (oauthCompletion) {
      flowId = currentFlowId();
      completion = oauthCompletion;
      loading = false;
      error = null;
      return;
    }

    const activeFlowId = refreshFlowId();
    if (!activeFlowId) {
      loading = false;
      return;
    }

    loading = true;
    error = null;
    try {
      flowState = await loadAccountFlowState(trellisUrl, activeFlowId);
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      loading = false;
    }
  }

  async function submitBootstrap(): Promise<void> {
    const activeFlowId = refreshFlowId();
    if (!activeFlowId || loadedTerminalFlow) return;

    submitting = true;
    error = null;

    try {
      completion = await completeAdminBootstrap(trellisUrl, activeFlowId, {
        username: username.trim(),
        password,
        name,
        email,
      });
    } catch (caught) {
      error = caught instanceof Error ? caught.message : String(caught);
    } finally {
      submitting = false;
    }
  }

  onMount(() => {
    void loadFlow();
  });
</script>

<svelte:head>
  <title>Bootstrap admin · Trellis</title>
</svelte:head>

<div
  class="portal-shell flex min-h-screen flex-col items-center justify-center gap-7 px-4 py-10 sm:px-6"
  data-theme="portal"
>
  <div class="portal-card card w-full max-w-md border border-base-300">
    <div class="card-body gap-6 p-7 sm:p-8">
      <div class="flex justify-center">
        <PortalBrand subtitle="Admin bootstrap" />
      </div>

      {#if loading}
        <div class="flex items-center gap-4 py-3" aria-live="polite">
          <span class="loading loading-ring loading-lg" aria-hidden="true"></span>
          <div>
            <p class="text-sm font-medium text-base-content">Loading bootstrap</p>
            <p class="portal-copy text-xs">Resolving account-flow state.</p>
          </div>
        </div>
      {:else if completion}
        <div>
          <h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Admin account ready</h1>
          <p class="portal-copy mt-2 text-sm">
            The first admin account is ready. You can now sign in and
            finish configuring Trellis.
          </p>
        </div>

        <div class="portal-subtle-panel rounded-box p-4 text-sm leading-6 text-base-content/70">
          <p class="portal-section-label">Admin user</p>
          <p class="mono mt-1 break-all text-base-content">{completion.userId}</p>
        </div>

        <p class="portal-copy text-sm">
          Open a Trellis app login page to start a new sign-in flow.
        </p>
      {:else if flowState?.status === "expired"}
        <div>
          <h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Bootstrap link expired</h1>
          <p class="portal-copy mt-2 text-sm">
            This admin bootstrap request is missing or no longer active. Start bootstrap again.
          </p>
        </div>
      {:else if flowState?.status === "consumed"}
        <div>
          <h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Bootstrap already used</h1>
          <p class="portal-copy mt-2 text-sm">
            This admin bootstrap request has already been completed.
          </p>
        </div>
      {:else}
        <div>
          <h1 class="text-xl font-semibold tracking-[-0.025em] text-base-content">Create the first admin</h1>
          <p class="portal-copy mt-2 text-sm">
            Choose local credentials for the built-in administrator account.
          </p>
        </div>

        {#if active}
          {#each unavailableProviders(active) as provider (provider.id)}
            <a class="btn btn-outline btn-block" href={accountFlowProviderLoginUrl(trellisUrl, active.flowId, provider.id)}>
              Continue with {provider.displayName}
            </a>
          {/each}
        {/if}

        {#if active && !hasLocalProvider(active)}
          <div class="alert alert-info text-sm" role="alert">
            <span>This bootstrap request does not allow username and password setup.</span>
          </div>
        {:else}

        <form
          class="grid gap-4"
          onsubmit={(event) => {
            event.preventDefault();
            void submitBootstrap();
          }}
        >
          <label class="form-control gap-1.5">
            <span class="label-text text-sm font-medium text-base-content">Username</span>
            <input
              class="input input-bordered w-full"
              autocomplete="username"
              disabled={submitting || !flowId}
              required
              bind:value={username}
            />
          </label>

          <label class="form-control gap-1.5">
            <span class="label-text text-sm font-medium text-base-content">Password</span>
            <input
              class="input input-bordered w-full"
              autocomplete="new-password"
              disabled={submitting || !flowId}
              required
              type="password"
              bind:value={password}
            />
          </label>

          <label class="form-control gap-1.5">
            <span class="label-text text-sm font-medium text-base-content">Name <span class="font-normal text-base-content/45">optional</span></span>
            <input
              class="input input-bordered w-full"
              autocomplete="name"
              disabled={submitting || !flowId}
              bind:value={name}
            />
          </label>

          <label class="form-control gap-1.5">
            <span class="label-text text-sm font-medium text-base-content">Email <span class="font-normal text-base-content/45">optional</span></span>
            <input
              class="input input-bordered w-full"
              autocomplete="email"
              disabled={submitting || !flowId}
              type="email"
              bind:value={email}
            />
          </label>

          <button class="btn btn-primary btn-block" disabled={!canSubmit} type="submit">
            {#if submitting}
              <span class="loading loading-spinner loading-sm" aria-hidden="true"></span>
              Creating admin...
            {:else}
              Create admin account
            {/if}
          </button>
        </form>
        {/if}
      {/if}

      {#if submitting}
        <p class="portal-copy text-sm" aria-live="polite">Submitting admin bootstrap...</p>
      {/if}

      {#if error}
        <div class="alert alert-error text-sm" role="alert">
          <span>{error}</span>
        </div>
      {/if}
    </div>
  </div>
</div>
