// Generated by Trellis. Do not edit.
/// Facade for the `fieldOps` dependency alias.
use crate::apis::demo_service as sdk;
pub struct Client<'a> {
    inner: sdk::DemoServiceClient<'a>,
    transport: &'a trellis_rs::generated::Caller,
}
impl<'a> Client<'a> {
    pub fn new(inner: &'a trellis_rs::generated::Caller) -> Self {
        Self {
            inner: sdk::DemoServiceClient::new(inner),
            transport: inner,
        }
    }
    pub const API_ID: &'static str = "demo.service@v1";
    pub async fn assignments_list(
        &self,
        input: &sdk::AssignmentsListRequest,
    ) -> Result<
        sdk::AssignmentsListResponse,
        trellis_rs::generated::CallError<sdk::rpc::AssignmentsListError>,
    > {
        self.inner.rpc().assignments().list(input).await
    }
    pub async fn evidence_download(
        &self,
        input: &sdk::EvidenceDownloadRequest,
    ) -> Result<
        sdk::EvidenceDownloadResponse,
        trellis_rs::generated::CallError<sdk::rpc::EvidenceDownloadError>,
    > {
        self.inner.rpc().evidence().download(input).await
    }
    pub async fn evidence_list(
        &self,
        input: &sdk::EvidenceListRequest,
    ) -> Result<
        sdk::EvidenceListResponse,
        trellis_rs::generated::CallError<sdk::rpc::EvidenceListError>,
    > {
        self.inner.rpc().evidence().list(input).await
    }
    pub async fn sites_get(
        &self,
        input: &sdk::SitesGetRequest,
    ) -> Result<sdk::SitesGetResponse, trellis_rs::generated::CallError<sdk::rpc::SitesGetError>>
    {
        self.inner.rpc().sites().get(input).await
    }
    pub async fn sites_list(
        &self,
        input: &sdk::SitesListRequest,
    ) -> Result<sdk::SitesListResponse, trellis_rs::generated::CallError<sdk::rpc::SitesListError>>
    {
        self.inner.rpc().sites().list(input).await
    }
    /// Download bytes from a transfer grant returned by this dependency.
    pub async fn download_transfer(
        &self,
        grant: &trellis_rs::generated::DownloadTransferGrant,
    ) -> Result<Vec<u8>, trellis_rs::generated::TrellisClientError> {
        self.transport.download_transfer(grant).await
    }
    /// Stream bytes from a transfer grant into a caller-owned writer.
    pub async fn download_transfer_into<W>(
        &self,
        grant: &trellis_rs::generated::DownloadTransferGrant,
        writer: &mut W,
    ) -> Result<trellis_rs::generated::FileInfo, trellis_rs::generated::TrellisClientError>
    where
        W: tokio::io::AsyncWrite + Unpin + Send + ?Sized,
    {
        self.transport.download_transfer_into(grant, writer).await
    }
    /// Stream bytes into a writer with authenticated cancellation.
    pub async fn download_transfer_into_with_cancel<W>(
        &self,
        grant: &trellis_rs::generated::DownloadTransferGrant,
        writer: &mut W,
        cancellation: &trellis_rs::generated::TransferCancellation,
    ) -> Result<trellis_rs::generated::FileInfo, trellis_rs::generated::TrellisClientError>
    where
        W: tokio::io::AsyncWrite + Unpin + Send + ?Sized,
    {
        self.transport
            .download_transfer_into_with_cancel(grant, writer, cancellation)
            .await
    }
    pub fn evidence_upload(
        &self,
    ) -> trellis_rs::generated::OperationInvoker<
        'a,
        trellis_rs::generated::Caller,
        sdk::operations::EvidenceUploadOperation,
    > {
        self.transport
            .operation::<sdk::operations::EvidenceUploadOperation>()
    }
    pub fn reports_generate(
        &self,
    ) -> trellis_rs::generated::OperationInvoker<
        'a,
        trellis_rs::generated::Caller,
        sdk::operations::ReportsGenerateOperation,
    > {
        self.transport
            .operation::<sdk::operations::ReportsGenerateOperation>()
    }
    pub fn sites_refresh(
        &self,
    ) -> trellis_rs::generated::OperationInvoker<
        'a,
        trellis_rs::generated::Caller,
        sdk::operations::SitesRefreshOperation,
    > {
        self.transport
            .operation::<sdk::operations::SitesRefreshOperation>()
    }
    pub async fn subscribe_audit_recorded(
        &self,
    ) -> Result<
        futures_util::stream::BoxStream<
            'static,
            Result<sdk::AuditRecordedEvent, trellis_rs::generated::TrellisClientError>,
        >,
        trellis_rs::generated::TrellisClientError,
    > {
        self.transport
            .subscribe::<sdk::events::AuditRecordedEventDescriptor>()
            .await
    }
    pub async fn subscribe_evidence_uploaded(
        &self,
    ) -> Result<
        futures_util::stream::BoxStream<
            'static,
            Result<sdk::EvidenceUploadedEvent, trellis_rs::generated::TrellisClientError>,
        >,
        trellis_rs::generated::TrellisClientError,
    > {
        self.transport
            .subscribe::<sdk::events::EvidenceUploadedEventDescriptor>()
            .await
    }
    pub async fn subscribe_reports_published(
        &self,
    ) -> Result<
        futures_util::stream::BoxStream<
            'static,
            Result<sdk::ReportsPublishedEvent, trellis_rs::generated::TrellisClientError>,
        >,
        trellis_rs::generated::TrellisClientError,
    > {
        self.transport
            .subscribe::<sdk::events::ReportsPublishedEventDescriptor>()
            .await
    }
    pub async fn subscribe_sites_refreshed(
        &self,
    ) -> Result<
        futures_util::stream::BoxStream<
            'static,
            Result<sdk::SitesRefreshedEvent, trellis_rs::generated::TrellisClientError>,
        >,
        trellis_rs::generated::TrellisClientError,
    > {
        self.transport
            .subscribe::<sdk::events::SitesRefreshedEventDescriptor>()
            .await
    }
}
