// Generated by Trellis. Do not edit.
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_RUNTIME, PARTICIPANT_STATE_METADATA, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/test-client/mod.js";
import * as Api1 from "../../apis/test-runtime/mod.js";
import * as Api2 from "../../apis/state/mod.js";
declare const __ownedActions: readonly [];
declare const __usedActions: readonly [typeof Api1.ACTIONS["Changed"]["subscribe"], typeof Api1.ACTIONS["Echo"], typeof Api1.ACTIONS["Upload"], typeof Api1.ACTIONS["Watch"], typeof Api1.ACTIONS["Work"], typeof Api2.ACTIONS["State.Delete"], typeof Api2.ACTIONS["State.Get"], typeof Api2.ACTIONS["State.List"], typeof Api2.ACTIONS["State.Put"]];
declare const __allActions: readonly [typeof Api1.ACTIONS["Changed"]["subscribe"], typeof Api1.ACTIONS["Echo"], typeof Api1.ACTIONS["Upload"], typeof Api1.ACTIONS["Watch"], typeof Api1.ACTIONS["Work"], typeof Api2.ACTIONS["State.Delete"], typeof Api2.ACTIONS["State.Get"], typeof Api2.ACTIONS["State.List"], typeof Api2.ACTIONS["State.Put"]];
declare const __participant: {
	readonly id: "test.caller";
	readonly digest: "S9GjbkG-Uz5wdieuErmNNTD68OpnEs6ONWMkhgKKl_M";
	readonly artifact: {
		readonly description: "Caller-owned state.";
		readonly displayName: "Runtime caller";
		readonly format: "trellis.participant.v1";
		readonly id: "test.caller";
		readonly implements: {
			readonly self: {
				readonly api: "test.client@v1";
				readonly apiDigest: "o8El02dTOgwoMQysX9wgZj3Tp4RHGljAroEj0Q1fGPw";
			};
		};
		readonly kind: "app";
		readonly schemas: {
			readonly Saved: {
				readonly properties: {
					readonly value: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["value"];
				readonly type: "object";
			};
		};
		readonly state: {
			readonly saved: {
				readonly kind: "value";
				readonly schema: {
					readonly schema: "Saved";
				};
				readonly stateVersion: "saved.v1";
			};
		};
		readonly uses: {
			readonly required: {
				readonly runtime: {
					readonly api: "test.runtime@v1";
					readonly apiDigest: "5CesKi4xQWw2TuBSzOaf_eF6_h9iUxh9SrYRfc6yK78";
					readonly events: {
						readonly subscribe: readonly ["Changed"];
					};
					readonly feeds: {
						readonly subscribe: readonly ["Watch"];
					};
					readonly operations: {
						readonly invoke: readonly ["Upload", "Work"];
						readonly observe: readonly ["Upload", "Work"];
					};
					readonly rpc: {
						readonly call: readonly ["Echo"];
					};
				};
				readonly state: {
					readonly api: "trellis.state@v1";
					readonly apiDigest: "1WHxeF9WLJh3v-mmHiV5mql3a67tmPNpEUFxxUIF9-Y";
					readonly rpc: {
						readonly call: readonly ["State.Delete", "State.Get", "State.List", "State.Put"];
					};
				};
			};
		};
	};
	readonly api: typeof Api0.API;
	readonly apiDigest: typeof Api0.API_DIGEST;
	readonly referencedApis: readonly [typeof Api1.API, typeof Api2.API];
};
declare const __metadata: {
	readonly PARTICIPANT_RUNTIME: {
		readonly ownedApi: ReturnType<typeof runtimeApiFromActions<typeof __ownedActions>>;
		readonly usedApi: ReturnType<typeof runtimeApiFromActions<typeof __usedActions>>;
		readonly api: ReturnType<typeof runtimeApiFromActions<typeof __allActions>>;
		readonly actions: readonly [{
			readonly action: typeof Api1.ACTIONS["Changed"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Echo"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Upload"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Watch"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Work"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.Delete"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.Get"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.Put"];
			readonly optional: false;
		}];
	};
	readonly PARTICIPANT_STATE_METADATA: {
		readonly saved: {
			readonly kind: "value";
			readonly value: {
				value: string;
			};
			readonly schema: {
				readonly properties: {
					readonly value: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["value"];
				readonly type: "object";
			};
			readonly stateVersion: "saved.v1";
			readonly acceptedVersions: {};
		};
	};
};
export declare const participant: typeof __participant & {
	readonly [PARTICIPANT_RUNTIME]: typeof __metadata.PARTICIPANT_RUNTIME;
	readonly [PARTICIPANT_STATE_METADATA]: typeof __metadata.PARTICIPANT_STATE_METADATA;
};
export default participant;
