// Generated by Trellis. Do not edit.
// @ts-self-types="./mod.d.ts"
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_RUNTIME, PARTICIPANT_STATE_METADATA, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/test-client/mod.js";
import * as Api1 from "../../apis/test-runtime/mod.js";
import * as Api2 from "../../apis/state/mod.js";
function typeOnly() {
	return undefined;
}
const __ownedActions = [];
const __usedActions = [
	Api1.ACTIONS["Changed"]["subscribe"],
	Api1.ACTIONS["Echo"],
	Api1.ACTIONS["Upload"],
	Api1.ACTIONS["Watch"],
	Api1.ACTIONS["Work"],
	Api2.ACTIONS["State.Delete"],
	Api2.ACTIONS["State.Get"],
	Api2.ACTIONS["State.List"],
	Api2.ACTIONS["State.Put"]
];
const __allActions = [
	Api1.ACTIONS["Changed"]["subscribe"],
	Api1.ACTIONS["Echo"],
	Api1.ACTIONS["Upload"],
	Api1.ACTIONS["Watch"],
	Api1.ACTIONS["Work"],
	Api2.ACTIONS["State.Delete"],
	Api2.ACTIONS["State.Get"],
	Api2.ACTIONS["State.List"],
	Api2.ACTIONS["State.Put"]
];
const __participant = {
	id: "test.caller",
	digest: "S9GjbkG-Uz5wdieuErmNNTD68OpnEs6ONWMkhgKKl_M",
	artifact: {
		"description": "Caller-owned state.",
		"displayName": "Runtime caller",
		"format": "trellis.participant.v1",
		"id": "test.caller",
		"implements": { "self": {
			"api": "test.client@v1",
			"apiDigest": "o8El02dTOgwoMQysX9wgZj3Tp4RHGljAroEj0Q1fGPw"
		} },
		"kind": "app",
		"schemas": { "Saved": {
			"properties": { "value": { "type": "string" } },
			"required": ["value"],
			"type": "object"
		} },
		"state": { "saved": {
			"kind": "value",
			"schema": { "schema": "Saved" },
			"stateVersion": "saved.v1"
		} },
		"uses": { "required": {
			"runtime": {
				"api": "test.runtime@v1",
				"apiDigest": "5CesKi4xQWw2TuBSzOaf_eF6_h9iUxh9SrYRfc6yK78",
				"events": { "subscribe": ["Changed"] },
				"feeds": { "subscribe": ["Watch"] },
				"operations": {
					"invoke": ["Upload", "Work"],
					"observe": ["Upload", "Work"]
				},
				"rpc": { "call": ["Echo"] }
			},
			"state": {
				"api": "trellis.state@v1",
				"apiDigest": "1WHxeF9WLJh3v-mmHiV5mql3a67tmPNpEUFxxUIF9-Y",
				"rpc": { "call": [
					"State.Delete",
					"State.Get",
					"State.List",
					"State.Put"
				] }
			}
		} }
	},
	api: Api0.API,
	apiDigest: Api0.API_DIGEST,
	referencedApis: [Api1.API, Api2.API]
};
const __metadata = {
	PARTICIPANT_RUNTIME: {
		ownedApi: runtimeApiFromActions(__ownedActions, {}),
		usedApi: runtimeApiFromActions(__usedActions),
		api: runtimeApiFromActions(__allActions, {}),
		actions: [
			{
				action: Api1.ACTIONS["Changed"]["subscribe"],
				optional: false
			},
			{
				action: Api1.ACTIONS["Echo"],
				optional: false
			},
			{
				action: Api1.ACTIONS["Upload"],
				optional: false
			},
			{
				action: Api1.ACTIONS["Watch"],
				optional: false
			},
			{
				action: Api1.ACTIONS["Work"],
				optional: false
			},
			{
				action: Api2.ACTIONS["State.Delete"],
				optional: false
			},
			{
				action: Api2.ACTIONS["State.Get"],
				optional: false
			},
			{
				action: Api2.ACTIONS["State.List"],
				optional: false
			},
			{
				action: Api2.ACTIONS["State.Put"],
				optional: false
			}
		]
	},
	PARTICIPANT_STATE_METADATA: { "saved": {
		kind: "value",
		value: typeOnly(),
		schema: {
			"properties": { "value": { "type": "string" } },
			"required": ["value"],
			"type": "object"
		},
		stateVersion: "saved.v1",
		acceptedVersions: {}
	} }
};
export const participant = {
	...__participant,
	[PARTICIPANT_RUNTIME]: __metadata.PARTICIPANT_RUNTIME,
	[PARTICIPANT_STATE_METADATA]: __metadata.PARTICIPANT_STATE_METADATA
};
export default participant;
