// Generated by Trellis. Do not edit.
// @ts-self-types="./descriptors.d.ts"
// Generated from demo.service@v1
import { eventActions, feedAction, operationAction, rpcAction, schema } from "@qlever-llc/trellis";
import * as Types from "./types.js";
import { ActivityLiveFeedEventSchema, ActivityLiveFeedRequestSchema, AssignmentsListRequestSchema, AssignmentsListResponseSchema, AuditRecordedEventSchema, EvidenceDeleteRequestSchema, EvidenceDeleteResponseSchema, EvidenceDownloadRequestSchema, EvidenceDownloadResponseSchema, EvidenceListRequestSchema, EvidenceListResponseSchema, EvidenceUploadProgressSchema, EvidenceUploadRequestSchema, EvidenceUploadResponseSchema, EvidenceUploadedEventSchema, ReportsGenerateProgressSchema, ReportsGenerateRequestSchema, ReportsGenerateResponseSchema, ReportsListRequestSchema, ReportsListResponseSchema, ReportsPublishedEventSchema, SitesGetRequestSchema, SitesGetResponseSchema, SitesListRequestSchema, SitesListResponseSchema, SitesRefreshProgressSchema, SitesRefreshRequestSchema, SitesRefreshResponseSchema, SitesRefreshedEventSchema } from "./schemas.js";
import { API as ACTION_ARTIFACT, API_DIGEST as ACTION_DIGEST } from "./api.js";
const ACTION_SOURCE = {
	api: ACTION_ARTIFACT,
	apiDigest: ACTION_DIGEST
};
const API_ID = "demo.service@v1";
const __AssignmentsListDescriptor = {
	subject: "rpc.v1.Assignments.List",
	permission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "rpc",
		surfaceName: "Assignments.List",
		action: "call"
	}),
	input: schema(AssignmentsListRequestSchema),
	output: schema(AssignmentsListResponseSchema),
	callerCapabilities: [],
	errors: ["UnexpectedError"],
	declaredErrorTypes: ["UnexpectedError"],
	runtimeErrors: [{
		type: "UnexpectedError",
		fromSerializable: Types.UnexpectedError.fromSerializable
	}]
};
export const AssignmentsList = rpcAction(API_ID, "Assignments.List", __AssignmentsListDescriptor, "AssignmentsList", ACTION_SOURCE);
const __EvidenceDeleteDescriptor = {
	subject: "rpc.v1.Evidence.Delete",
	permission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "rpc",
		surfaceName: "Evidence.Delete",
		action: "call"
	}),
	input: schema(EvidenceDeleteRequestSchema),
	output: schema(EvidenceDeleteResponseSchema),
	callerCapabilities: [],
	errors: ["UnexpectedError"],
	declaredErrorTypes: ["UnexpectedError"],
	runtimeErrors: [{
		type: "UnexpectedError",
		fromSerializable: Types.UnexpectedError.fromSerializable
	}]
};
export const EvidenceDelete = rpcAction(API_ID, "Evidence.Delete", __EvidenceDeleteDescriptor, "EvidenceDelete", ACTION_SOURCE);
const __EvidenceDownloadDescriptor = {
	subject: "rpc.v1.Evidence.Download",
	permission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "rpc",
		surfaceName: "Evidence.Download",
		action: "call"
	}),
	input: schema(EvidenceDownloadRequestSchema),
	output: schema(EvidenceDownloadResponseSchema),
	transfer: { direction: "receive" },
	callerCapabilities: [],
	errors: ["TransferError", "UnexpectedError"],
	declaredErrorTypes: ["TransferError", "UnexpectedError"],
	runtimeErrors: [{
		type: "TransferError",
		fromSerializable: Types.TransferError.fromSerializable
	}, {
		type: "UnexpectedError",
		fromSerializable: Types.UnexpectedError.fromSerializable
	}]
};
export const EvidenceDownload = rpcAction(API_ID, "Evidence.Download", __EvidenceDownloadDescriptor, "EvidenceDownload", ACTION_SOURCE);
const __EvidenceListDescriptor = {
	subject: "rpc.v1.Evidence.List",
	permission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "rpc",
		surfaceName: "Evidence.List",
		action: "call"
	}),
	input: schema(EvidenceListRequestSchema),
	output: schema(EvidenceListResponseSchema),
	callerCapabilities: [],
	errors: ["UnexpectedError"],
	declaredErrorTypes: ["UnexpectedError"],
	runtimeErrors: [{
		type: "UnexpectedError",
		fromSerializable: Types.UnexpectedError.fromSerializable
	}]
};
export const EvidenceList = rpcAction(API_ID, "Evidence.List", __EvidenceListDescriptor, "EvidenceList", ACTION_SOURCE);
const __ReportsListDescriptor = {
	subject: "rpc.v1.Reports.List",
	permission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "rpc",
		surfaceName: "Reports.List",
		action: "call"
	}),
	input: schema(ReportsListRequestSchema),
	output: schema(ReportsListResponseSchema),
	callerCapabilities: [],
	errors: ["UnexpectedError"],
	declaredErrorTypes: ["UnexpectedError"],
	runtimeErrors: [{
		type: "UnexpectedError",
		fromSerializable: Types.UnexpectedError.fromSerializable
	}]
};
export const ReportsList = rpcAction(API_ID, "Reports.List", __ReportsListDescriptor, "ReportsList", ACTION_SOURCE);
const __SitesGetDescriptor = {
	subject: "rpc.v1.Sites.Get",
	permission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "rpc",
		surfaceName: "Sites.Get",
		action: "call"
	}),
	input: schema(SitesGetRequestSchema),
	output: schema(SitesGetResponseSchema),
	callerCapabilities: [],
	errors: ["UnexpectedError"],
	declaredErrorTypes: ["UnexpectedError"],
	runtimeErrors: [{
		type: "UnexpectedError",
		fromSerializable: Types.UnexpectedError.fromSerializable
	}]
};
export const SitesGet = rpcAction(API_ID, "Sites.Get", __SitesGetDescriptor, "SitesGet", ACTION_SOURCE);
const __SitesListDescriptor = {
	subject: "rpc.v1.Sites.List",
	permission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "rpc",
		surfaceName: "Sites.List",
		action: "call"
	}),
	input: schema(SitesListRequestSchema),
	output: schema(SitesListResponseSchema),
	callerCapabilities: [],
	errors: ["UnexpectedError"],
	declaredErrorTypes: ["UnexpectedError"],
	runtimeErrors: [{
		type: "UnexpectedError",
		fromSerializable: Types.UnexpectedError.fromSerializable
	}]
};
export const SitesList = rpcAction(API_ID, "Sites.List", __SitesListDescriptor, "SitesList", ACTION_SOURCE);
const __EvidenceUploadDescriptor = {
	subject: "operations.v1.Evidence.Upload",
	permissions: {
		invoke: Object.freeze({
			apiId: "demo.service@v1",
			apiVersion: "v1",
			surfaceKind: "operation",
			surfaceName: "Evidence.Upload",
			action: "invoke"
		}),
		observe: Object.freeze({
			apiId: "demo.service@v1",
			apiVersion: "v1",
			surfaceKind: "operation",
			surfaceName: "Evidence.Upload",
			action: "observe"
		}),
		cancel: Object.freeze({
			apiId: "demo.service@v1",
			apiVersion: "v1",
			surfaceKind: "operation",
			surfaceName: "Evidence.Upload",
			action: "cancel"
		}),
		control: {}
	},
	input: schema(EvidenceUploadRequestSchema),
	progress: schema(EvidenceUploadProgressSchema),
	output: schema(EvidenceUploadResponseSchema),
	transfer: { direction: "send" },
	callerCapabilities: [],
	observeCapabilities: [],
	cancelCapabilities: [],
	controlCapabilities: []
};
Object.freeze(__EvidenceUploadDescriptor.permissions.control);
Object.freeze(__EvidenceUploadDescriptor.permissions);
export const EvidenceUpload = operationAction(API_ID, "Evidence.Upload", __EvidenceUploadDescriptor, "EvidenceUpload", ACTION_SOURCE);
const __ReportsGenerateDescriptor = {
	subject: "operations.v1.Reports.Generate",
	permissions: {
		invoke: Object.freeze({
			apiId: "demo.service@v1",
			apiVersion: "v1",
			surfaceKind: "operation",
			surfaceName: "Reports.Generate",
			action: "invoke"
		}),
		observe: Object.freeze({
			apiId: "demo.service@v1",
			apiVersion: "v1",
			surfaceKind: "operation",
			surfaceName: "Reports.Generate",
			action: "observe"
		}),
		cancel: Object.freeze({
			apiId: "demo.service@v1",
			apiVersion: "v1",
			surfaceKind: "operation",
			surfaceName: "Reports.Generate",
			action: "cancel"
		}),
		control: {}
	},
	input: schema(ReportsGenerateRequestSchema),
	progress: schema(ReportsGenerateProgressSchema),
	output: schema(ReportsGenerateResponseSchema),
	callerCapabilities: [],
	observeCapabilities: [],
	cancelCapabilities: [],
	controlCapabilities: [],
	cancel: true
};
Object.freeze(__ReportsGenerateDescriptor.permissions.control);
Object.freeze(__ReportsGenerateDescriptor.permissions);
export const ReportsGenerate = operationAction(API_ID, "Reports.Generate", __ReportsGenerateDescriptor, "ReportsGenerate", ACTION_SOURCE);
const __SitesRefreshDescriptor = {
	subject: "operations.v1.Sites.Refresh",
	permissions: {
		invoke: Object.freeze({
			apiId: "demo.service@v1",
			apiVersion: "v1",
			surfaceKind: "operation",
			surfaceName: "Sites.Refresh",
			action: "invoke"
		}),
		observe: Object.freeze({
			apiId: "demo.service@v1",
			apiVersion: "v1",
			surfaceKind: "operation",
			surfaceName: "Sites.Refresh",
			action: "observe"
		}),
		cancel: Object.freeze({
			apiId: "demo.service@v1",
			apiVersion: "v1",
			surfaceKind: "operation",
			surfaceName: "Sites.Refresh",
			action: "cancel"
		}),
		control: {}
	},
	input: schema(SitesRefreshRequestSchema),
	progress: schema(SitesRefreshProgressSchema),
	output: schema(SitesRefreshResponseSchema),
	callerCapabilities: [],
	observeCapabilities: [],
	cancelCapabilities: [],
	controlCapabilities: []
};
Object.freeze(__SitesRefreshDescriptor.permissions.control);
Object.freeze(__SitesRefreshDescriptor.permissions);
export const SitesRefresh = operationAction(API_ID, "Sites.Refresh", __SitesRefreshDescriptor, "SitesRefresh", ACTION_SOURCE);
const __AuditRecordedDescriptor = {
	subject: "events.v1.Audit.Recorded",
	publishPermission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Audit.Recorded",
		action: "publish"
	}),
	subscribePermission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Audit.Recorded",
		action: "subscribe"
	}),
	event: schema(AuditRecordedEventSchema),
	publishCapabilities: [],
	subscribeCapabilities: []
};
export const AuditRecorded = eventActions(API_ID, "Audit.Recorded", __AuditRecordedDescriptor, "AuditRecorded", true, ACTION_SOURCE);
const __EvidenceUploadedDescriptor = {
	subject: "events.v1.Evidence.Uploaded",
	publishPermission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Evidence.Uploaded",
		action: "publish"
	}),
	subscribePermission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Evidence.Uploaded",
		action: "subscribe"
	}),
	event: schema(EvidenceUploadedEventSchema),
	publishCapabilities: [],
	subscribeCapabilities: []
};
export const EvidenceUploaded = eventActions(API_ID, "Evidence.Uploaded", __EvidenceUploadedDescriptor, "EvidenceUploaded", true, ACTION_SOURCE);
const __ReportsPublishedDescriptor = {
	subject: "events.v1.Reports.Published",
	publishPermission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Reports.Published",
		action: "publish"
	}),
	subscribePermission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Reports.Published",
		action: "subscribe"
	}),
	event: schema(ReportsPublishedEventSchema),
	publishCapabilities: [],
	subscribeCapabilities: []
};
export const ReportsPublished = eventActions(API_ID, "Reports.Published", __ReportsPublishedDescriptor, "ReportsPublished", true, ACTION_SOURCE);
const __SitesRefreshedDescriptor = {
	subject: "events.v1.Sites.Refreshed",
	publishPermission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Sites.Refreshed",
		action: "publish"
	}),
	subscribePermission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Sites.Refreshed",
		action: "subscribe"
	}),
	event: schema(SitesRefreshedEventSchema),
	publishCapabilities: [],
	subscribeCapabilities: []
};
export const SitesRefreshed = eventActions(API_ID, "Sites.Refreshed", __SitesRefreshedDescriptor, "SitesRefreshed", true, ACTION_SOURCE);
const __AuditFeedDescriptor = {
	subject: "feed.v1.Audit.Feed",
	permission: Object.freeze({
		apiId: "demo.service@v1",
		apiVersion: "v1",
		surfaceKind: "feed",
		surfaceName: "Audit.Feed",
		action: "subscribe"
	}),
	input: schema(ActivityLiveFeedRequestSchema),
	event: schema(ActivityLiveFeedEventSchema),
	subscribeCapabilities: []
};
export const AuditFeed = feedAction(API_ID, "Audit.Feed", __AuditFeedDescriptor, "AuditFeed", ACTION_SOURCE);
export const ACTIONS = {
	"Assignments.List": AssignmentsList,
	"Evidence.Delete": EvidenceDelete,
	"Evidence.Download": EvidenceDownload,
	"Evidence.List": EvidenceList,
	"Reports.List": ReportsList,
	"Sites.Get": SitesGet,
	"Sites.List": SitesList,
	"Evidence.Upload": EvidenceUpload,
	"Reports.Generate": ReportsGenerate,
	"Sites.Refresh": SitesRefresh,
	"Audit.Recorded": AuditRecorded,
	"Evidence.Uploaded": EvidenceUploaded,
	"Reports.Published": ReportsPublished,
	"Sites.Refreshed": SitesRefreshed,
	"Audit.Feed": AuditFeed
};
