// Generated by Trellis. Do not edit.
// Generated from trellis.core@v1
export declare const TrellisSurfaceStatusRequestSchema: {
	readonly properties: {
		readonly action: {
			readonly anyOf: readonly [{
				readonly const: "call";
				readonly type: "string";
			}, {
				readonly const: "publish";
				readonly type: "string";
			}, {
				readonly const: "subscribe";
				readonly type: "string";
			}, {
				readonly const: "observe";
				readonly type: "string";
			}];
		};
		readonly contractId: {
			readonly minLength: 1;
			readonly type: "string";
		};
		readonly kind: {
			readonly anyOf: readonly [{
				readonly const: "rpc";
				readonly type: "string";
			}, {
				readonly const: "operation";
				readonly type: "string";
			}, {
				readonly const: "event";
				readonly type: "string";
			}, {
				readonly const: "feed";
				readonly type: "string";
			}];
		};
		readonly surface: {
			readonly minLength: 1;
			readonly type: "string";
		};
	};
	readonly required: readonly ["contractId", "kind", "surface"];
	readonly type: "object";
};
export declare const TrellisSurfaceStatusResponseSchema: {
	readonly properties: {
		readonly status: {
			readonly anyOf: readonly [{
				readonly properties: {
					readonly liveImplementer: {
						readonly type: "boolean";
					};
					readonly runtime: {
						readonly anyOf: readonly [{
							readonly const: "live";
							readonly type: "string";
						}, {
							readonly const: "no_live_implementer";
							readonly type: "string";
						}, {
							readonly const: "disabled";
							readonly type: "string";
						}];
					};
					readonly state: {
						readonly const: "available";
						readonly type: "string";
					};
				};
				readonly required: readonly ["liveImplementer", "runtime", "state"];
				readonly type: "object";
			}, {
				readonly properties: {
					readonly reason: {
						readonly const: "authority_unavailable";
						readonly type: "string";
					};
					readonly state: {
						readonly const: "unavailable";
						readonly type: "string";
					};
				};
				readonly required: readonly ["reason", "state"];
				readonly type: "object";
			}, {
				readonly properties: {
					readonly missingCapabilities: {
						readonly items: {
							readonly type: "string";
						};
						readonly type: "array";
					};
					readonly state: {
						readonly const: "unauthorized";
						readonly type: "string";
					};
				};
				readonly required: readonly ["missingCapabilities", "state"];
				readonly type: "object";
			}, {
				readonly properties: {
					readonly contractId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly state: {
						readonly const: "unknown_contract";
						readonly type: "string";
					};
				};
				readonly required: readonly ["contractId", "state"];
				readonly type: "object";
			}, {
				readonly properties: {
					readonly contractId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly kind: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly state: {
						readonly const: "unknown_surface";
						readonly type: "string";
					};
					readonly surface: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["contractId", "kind", "state", "surface"];
				readonly type: "object";
			}];
		};
	};
	readonly required: readonly ["status"];
	readonly type: "object";
};
