// Generated by Trellis. Do not edit.
// @ts-self-types="./mod.d.ts"
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_RUNTIME, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/test-admin/mod.js";
import * as Api1 from "../../apis/auth/mod.js";
import * as Api2 from "../../apis/eventlog/mod.js";
import * as Api3 from "../../apis/health/mod.js";
import * as Api4 from "../../apis/jobs/mod.js";
import * as Api5 from "../../apis/state/mod.js";
function typeOnly() {
	return undefined;
}
const __ownedActions = [];
const __usedActions = [
	Api1.ACTIONS["Auth.CapabilityGroups.Put"],
	Api1.ACTIONS["Auth.Connections.List"],
	Api1.ACTIONS["Auth.DeploymentAuthority.AcceptMigration"],
	Api1.ACTIONS["Auth.DeploymentAuthority.AcceptUpdate"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Get"],
	Api1.ACTIONS["Auth.DeploymentAuthority.List"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Plan"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Plans.List"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Reconcile"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Reject"],
	Api1.ACTIONS["Auth.Deployments.Create"],
	Api1.ACTIONS["Auth.Devices.Provision"],
	Api1.ACTIONS["Auth.IdentityAuthority.List"],
	Api1.ACTIONS["Auth.IdentityAuthority.Revoke"],
	Api1.ACTIONS["Auth.Portals.Get"],
	Api1.ACTIONS["Auth.Portals.GrantOverrides.Put"],
	Api1.ACTIONS["Auth.Portals.GrantOverrides.Remove"],
	Api1.ACTIONS["Auth.Portals.List"],
	Api1.ACTIONS["Auth.Portals.LoginSettings.Update"],
	Api1.ACTIONS["Auth.Portals.Put"],
	Api1.ACTIONS["Auth.Portals.Routes.Put"],
	Api1.ACTIONS["Auth.ServiceInstances.Provision"],
	Api1.ACTIONS["Auth.Sessions.Revoke"],
	Api1.ACTIONS["Auth.UserIdentities.List"],
	Api2.ACTIONS["EventLog.Query"],
	Api3.ACTIONS["Health.Query"],
	Api4.ACTIONS["Jobs.Query"],
	Api5.ACTIONS["State.Admin.Delete"],
	Api5.ACTIONS["State.Admin.Get"],
	Api5.ACTIONS["State.Admin.List"]
];
const __allActions = [
	Api1.ACTIONS["Auth.CapabilityGroups.Put"],
	Api1.ACTIONS["Auth.Connections.List"],
	Api1.ACTIONS["Auth.DeploymentAuthority.AcceptMigration"],
	Api1.ACTIONS["Auth.DeploymentAuthority.AcceptUpdate"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Get"],
	Api1.ACTIONS["Auth.DeploymentAuthority.List"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Plan"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Plans.List"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Reconcile"],
	Api1.ACTIONS["Auth.DeploymentAuthority.Reject"],
	Api1.ACTIONS["Auth.Deployments.Create"],
	Api1.ACTIONS["Auth.Devices.Provision"],
	Api1.ACTIONS["Auth.IdentityAuthority.List"],
	Api1.ACTIONS["Auth.IdentityAuthority.Revoke"],
	Api1.ACTIONS["Auth.Portals.Get"],
	Api1.ACTIONS["Auth.Portals.GrantOverrides.Put"],
	Api1.ACTIONS["Auth.Portals.GrantOverrides.Remove"],
	Api1.ACTIONS["Auth.Portals.List"],
	Api1.ACTIONS["Auth.Portals.LoginSettings.Update"],
	Api1.ACTIONS["Auth.Portals.Put"],
	Api1.ACTIONS["Auth.Portals.Routes.Put"],
	Api1.ACTIONS["Auth.ServiceInstances.Provision"],
	Api1.ACTIONS["Auth.Sessions.Revoke"],
	Api1.ACTIONS["Auth.UserIdentities.List"],
	Api2.ACTIONS["EventLog.Query"],
	Api3.ACTIONS["Health.Query"],
	Api4.ACTIONS["Jobs.Query"],
	Api5.ACTIONS["State.Admin.Delete"],
	Api5.ACTIONS["State.Admin.Get"],
	Api5.ACTIONS["State.Admin.List"]
];
const __participant = {
	id: "test.admin",
	digest: "EDeJwjTBOk_eRAmw2Rfe3FMrJI49TyIck0RypNksiuM",
	artifact: {
		"description": "Admin participant used by live Trellis integration tests.",
		"displayName": "Trellis Test Admin",
		"format": "trellis.participant.v1",
		"id": "test.admin",
		"implements": { "self": {
			"api": "test.admin@v1",
			"apiDigest": "5P5LEUZUAXsjyxXET1FRblEv0_v-mXtMczmF2zDDOaU"
		} },
		"kind": "app",
		"uses": { "required": {
			"auth": {
				"api": "trellis.auth@v1",
				"apiDigest": "6k2TZ2r6d0H2y9qB-6y2PsCvJ9kq5KFlGvVOqM0nAEw",
				"rpc": { "call": [
					"Auth.CapabilityGroups.Put",
					"Auth.Connections.List",
					"Auth.DeploymentAuthority.AcceptMigration",
					"Auth.DeploymentAuthority.AcceptUpdate",
					"Auth.DeploymentAuthority.Get",
					"Auth.DeploymentAuthority.List",
					"Auth.DeploymentAuthority.Plan",
					"Auth.DeploymentAuthority.Plans.List",
					"Auth.DeploymentAuthority.Reconcile",
					"Auth.DeploymentAuthority.Reject",
					"Auth.Deployments.Create",
					"Auth.Devices.Provision",
					"Auth.IdentityAuthority.List",
					"Auth.IdentityAuthority.Revoke",
					"Auth.Portals.Get",
					"Auth.Portals.GrantOverrides.Put",
					"Auth.Portals.GrantOverrides.Remove",
					"Auth.Portals.List",
					"Auth.Portals.LoginSettings.Update",
					"Auth.Portals.Put",
					"Auth.Portals.Routes.Put",
					"Auth.ServiceInstances.Provision",
					"Auth.Sessions.Revoke",
					"Auth.UserIdentities.List"
				] }
			},
			"eventlog": {
				"api": "trellis.eventlog@v1",
				"apiDigest": "0dHI0vCQ_7EhGPQY10aK_hc5cEnnwdPIZrSIjwo7Nwg",
				"rpc": { "call": ["EventLog.Query"] }
			},
			"health": {
				"api": "trellis.health@v1",
				"apiDigest": "8GFaxY8gvKvagqRIF43iaRpUN_40ukCylk_nwmFaZkg",
				"rpc": { "call": ["Health.Query"] }
			},
			"jobs": {
				"api": "trellis.jobs@v1",
				"apiDigest": "PE0Zr_66Vaypj1-XksXfaDOViTirdGw6DuoaKpWtFXs",
				"rpc": { "call": ["Jobs.Query"] }
			},
			"state": {
				"api": "trellis.state@v1",
				"apiDigest": "1WHxeF9WLJh3v-mmHiV5mql3a67tmPNpEUFxxUIF9-Y",
				"rpc": { "call": [
					"State.Admin.Delete",
					"State.Admin.Get",
					"State.Admin.List"
				] }
			}
		} }
	},
	api: Api0.API,
	apiDigest: Api0.API_DIGEST,
	referencedApis: [
		Api1.API,
		Api2.API,
		Api3.API,
		Api4.API,
		Api5.API
	]
};
const __metadata = { PARTICIPANT_RUNTIME: {
	ownedApi: runtimeApiFromActions(__ownedActions, {}),
	usedApi: runtimeApiFromActions(__usedActions),
	api: runtimeApiFromActions(__allActions, {}),
	actions: [
		{
			action: Api1.ACTIONS["Auth.CapabilityGroups.Put"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Connections.List"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.DeploymentAuthority.AcceptMigration"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.DeploymentAuthority.AcceptUpdate"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.DeploymentAuthority.Get"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.DeploymentAuthority.List"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.DeploymentAuthority.Plan"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.DeploymentAuthority.Plans.List"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.DeploymentAuthority.Reconcile"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.DeploymentAuthority.Reject"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Deployments.Create"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Devices.Provision"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.IdentityAuthority.List"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.IdentityAuthority.Revoke"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Portals.Get"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Portals.GrantOverrides.Put"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Portals.GrantOverrides.Remove"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Portals.List"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Portals.LoginSettings.Update"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Portals.Put"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Portals.Routes.Put"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.ServiceInstances.Provision"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.Sessions.Revoke"],
			optional: false
		},
		{
			action: Api1.ACTIONS["Auth.UserIdentities.List"],
			optional: false
		},
		{
			action: Api2.ACTIONS["EventLog.Query"],
			optional: false
		},
		{
			action: Api3.ACTIONS["Health.Query"],
			optional: false
		},
		{
			action: Api4.ACTIONS["Jobs.Query"],
			optional: false
		},
		{
			action: Api5.ACTIONS["State.Admin.Delete"],
			optional: false
		},
		{
			action: Api5.ACTIONS["State.Admin.Get"],
			optional: false
		},
		{
			action: Api5.ACTIONS["State.Admin.List"],
			optional: false
		}
	]
} };
export const participant = {
	...__participant,
	[PARTICIPANT_RUNTIME]: __metadata.PARTICIPANT_RUNTIME
};
export default participant;
