// Generated by Trellis. Do not edit.
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_EVENT_CONSUMERS_METADATA, PARTICIPANT_JOBS_METADATA, PARTICIPANT_KV_METADATA, PARTICIPANT_RUNTIME, PARTICIPANT_STORE_METADATA, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/demo-service/mod.js";
declare const __ownedActions: readonly [typeof Api0.ACTIONS["Assignments.List"], typeof Api0.ACTIONS["Audit.Feed"], typeof Api0.ACTIONS["Audit.Recorded"]["publish"], typeof Api0.ACTIONS["Audit.Recorded"]["subscribe"], typeof Api0.ACTIONS["Evidence.Delete"], typeof Api0.ACTIONS["Evidence.Download"], typeof Api0.ACTIONS["Evidence.List"], typeof Api0.ACTIONS["Evidence.Upload"], typeof Api0.ACTIONS["Evidence.Uploaded"]["publish"], typeof Api0.ACTIONS["Evidence.Uploaded"]["subscribe"], typeof Api0.ACTIONS["Reports.Generate"], typeof Api0.ACTIONS["Reports.List"], typeof Api0.ACTIONS["Reports.Published"]["publish"], typeof Api0.ACTIONS["Reports.Published"]["subscribe"], typeof Api0.ACTIONS["Sites.Get"], typeof Api0.ACTIONS["Sites.List"], typeof Api0.ACTIONS["Sites.Refresh"], typeof Api0.ACTIONS["Sites.Refreshed"]["publish"], typeof Api0.ACTIONS["Sites.Refreshed"]["subscribe"]];
declare const __usedActions: readonly [];
declare const __allActions: readonly [typeof Api0.ACTIONS["Assignments.List"], typeof Api0.ACTIONS["Audit.Feed"], typeof Api0.ACTIONS["Audit.Recorded"]["publish"], typeof Api0.ACTIONS["Audit.Recorded"]["subscribe"], typeof Api0.ACTIONS["Evidence.Delete"], typeof Api0.ACTIONS["Evidence.Download"], typeof Api0.ACTIONS["Evidence.List"], typeof Api0.ACTIONS["Evidence.Upload"], typeof Api0.ACTIONS["Evidence.Uploaded"]["publish"], typeof Api0.ACTIONS["Evidence.Uploaded"]["subscribe"], typeof Api0.ACTIONS["Reports.Generate"], typeof Api0.ACTIONS["Reports.List"], typeof Api0.ACTIONS["Reports.Published"]["publish"], typeof Api0.ACTIONS["Reports.Published"]["subscribe"], typeof Api0.ACTIONS["Sites.Get"], typeof Api0.ACTIONS["Sites.List"], typeof Api0.ACTIONS["Sites.Refresh"], typeof Api0.ACTIONS["Sites.Refreshed"]["publish"], typeof Api0.ACTIONS["Sites.Refreshed"]["subscribe"]];
declare const __participant: {
	readonly id: "demo.service@v1";
	readonly digest: "Fi-mty1sqyQ9fu00AxUkgha3kWJslQTJWu73SVVoa28";
	readonly artifact: {
		readonly description: "Consolidated Field Ops demo service for Trellis concepts.";
		readonly displayName: "Field Ops Demo Service";
		readonly docs: {
			readonly markdown: "Provides assignments, site summaries, evidence transfer, report generation, and audit activity for the Field Ops demo.";
			readonly summary: "Field operations demo APIs.";
		};
		readonly eventConsumers: {
			readonly events: {
				readonly events: {
					readonly self: readonly ["Sites.Refreshed"];
				};
			};
		};
		readonly format: "trellis.participant.v1";
		readonly id: "demo.service@v1";
		readonly implements: {
			readonly self: {
				readonly api: "demo.service@v1";
				readonly apiDigest: "qu_P04zYsryJycTKpriGBJIOAZ9N0xDwYZj8p9BR8eg";
				readonly operationTransfers: {
					readonly "Evidence.Upload": {
						readonly contentType: "/contentType";
						readonly expiresInMs: 60000;
						readonly key: "/key";
						readonly metadata: "/metadata";
						readonly store: "uploads";
					};
				};
			};
		};
		readonly jobQueues: {
			readonly refreshSiteSummary: {
				readonly docs: {
					readonly markdown: "Background work item that recomputes the latest summary for one site.";
					readonly summary: "Refresh a site summary.";
				};
				readonly payload: {
					readonly schema: "SiteRefreshJobPayload";
				};
				readonly result: {
					readonly schema: "SiteRefreshJobResult";
				};
			};
		};
		readonly kind: "service";
		readonly resources: {
			readonly kv: {
				readonly siteSummaries: {
					readonly docs: {
						readonly markdown: "Stores the current site summary records served by the demo APIs.";
						readonly summary: "Cached site summaries.";
					};
					readonly purpose: "Latest site summaries for the Field Ops demo.";
					readonly schema: {
						readonly schema: "SiteSummary";
					};
				};
			};
			readonly store: {
				readonly uploads: {
					readonly docs: {
						readonly markdown: "Persists uploaded evidence files before they are listed or downloaded.";
						readonly summary: "Evidence upload objects.";
					};
					readonly maxObjectBytes: 67108864;
					readonly maxTotalBytes: 268435456;
					readonly purpose: "Persistent evidence locker files for the Field Ops demo.";
				};
			};
		};
		readonly schemas: {
			readonly ActivityLiveFeedEvent: {
				readonly anyOf: readonly [{
					readonly properties: {
						readonly event: {
							readonly properties: {
								readonly activityId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly kind: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly message: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly occurredAt: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly relatedInspectionId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly relatedSiteId: {
									readonly minLength: 1;
									readonly type: "string";
								};
							};
							readonly required: readonly ["activityId", "kind", "message", "occurredAt"];
							readonly type: "object";
						};
						readonly name: {
							readonly const: "Audit.Recorded";
							readonly type: "string";
						};
					};
					readonly required: readonly ["name", "event"];
					readonly type: "object";
				}, {
					readonly properties: {
						readonly event: {
							readonly properties: {
								readonly inspectionId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly publishedAt: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly reportId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly siteId: {
									readonly minLength: 1;
									readonly type: "string";
								};
							};
							readonly required: readonly ["reportId", "inspectionId", "publishedAt"];
							readonly type: "object";
						};
						readonly name: {
							readonly const: "Reports.Published";
							readonly type: "string";
						};
					};
					readonly required: readonly ["name", "event"];
					readonly type: "object";
				}, {
					readonly properties: {
						readonly event: {
							readonly properties: {
								readonly contentType: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly evidenceId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly evidenceType: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly fileName: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly key: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly size: {
									readonly minimum: 0;
									readonly type: "integer";
								};
								readonly uploadedAt: {
									readonly minLength: 1;
									readonly type: "string";
								};
							};
							readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
							readonly type: "object";
						};
						readonly name: {
							readonly const: "Evidence.Uploaded";
							readonly type: "string";
						};
					};
					readonly required: readonly ["name", "event"];
					readonly type: "object";
				}, {
					readonly properties: {
						readonly event: {
							readonly properties: {
								readonly refreshId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly refreshedAt: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly site: {
									readonly properties: {
										readonly lastReportAt: {
											readonly minLength: 1;
											readonly type: "string";
										};
										readonly latestStatus: {
											readonly minLength: 1;
											readonly type: "string";
										};
										readonly openInspections: {
											readonly minimum: 0;
											readonly type: "integer";
										};
										readonly overdueInspections: {
											readonly minimum: 0;
											readonly type: "integer";
										};
										readonly siteId: {
											readonly minLength: 1;
											readonly type: "string";
										};
										readonly siteName: {
											readonly minLength: 1;
											readonly type: "string";
										};
									};
									readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
									readonly type: "object";
								};
							};
							readonly required: readonly ["refreshId", "site", "refreshedAt"];
							readonly type: "object";
						};
						readonly name: {
							readonly const: "Sites.Refreshed";
							readonly type: "string";
						};
					};
					readonly required: readonly ["name", "event"];
					readonly type: "object";
				}];
			};
			readonly ActivityLiveFeedRequest: {
				readonly properties: {};
				readonly type: "object";
			};
			readonly AssignmentsListRequest: {
				readonly properties: {
					readonly limit: {
						readonly maximum: 500;
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly offset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
				};
				readonly required: readonly ["limit"];
				readonly type: "object";
			};
			readonly AssignmentsListResponse: {
				readonly properties: {
					readonly count: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly entries: {
						readonly items: {
							readonly properties: {
								readonly assetName: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly checklistName: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly inspectionId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly priority: {
									readonly anyOf: readonly [{
										readonly const: "high";
										readonly type: "string";
									}, {
										readonly const: "medium";
										readonly type: "string";
									}, {
										readonly const: "low";
										readonly type: "string";
									}];
								};
								readonly scheduledFor: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly siteId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly siteName: {
									readonly minLength: 1;
									readonly type: "string";
								};
							};
							readonly required: readonly ["inspectionId", "siteId", "siteName", "assetName", "checklistName", "priority", "scheduledFor"];
							readonly type: "object";
						};
						readonly type: "array";
					};
					readonly limit: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly nextOffset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly offset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
				};
				readonly required: readonly ["entries", "count", "offset", "limit"];
				readonly type: "object";
			};
			readonly AuditFeedItem: {
				readonly properties: {
					readonly event: {
						readonly properties: {
							readonly activityId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly kind: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly message: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly occurredAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly relatedInspectionId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly relatedSiteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["activityId", "kind", "message", "occurredAt"];
						readonly type: "object";
					};
					readonly name: {
						readonly const: "Audit.Recorded";
						readonly type: "string";
					};
				};
				readonly required: readonly ["name", "event"];
				readonly type: "object";
			};
			readonly AuditRecordedEvent: {
				readonly properties: {
					readonly activityId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly kind: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly message: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly occurredAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly relatedInspectionId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly relatedSiteId: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["activityId", "kind", "message", "occurredAt"];
				readonly type: "object";
			};
			readonly EvidenceDeleteRequest: {
				readonly properties: {
					readonly key: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["key"];
				readonly type: "object";
			};
			readonly EvidenceDeleteResponse: {
				readonly properties: {
					readonly deleted: {
						readonly type: "boolean";
					};
					readonly key: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["key", "deleted"];
				readonly type: "object";
			};
			readonly EvidenceDownloadGrant: {
				readonly properties: {
					readonly chunkBytes: {
						readonly minimum: 1;
						readonly type: "integer";
					};
					readonly direction: {
						readonly const: "receive";
						readonly type: "string";
					};
					readonly expiresAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly info: {
						readonly properties: {
							readonly contentType: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly digest: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly key: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly metadata: {
								readonly additionalProperties: {
									readonly type: "string";
								};
								readonly type: "object";
							};
							readonly size: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly updatedAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["key", "size", "updatedAt", "digest", "metadata"];
						readonly type: "object";
					};
					readonly service: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly sessionKey: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly subject: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly transferId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly type: {
						readonly const: "TransferGrant";
						readonly type: "string";
					};
				};
				readonly required: readonly ["type", "direction", "service", "sessionKey", "transferId", "subject", "expiresAt", "chunkBytes", "info"];
				readonly type: "object";
			};
			readonly EvidenceDownloadInfo: {
				readonly properties: {
					readonly contentType: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly digest: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly key: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly metadata: {
						readonly additionalProperties: {
							readonly type: "string";
						};
						readonly type: "object";
					};
					readonly size: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly updatedAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["key", "size", "updatedAt", "digest", "metadata"];
				readonly type: "object";
			};
			readonly EvidenceDownloadRequest: {
				readonly properties: {
					readonly key: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["key"];
				readonly type: "object";
			};
			readonly EvidenceDownloadResponse: {
				readonly properties: {
					readonly transfer: {
						readonly properties: {
							readonly chunkBytes: {
								readonly minimum: 1;
								readonly type: "integer";
							};
							readonly direction: {
								readonly const: "receive";
								readonly type: "string";
							};
							readonly expiresAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly info: {
								readonly properties: {
									readonly contentType: {
										readonly minLength: 1;
										readonly type: "string";
									};
									readonly digest: {
										readonly minLength: 1;
										readonly type: "string";
									};
									readonly key: {
										readonly minLength: 1;
										readonly type: "string";
									};
									readonly metadata: {
										readonly additionalProperties: {
											readonly type: "string";
										};
										readonly type: "object";
									};
									readonly size: {
										readonly minimum: 0;
										readonly type: "integer";
									};
									readonly updatedAt: {
										readonly minLength: 1;
										readonly type: "string";
									};
								};
								readonly required: readonly ["key", "size", "updatedAt", "digest", "metadata"];
								readonly type: "object";
							};
							readonly service: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly sessionKey: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly subject: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly transferId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly type: {
								readonly const: "TransferGrant";
								readonly type: "string";
							};
						};
						readonly required: readonly ["type", "direction", "service", "sessionKey", "transferId", "subject", "expiresAt", "chunkBytes", "info"];
						readonly type: "object";
					};
				};
				readonly required: readonly ["transfer"];
				readonly type: "object";
			};
			readonly EvidenceFeedItem: {
				readonly properties: {
					readonly event: {
						readonly properties: {
							readonly contentType: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly evidenceId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly evidenceType: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly fileName: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly key: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly size: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly uploadedAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
						readonly type: "object";
					};
					readonly name: {
						readonly const: "Evidence.Uploaded";
						readonly type: "string";
					};
				};
				readonly required: readonly ["name", "event"];
				readonly type: "object";
			};
			readonly EvidenceFileInfo: {
				readonly properties: {
					readonly contentType: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly digest: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly key: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly metadata: {
						readonly additionalProperties: {
							readonly type: "string";
						};
						readonly type: "object";
					};
					readonly size: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly updatedAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["key", "size", "updatedAt", "metadata"];
				readonly type: "object";
			};
			readonly EvidenceListRequest: {
				readonly properties: {
					readonly limit: {
						readonly maximum: 500;
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly offset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly prefix: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["limit"];
				readonly type: "object";
			};
			readonly EvidenceListResponse: {
				readonly properties: {
					readonly count: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly entries: {
						readonly items: {
							readonly properties: {
								readonly contentType: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly evidenceId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly evidenceType: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly fileName: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly key: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly size: {
									readonly minimum: 0;
									readonly type: "integer";
								};
								readonly uploadedAt: {
									readonly minLength: 1;
									readonly type: "string";
								};
							};
							readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
							readonly type: "object";
						};
						readonly type: "array";
					};
					readonly limit: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly nextOffset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly offset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
				};
				readonly required: readonly ["entries", "count", "offset", "limit"];
				readonly type: "object";
			};
			readonly EvidenceRecord: {
				readonly properties: {
					readonly contentType: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly evidenceId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly evidenceType: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly fileName: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly key: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly size: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly uploadedAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
				readonly type: "object";
			};
			readonly EvidenceUploadProgress: {
				readonly properties: {
					readonly message: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly stage: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["stage", "message"];
				readonly type: "object";
			};
			readonly EvidenceUploadRequest: {
				readonly properties: {
					readonly contentType: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly evidenceType: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly key: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly metadata: {
						readonly additionalProperties: {
							readonly type: "string";
						};
						readonly type: "object";
					};
				};
				readonly required: readonly ["key", "evidenceType"];
				readonly type: "object";
			};
			readonly EvidenceUploadResponse: {
				readonly properties: {
					readonly contentType: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly disposition: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly evidenceId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly fileName: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly key: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly size: {
						readonly minimum: 0;
						readonly type: "integer";
					};
				};
				readonly required: readonly ["evidenceId", "key", "size", "disposition"];
				readonly type: "object";
			};
			readonly EvidenceUploadedEvent: {
				readonly properties: {
					readonly contentType: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly evidenceId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly evidenceType: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly fileName: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly key: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly size: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly uploadedAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["evidenceId", "key", "size", "evidenceType", "uploadedAt"];
				readonly type: "object";
			};
			readonly InspectionAssignment: {
				readonly properties: {
					readonly assetName: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly checklistName: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly inspectionId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly priority: {
						readonly anyOf: readonly [{
							readonly const: "high";
							readonly type: "string";
						}, {
							readonly const: "medium";
							readonly type: "string";
						}, {
							readonly const: "low";
							readonly type: "string";
						}];
					};
					readonly scheduledFor: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly siteId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly siteName: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["inspectionId", "siteId", "siteName", "assetName", "checklistName", "priority", "scheduledFor"];
				readonly type: "object";
			};
			readonly NonEmptyString: {
				readonly minLength: 1;
				readonly type: "string";
			};
			readonly NonWhitespaceString: {
				readonly minLength: 1;
				readonly pattern: "\\S";
				readonly type: "string";
			};
			readonly Priority: {
				readonly anyOf: readonly [{
					readonly const: "high";
					readonly type: "string";
				}, {
					readonly const: "medium";
					readonly type: "string";
				}, {
					readonly const: "low";
					readonly type: "string";
				}];
			};
			readonly ReportRecord: {
				readonly properties: {
					readonly assetName: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly evidenceStatus: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly inspectionId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly publishedAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly readiness: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly reportComment: {
						readonly minLength: 1;
						readonly pattern: "\\S";
						readonly type: "string";
					};
					readonly reportId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly siteId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly siteName: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly status: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly summary: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["reportId", "inspectionId", "siteName", "assetName", "status", "publishedAt", "reportComment", "summary", "readiness", "evidenceStatus"];
				readonly type: "object";
			};
			readonly ReportsFeedItem: {
				readonly properties: {
					readonly event: {
						readonly properties: {
							readonly inspectionId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly publishedAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly reportId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["reportId", "inspectionId", "publishedAt"];
						readonly type: "object";
					};
					readonly name: {
						readonly const: "Reports.Published";
						readonly type: "string";
					};
				};
				readonly required: readonly ["name", "event"];
				readonly type: "object";
			};
			readonly ReportsGenerateProgress: {
				readonly properties: {
					readonly message: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly stage: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["stage", "message"];
				readonly type: "object";
			};
			readonly ReportsGenerateRequest: {
				readonly properties: {
					readonly inspectionId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly reportComment: {
						readonly minLength: 1;
						readonly pattern: "\\S";
						readonly type: "string";
					};
				};
				readonly required: readonly ["inspectionId", "reportComment"];
				readonly type: "object";
			};
			readonly ReportsGenerateResponse: {
				readonly properties: {
					readonly inspectionId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly reportId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly status: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["reportId", "inspectionId", "status"];
				readonly type: "object";
			};
			readonly ReportsListRequest: {
				readonly properties: {
					readonly limit: {
						readonly maximum: 500;
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly offset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
				};
				readonly required: readonly ["limit"];
				readonly type: "object";
			};
			readonly ReportsListResponse: {
				readonly properties: {
					readonly count: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly entries: {
						readonly items: {
							readonly properties: {
								readonly assetName: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly evidenceStatus: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly inspectionId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly publishedAt: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly readiness: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly reportComment: {
									readonly minLength: 1;
									readonly pattern: "\\S";
									readonly type: "string";
								};
								readonly reportId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly siteId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly siteName: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly status: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly summary: {
									readonly minLength: 1;
									readonly type: "string";
								};
							};
							readonly required: readonly ["reportId", "inspectionId", "siteName", "assetName", "status", "publishedAt", "reportComment", "summary", "readiness", "evidenceStatus"];
							readonly type: "object";
						};
						readonly type: "array";
					};
					readonly limit: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly nextOffset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly offset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
				};
				readonly required: readonly ["entries", "count", "offset", "limit"];
				readonly type: "object";
			};
			readonly ReportsPublishedEvent: {
				readonly properties: {
					readonly inspectionId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly publishedAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly reportId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly siteId: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["reportId", "inspectionId", "publishedAt"];
				readonly type: "object";
			};
			readonly SiteRefreshJobPayload: {
				readonly properties: {
					readonly siteId: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["siteId"];
				readonly type: "object";
			};
			readonly SiteRefreshJobResult: {
				readonly properties: {
					readonly refreshId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly site: {
						readonly properties: {
							readonly lastReportAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly latestStatus: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly openInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly overdueInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly siteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteName: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
						readonly type: "object";
					};
					readonly status: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["refreshId", "site", "status"];
				readonly type: "object";
			};
			readonly SiteSummary: {
				readonly properties: {
					readonly lastReportAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly latestStatus: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly openInspections: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly overdueInspections: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly siteId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly siteName: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
				readonly type: "object";
			};
			readonly SitesFeedItem: {
				readonly properties: {
					readonly event: {
						readonly properties: {
							readonly refreshId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly refreshedAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly site: {
								readonly properties: {
									readonly lastReportAt: {
										readonly minLength: 1;
										readonly type: "string";
									};
									readonly latestStatus: {
										readonly minLength: 1;
										readonly type: "string";
									};
									readonly openInspections: {
										readonly minimum: 0;
										readonly type: "integer";
									};
									readonly overdueInspections: {
										readonly minimum: 0;
										readonly type: "integer";
									};
									readonly siteId: {
										readonly minLength: 1;
										readonly type: "string";
									};
									readonly siteName: {
										readonly minLength: 1;
										readonly type: "string";
									};
								};
								readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
								readonly type: "object";
							};
						};
						readonly required: readonly ["refreshId", "site", "refreshedAt"];
						readonly type: "object";
					};
					readonly name: {
						readonly const: "Sites.Refreshed";
						readonly type: "string";
					};
				};
				readonly required: readonly ["name", "event"];
				readonly type: "object";
			};
			readonly SitesGetRequest: {
				readonly properties: {
					readonly siteId: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["siteId"];
				readonly type: "object";
			};
			readonly SitesGetResponse: {
				readonly properties: {
					readonly site: {
						readonly properties: {
							readonly lastReportAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly latestStatus: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly openInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly overdueInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly siteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteName: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
						readonly type: "object";
					};
				};
				readonly type: "object";
			};
			readonly SitesListRequest: {
				readonly properties: {
					readonly limit: {
						readonly maximum: 500;
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly offset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
				};
				readonly required: readonly ["limit"];
				readonly type: "object";
			};
			readonly SitesListResponse: {
				readonly properties: {
					readonly count: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly entries: {
						readonly items: {
							readonly properties: {
								readonly lastReportAt: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly latestStatus: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly openInspections: {
									readonly minimum: 0;
									readonly type: "integer";
								};
								readonly overdueInspections: {
									readonly minimum: 0;
									readonly type: "integer";
								};
								readonly siteId: {
									readonly minLength: 1;
									readonly type: "string";
								};
								readonly siteName: {
									readonly minLength: 1;
									readonly type: "string";
								};
							};
							readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
							readonly type: "object";
						};
						readonly type: "array";
					};
					readonly limit: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly nextOffset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly offset: {
						readonly minimum: 0;
						readonly type: "integer";
					};
				};
				readonly required: readonly ["entries", "count", "offset", "limit"];
				readonly type: "object";
			};
			readonly SitesRefreshProgress: {
				readonly properties: {
					readonly message: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly stage: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["stage", "message"];
				readonly type: "object";
			};
			readonly SitesRefreshRequest: {
				readonly properties: {
					readonly siteId: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["siteId"];
				readonly type: "object";
			};
			readonly SitesRefreshResponse: {
				readonly properties: {
					readonly refreshId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly site: {
						readonly properties: {
							readonly lastReportAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly latestStatus: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly openInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly overdueInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly siteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteName: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
						readonly type: "object";
					};
					readonly status: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["refreshId", "site", "status"];
				readonly type: "object";
			};
			readonly SitesRefreshedEvent: {
				readonly properties: {
					readonly refreshId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly refreshedAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly site: {
						readonly properties: {
							readonly lastReportAt: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly latestStatus: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly openInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly overdueInspections: {
								readonly minimum: 0;
								readonly type: "integer";
							};
							readonly siteId: {
								readonly minLength: 1;
								readonly type: "string";
							};
							readonly siteName: {
								readonly minLength: 1;
								readonly type: "string";
							};
						};
						readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
						readonly type: "object";
					};
				};
				readonly required: readonly ["refreshId", "site", "refreshedAt"];
				readonly type: "object";
			};
		};
	};
	readonly api: typeof Api0.API;
	readonly apiDigest: typeof Api0.API_DIGEST;
	readonly referencedApis: readonly [];
	readonly AssignmentsList: typeof Api0.ACTIONS["Assignments.List"];
	readonly AuditFeed: typeof Api0.ACTIONS["Audit.Feed"];
	readonly AuditRecorded: typeof Api0.ACTIONS["Audit.Recorded"];
	readonly EvidenceDelete: typeof Api0.ACTIONS["Evidence.Delete"];
	readonly EvidenceDownload: typeof Api0.ACTIONS["Evidence.Download"];
	readonly EvidenceList: typeof Api0.ACTIONS["Evidence.List"];
	readonly EvidenceUpload: typeof Api0.ACTIONS["Evidence.Upload"];
	readonly EvidenceUploaded: typeof Api0.ACTIONS["Evidence.Uploaded"];
	readonly ReportsGenerate: typeof Api0.ACTIONS["Reports.Generate"];
	readonly ReportsList: typeof Api0.ACTIONS["Reports.List"];
	readonly ReportsPublished: typeof Api0.ACTIONS["Reports.Published"];
	readonly SitesGet: typeof Api0.ACTIONS["Sites.Get"];
	readonly SitesList: typeof Api0.ACTIONS["Sites.List"];
	readonly SitesRefresh: typeof Api0.ACTIONS["Sites.Refresh"];
	readonly SitesRefreshed: typeof Api0.ACTIONS["Sites.Refreshed"];
};
declare const __metadata: {
	readonly PARTICIPANT_RUNTIME: {
		readonly ownedApi: ReturnType<typeof runtimeApiFromActions<typeof __ownedActions>>;
		readonly usedApi: ReturnType<typeof runtimeApiFromActions<typeof __usedActions>>;
		readonly api: ReturnType<typeof runtimeApiFromActions<typeof __allActions>>;
		readonly actions: readonly [{
			readonly action: typeof Api0.ACTIONS["Assignments.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Audit.Feed"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Audit.Recorded"]["publish"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Audit.Recorded"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Evidence.Delete"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Evidence.Download"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Evidence.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Evidence.Upload"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Evidence.Uploaded"]["publish"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Evidence.Uploaded"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Reports.Generate"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Reports.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Reports.Published"]["publish"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Reports.Published"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Sites.Get"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Sites.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Sites.Refresh"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Sites.Refreshed"]["publish"];
			readonly optional: false;
		}, {
			readonly action: typeof Api0.ACTIONS["Sites.Refreshed"]["subscribe"];
			readonly optional: false;
		}];
	};
	readonly PARTICIPANT_JOBS_METADATA: {
		readonly refreshSiteSummary: {
			readonly payload: Api0.SiteRefreshJobPayload;
			readonly result: unknown;
		};
	};
	readonly PARTICIPANT_KV_METADATA: {
		readonly siteSummaries: {
			readonly required: true;
			readonly value: Api0.SiteSummary;
			readonly schema: {
				readonly properties: {
					readonly lastReportAt: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly latestStatus: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly openInspections: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly overdueInspections: {
						readonly minimum: 0;
						readonly type: "integer";
					};
					readonly siteId: {
						readonly minLength: 1;
						readonly type: "string";
					};
					readonly siteName: {
						readonly minLength: 1;
						readonly type: "string";
					};
				};
				readonly required: readonly ["siteId", "siteName", "openInspections", "overdueInspections", "latestStatus", "lastReportAt"];
				readonly type: "object";
			};
		};
	};
	readonly PARTICIPANT_STORE_METADATA: {
		readonly uploads: {
			readonly required: true;
		};
	};
	readonly PARTICIPANT_EVENT_CONSUMERS_METADATA: {
		readonly events: {
			readonly self: readonly ["Sites.Refreshed"];
		};
	};
};
export declare const participant: typeof __participant & {
	readonly [PARTICIPANT_RUNTIME]: typeof __metadata.PARTICIPANT_RUNTIME;
	readonly [PARTICIPANT_JOBS_METADATA]: typeof __metadata.PARTICIPANT_JOBS_METADATA;
	readonly [PARTICIPANT_KV_METADATA]: typeof __metadata.PARTICIPANT_KV_METADATA;
	readonly [PARTICIPANT_STORE_METADATA]: typeof __metadata.PARTICIPANT_STORE_METADATA;
	readonly [PARTICIPANT_EVENT_CONSUMERS_METADATA]: typeof __metadata.PARTICIPANT_EVENT_CONSUMERS_METADATA;
};
export default participant;
