// Generated by Trellis. Do not edit.
// Generated from trellis-app.console@v1
export declare const API_ID: "trellis-app.console@v1";
export declare const API_DIGEST: "FGQ9yeQpdADleg1-h5t_kS8DvpWVM2wGT0FgWXCKGJE";
export declare const API: {
	readonly description: "Drive the Trellis administration client's contract-declared platform access.";
	readonly displayName: "Trellis Console";
	readonly format: "trellis.api.v1";
	readonly id: "trellis-app.console@v1";
	readonly version: "1.0.0";
};
