// Generated by Trellis. Do not edit.
// Generated from demo.device@v1
export declare const API_ID: "demo.device@v1";
export declare const API_DIGEST: "mEmDg58k8Xb_TdI_j8-cQK5KsPvLzxdYD3Hmm0O4yL8";
export declare const API: {
	readonly description: "Activated Field Device TUI for the consolidated demo.";
	readonly displayName: "Field Device Demo";
	readonly docs: {
		readonly markdown: "Declares the Field Device demo's service usage and local state for selected sites and draft inspections.";
		readonly summary: "Activated field device demo.";
	};
	readonly exports: {
		readonly schemas: readonly ["DraftInspectionState", "SelectedSiteState"];
	};
	readonly format: "trellis.api.v1";
	readonly id: "demo.device@v1";
	readonly schemas: {
		readonly DraftInspectionState: {
			readonly properties: {
				readonly checklistName: {
					readonly type: "string";
				};
				readonly inspectionId: {
					readonly type: "string";
				};
				readonly notes: {
					readonly type: "string";
				};
				readonly siteId: {
					readonly type: "string";
				};
				readonly updatedAt: {
					readonly type: "string";
				};
			};
			readonly required: readonly ["inspectionId", "siteId", "checklistName", "notes", "updatedAt"];
			readonly type: "object";
		};
		readonly SelectedSiteState: {
			readonly properties: {
				readonly selectedAt: {
					readonly type: "string";
				};
				readonly siteId: {
					readonly type: "string";
				};
				readonly siteName: {
					readonly type: "string";
				};
			};
			readonly required: readonly ["siteId", "siteName", "selectedAt"];
			readonly type: "object";
		};
	};
	readonly version: "1.0.0";
};
