// Generated by Trellis. Do not edit.
// Generated from acme.orders@v1
export declare const CreateOrderRequestSchema: {
	readonly properties: {
		readonly customerId: {
			readonly type: "string";
		};
	};
	readonly required: readonly ["customerId"];
	readonly type: "object";
};
export declare const CreateOrderResponseSchema: {
	readonly properties: {
		readonly customerId: {
			readonly type: "string";
		};
		readonly orderId: {
			readonly type: "string";
		};
	};
	readonly required: readonly ["orderId", "customerId"];
	readonly type: "object";
};
