// Generated by Trellis. Do not edit.
/// Owned facade for `test.caller`.
/// Reusable native participant vocabulary for this participant.
pub struct OwnedParticipant;
impl OwnedParticipant {
    pub const PARTICIPANT_ID: &'static str = "test.caller";
    pub const PARTICIPANT_DIGEST: &'static str = "S9GjbkG-Uz5wdieuErmNNTD68OpnEs6ONWMkhgKKl_M";
    pub const PARTICIPANT_NEEDS_DIGEST: &'static str =
        "207gLcswwDgSZdp9EEioQJY9RPw_uL990J4Jkwdvals";
    pub const PARTICIPANT_JSON: &'static str = "{\"description\":\"Caller-owned state.\",\"displayName\":\"Runtime caller\",\"format\":\"trellis.participant.v1\",\"id\":\"test.caller\",\"implements\":{\"self\":{\"api\":\"test.client@v1\",\"apiDigest\":\"o8El02dTOgwoMQysX9wgZj3Tp4RHGljAroEj0Q1fGPw\"}},\"kind\":\"app\",\"schemas\":{\"Saved\":{\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"type\":\"object\"}},\"state\":{\"saved\":{\"kind\":\"value\",\"schema\":{\"schema\":\"Saved\"},\"stateVersion\":\"saved.v1\"}},\"uses\":{\"required\":{\"runtime\":{\"api\":\"test.runtime@v1\",\"apiDigest\":\"5CesKi4xQWw2TuBSzOaf_eF6_h9iUxh9SrYRfc6yK78\",\"events\":{\"subscribe\":[\"Changed\"]},\"feeds\":{\"subscribe\":[\"Watch\"]},\"operations\":{\"invoke\":[\"Upload\",\"Work\"],\"observe\":[\"Upload\",\"Work\"]},\"rpc\":{\"call\":[\"Echo\"]}},\"state\":{\"api\":\"trellis.state@v1\",\"apiDigest\":\"1WHxeF9WLJh3v-mmHiV5mql3a67tmPNpEUFxxUIF9-Y\",\"rpc\":{\"call\":[\"State.Delete\",\"State.Get\",\"State.List\",\"State.Put\"]}}}}}";
    pub const API_JSON: &'static str = "{\"description\":\"Caller-owned state.\",\"displayName\":\"Runtime caller\",\"format\":\"trellis.api.v1\",\"id\":\"test.client@v1\",\"schemas\":{\"Saved\":{\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"type\":\"object\"}},\"version\":\"1.0.0\"}";
    pub const API_DIGEST: &'static str = "o8El02dTOgwoMQysX9wgZj3Tp4RHGljAroEj0Q1fGPw";
}
pub struct Client<'a> {
    _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Client<'a> {
    pub fn new(inner: &'a trellis_rs::generated::Caller) -> Self {
        Self { _inner: inner }
    }
}
pub struct Service<'a> {
    _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Service<'a> {
    pub fn new(inner: &'a trellis_rs::generated::Caller) -> Self {
        Self { _inner: inner }
    }
}
