// Generated by Trellis. Do not edit.
// Generated from trellis.eventlog@v1
import type { SerializableErrorData } from "@qlever-llc/trellis";
import { TrellisError } from "@qlever-llc/trellis";
import { NotFoundErrorDataSchema } from "./schemas.js";
export type EventLogConsumersInspectInput = {
	consumerName: string;
	stream?: string;
};
export type EventLogConsumersInspectOutput = {};
export type EventLogConsumersQueryInput = {
	contractId?: string;
	deploymentId?: string;
	limit: number;
	offset?: number;
	ownerContractId?: string;
	status?: Array<("current" | "processing" | "behind" | "saturated" | "inactive" | "failing" | "missing" | "orphaned")>;
	subject?: string;
};
export type EventLogConsumersQueryOutput = {
	consumers: Array<{
		ackPending: number;
		ackWaitMs?: number;
		consumerName: string;
		contractId?: string;
		deploymentId?: string;
		filterSubjects: Array<string>;
		group?: string;
		managedBy?: ("authority" | "platform" | "external");
		maxDeliver?: number;
		oldestPendingAt?: string;
		oldestPendingEventId?: string;
		pending: number;
		redelivered?: number;
		status: ("current" | "processing" | "behind" | "saturated" | "inactive" | "failing" | "missing" | "orphaned");
		stream: string;
		waitingPulls: number;
	}>;
	limit: number;
	offset: number;
	total: number;
};
export type EventLogInspectInput = {
	eventId?: string;
	streamSequence?: number;
};
export type EventLogInspectOutput = {};
export type EventLogMetricsInput = {
	window?: ("15m" | "1h" | "6h" | "24h" | "7d");
};
export type EventLogMetricsOutput = {
	buckets: Array<{
		byResolution: {
			malformed?: number;
			resolved?: number;
			unresolved?: number;
		};
		byVerificationStatus: {
			"auth-unavailable"?: number;
			"invalid-signature"?: number;
			"missing-proof"?: number;
			"missing-session"?: number;
			"outside-session-window"?: number;
			"subject-denied"?: number;
			verified?: number;
		};
		integrityExceptions: number;
		payloadSizeBytes: number;
		start: string;
		total: number;
	}>;
	summary: {
		byResolution: {
			malformed?: number;
			resolved?: number;
			unresolved?: number;
		};
		byVerificationStatus: {
			"auth-unavailable"?: number;
			"invalid-signature"?: number;
			"missing-proof"?: number;
			"missing-session"?: number;
			"outside-session-window"?: number;
			"subject-denied"?: number;
			verified?: number;
		};
		eventTypes: Array<{
			count: number;
			ownerContractId: string;
			ownerEventName: string;
		}>;
		integrityExceptions: number;
		payloadSizeBytes: number;
		total: number;
		uniqueSubjects: number;
	};
};
export type EventLogQueryInput = {
	consumerDeploymentId?: string;
	consumerName?: string;
	excludeEventTypes?: Array<{
		ownerContractId: string;
		ownerEventName: string;
	}>;
	includeEventTypes?: Array<{
		ownerContractId: string;
		ownerEventName: string;
	}>;
	integrityExceptionOnly?: boolean;
	limit: number;
	offset?: number;
	ownerContractId?: string;
	ownerEventName?: string;
	publisherDeploymentId?: string;
	publisherParticipantId?: string;
	resolution?: Array<("resolved" | "unresolved" | "malformed")>;
	search?: string;
	sort?: {};
	subject?: string;
	verificationStatus?: Array<"verified">;
	window?: ("15m" | "1h" | "6h" | "24h" | "7d");
};
export type EventLogQueryOutput = {
	events: Array<{
		eventId: string;
		eventTime: string;
		headerCount: number;
		ownerContractId?: string;
		ownerEventName?: string;
		payloadSizeBytes: number;
		publisherDeploymentId?: string;
		publisherInstanceId?: string;
		publisherKind?: ("service" | "device" | "user");
		publisherParticipantDigest?: string;
		publisherParticipantId?: string;
		resolution: ("resolved" | "unresolved" | "malformed");
		streamSequence: number;
		subject: string;
		traceId?: string;
		verificationStatus: "verified";
	}>;
	limit: number;
	offset: number;
	total: number;
};
export type EventLogWatchInput = {};
export type EventLogWatchEvent = {};
export type NotFoundErrorData = SerializableErrorData & ({
	context?: {};
	id: string;
	message: string;
	type: "NotFoundError";
});
export declare class NotFoundError extends TrellisError<NotFoundErrorData> {
	static readonly schema: typeof NotFoundErrorDataSchema;
	readonly name: "NotFoundError";
	readonly data: NotFoundErrorData;
	constructor(data: NotFoundErrorData);
	static fromSerializable(data: NotFoundErrorData): NotFoundError;
	toSerializable(): NotFoundErrorData;
}
export type UnexpectedErrorData = SerializableErrorData;
export declare class UnexpectedError extends TrellisError<UnexpectedErrorData> {
	readonly name: "UnexpectedError";
	readonly data: UnexpectedErrorData;
	constructor(data: UnexpectedErrorData);
	static fromSerializable(data: UnexpectedErrorData): UnexpectedError;
	toSerializable(): UnexpectedErrorData;
}
export type ValidationErrorData = SerializableErrorData;
export declare class ValidationError extends TrellisError<ValidationErrorData> {
	readonly name: "ValidationError";
	readonly data: ValidationErrorData;
	constructor(data: ValidationErrorData);
	static fromSerializable(data: ValidationErrorData): ValidationError;
	toSerializable(): ValidationErrorData;
}
