// Generated by Trellis. Do not edit.
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_RUNTIME, PARTICIPANT_STATE_METADATA, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/demo-app/mod.js";
import * as Api1 from "../../apis/demo-service/mod.js";
import * as Api2 from "../../apis/state/mod.js";
declare const __ownedActions: readonly [];
declare const __usedActions: readonly [typeof Api1.ACTIONS["Assignments.List"], typeof Api1.ACTIONS["Audit.Feed"], typeof Api1.ACTIONS["Evidence.Delete"], typeof Api1.ACTIONS["Evidence.Download"], typeof Api1.ACTIONS["Evidence.List"], typeof Api1.ACTIONS["Evidence.Upload"], typeof Api1.ACTIONS["Reports.Generate"], typeof Api1.ACTIONS["Reports.List"], typeof Api1.ACTIONS["Sites.Get"], typeof Api1.ACTIONS["Sites.List"], typeof Api1.ACTIONS["Sites.Refresh"], typeof Api2.ACTIONS["State.Delete"], typeof Api2.ACTIONS["State.Get"], typeof Api2.ACTIONS["State.List"], typeof Api2.ACTIONS["State.Put"]];
declare const __allActions: readonly [typeof Api1.ACTIONS["Assignments.List"], typeof Api1.ACTIONS["Audit.Feed"], typeof Api1.ACTIONS["Evidence.Delete"], typeof Api1.ACTIONS["Evidence.Download"], typeof Api1.ACTIONS["Evidence.List"], typeof Api1.ACTIONS["Evidence.Upload"], typeof Api1.ACTIONS["Reports.Generate"], typeof Api1.ACTIONS["Reports.List"], typeof Api1.ACTIONS["Sites.Get"], typeof Api1.ACTIONS["Sites.List"], typeof Api1.ACTIONS["Sites.Refresh"], typeof Api2.ACTIONS["State.Delete"], typeof Api2.ACTIONS["State.Get"], typeof Api2.ACTIONS["State.List"], typeof Api2.ACTIONS["State.Put"]];
declare const __participant: {
	readonly id: "demo.app@v1";
	readonly digest: "1_LGujI_F37-CMwrTA59qtX5SRlKFMRZhMb1dwJ3Z8c";
	readonly artifact: {
		readonly description: "Browser console for the consolidated Field Ops demo.";
		readonly displayName: "Field Ops Console";
		readonly docs: {
			readonly markdown: "Declares the browser app's Field Ops service usage and workspace context state.";
			readonly summary: "Field operations browser console.";
		};
		readonly format: "trellis.participant.v1";
		readonly id: "demo.app@v1";
		readonly implements: {
			readonly self: {
				readonly api: "demo.app@v1";
				readonly apiDigest: "6TMQOitxUWuQ3REsNhxR1kf3hKyxSDlNr-6cTzjgqK8";
			};
		};
		readonly kind: "app";
		readonly schemas: {
			readonly InspectionContextState: {
				readonly properties: {
					readonly note: {
						readonly type: "string";
					};
					readonly siteId: {
						readonly type: "string";
					};
					readonly updatedAt: {
						readonly type: "string";
					};
					readonly updatedBy: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["siteId", "note", "updatedBy", "updatedAt"];
				readonly type: "object";
			};
		};
		readonly state: {
			readonly workspaceContext: {
				readonly docs: {
					readonly markdown: "Stores per-workspace inspection context used by the browser console.";
					readonly summary: "Workspace context state.";
				};
				readonly kind: "map";
				readonly schema: {
					readonly schema: "InspectionContextState";
				};
				readonly stateVersion: "inspection-context.v1";
			};
		};
		readonly uses: {
			readonly required: {
				readonly fieldOps: {
					readonly api: "demo.service@v1";
					readonly apiDigest: "qu_P04zYsryJycTKpriGBJIOAZ9N0xDwYZj8p9BR8eg";
					readonly feeds: {
						readonly subscribe: readonly ["Audit.Feed"];
					};
					readonly operations: {
						readonly cancel: readonly ["Reports.Generate"];
						readonly invoke: readonly ["Evidence.Upload", "Reports.Generate", "Sites.Refresh"];
						readonly observe: readonly ["Evidence.Upload", "Reports.Generate", "Sites.Refresh"];
					};
					readonly rpc: {
						readonly call: readonly ["Assignments.List", "Evidence.Delete", "Evidence.Download", "Evidence.List", "Reports.List", "Sites.Get", "Sites.List"];
					};
				};
				readonly state: {
					readonly api: "trellis.state@v1";
					readonly apiDigest: "1WHxeF9WLJh3v-mmHiV5mql3a67tmPNpEUFxxUIF9-Y";
					readonly rpc: {
						readonly call: readonly ["State.Delete", "State.Get", "State.List", "State.Put"];
					};
				};
			};
		};
	};
	readonly api: typeof Api0.API;
	readonly apiDigest: typeof Api0.API_DIGEST;
	readonly referencedApis: readonly [typeof Api1.API, typeof Api2.API];
};
declare const __metadata: {
	readonly PARTICIPANT_RUNTIME: {
		readonly ownedApi: ReturnType<typeof runtimeApiFromActions<typeof __ownedActions>>;
		readonly usedApi: ReturnType<typeof runtimeApiFromActions<typeof __usedActions>>;
		readonly api: ReturnType<typeof runtimeApiFromActions<typeof __allActions>>;
		readonly actions: readonly [{
			readonly action: typeof Api1.ACTIONS["Assignments.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Audit.Feed"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Evidence.Delete"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Evidence.Download"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Evidence.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Evidence.Upload"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Reports.Generate"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Reports.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Sites.Get"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Sites.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Sites.Refresh"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.Delete"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.Get"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.Put"];
			readonly optional: false;
		}];
	};
	readonly PARTICIPANT_STATE_METADATA: {
		readonly workspaceContext: {
			readonly kind: "map";
			readonly value: Api0.InspectionContextState;
			readonly schema: {
				readonly properties: {
					readonly note: {
						readonly type: "string";
					};
					readonly siteId: {
						readonly type: "string";
					};
					readonly updatedAt: {
						readonly type: "string";
					};
					readonly updatedBy: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["siteId", "note", "updatedBy", "updatedAt"];
				readonly type: "object";
			};
			readonly stateVersion: "inspection-context.v1";
			readonly acceptedVersions: {};
		};
	};
};
export declare const participant: typeof __participant & {
	readonly [PARTICIPANT_RUNTIME]: typeof __metadata.PARTICIPANT_RUNTIME;
	readonly [PARTICIPANT_STATE_METADATA]: typeof __metadata.PARTICIPANT_STATE_METADATA;
};
export default participant;
