// Generated by Trellis. Do not edit.
// @ts-self-types="./api.d.ts"
// Generated from demo.app@v1
export const API_ID = "demo.app@v1";
export const API_DIGEST = "6TMQOitxUWuQ3REsNhxR1kf3hKyxSDlNr-6cTzjgqK8";
export const API = {
	"description": "Browser console for the consolidated Field Ops demo.",
	"displayName": "Field Ops Console",
	"docs": {
		"markdown": "Declares the browser app's Field Ops service usage and workspace context state.",
		"summary": "Field operations browser console."
	},
	"exports": { "schemas": ["InspectionContextState"] },
	"format": "trellis.api.v1",
	"id": "demo.app@v1",
	"schemas": { "InspectionContextState": {
		"properties": {
			"note": { "type": "string" },
			"siteId": { "type": "string" },
			"updatedAt": { "type": "string" },
			"updatedBy": { "type": "string" }
		},
		"required": [
			"siteId",
			"note",
			"updatedBy",
			"updatedAt"
		],
		"type": "object"
	} },
	"version": "1.0.0"
};
