// Generated by Trellis. Do not edit.
// @ts-self-types="./descriptors.d.ts"
import { API as ACTION_ARTIFACT, API_DIGEST as ACTION_DIGEST } from "./api.js";
const ACTION_SOURCE = {
	api: ACTION_ARTIFACT,
	apiDigest: ACTION_DIGEST
};
const API_ID = "demo.app@v1";
export const ACTIONS = {};
