// Generated by Trellis. Do not edit.
// @ts-self-types="./schemas.d.ts"
// Generated from demo.app@v1
export const InspectionContextStateSchema = {
	"properties": {
		"note": { "type": "string" },
		"siteId": { "type": "string" },
		"updatedAt": { "type": "string" },
		"updatedBy": { "type": "string" }
	},
	"required": [
		"siteId",
		"note",
		"updatedBy",
		"updatedAt"
	],
	"type": "object"
};
