// Generated by Trellis. Do not edit.
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_RUNTIME, PARTICIPANT_STATE_METADATA, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/demo-device/mod.js";
import * as Api1 from "../../apis/demo-service/mod.js";
import * as Api2 from "../../apis/state/mod.js";
declare const __ownedActions: readonly [];
declare const __usedActions: readonly [typeof Api1.ACTIONS["Assignments.List"], typeof Api1.ACTIONS["Audit.Recorded"]["subscribe"], typeof Api1.ACTIONS["Evidence.Download"], typeof Api1.ACTIONS["Evidence.List"], typeof Api1.ACTIONS["Evidence.Upload"], typeof Api1.ACTIONS["Evidence.Uploaded"]["subscribe"], typeof Api1.ACTIONS["Reports.Generate"], typeof Api1.ACTIONS["Reports.Published"]["subscribe"], typeof Api1.ACTIONS["Sites.Get"], typeof Api1.ACTIONS["Sites.List"], typeof Api1.ACTIONS["Sites.Refresh"], typeof Api1.ACTIONS["Sites.Refreshed"]["subscribe"], typeof Api2.ACTIONS["State.Delete"], typeof Api2.ACTIONS["State.Get"], typeof Api2.ACTIONS["State.List"], typeof Api2.ACTIONS["State.Put"]];
declare const __allActions: readonly [typeof Api1.ACTIONS["Assignments.List"], typeof Api1.ACTIONS["Audit.Recorded"]["subscribe"], typeof Api1.ACTIONS["Evidence.Download"], typeof Api1.ACTIONS["Evidence.List"], typeof Api1.ACTIONS["Evidence.Upload"], typeof Api1.ACTIONS["Evidence.Uploaded"]["subscribe"], typeof Api1.ACTIONS["Reports.Generate"], typeof Api1.ACTIONS["Reports.Published"]["subscribe"], typeof Api1.ACTIONS["Sites.Get"], typeof Api1.ACTIONS["Sites.List"], typeof Api1.ACTIONS["Sites.Refresh"], typeof Api1.ACTIONS["Sites.Refreshed"]["subscribe"], typeof Api2.ACTIONS["State.Delete"], typeof Api2.ACTIONS["State.Get"], typeof Api2.ACTIONS["State.List"], typeof Api2.ACTIONS["State.Put"]];
declare const __participant: {
	readonly id: "demo.device@v1";
	readonly digest: "35Ozcrr83_MNG1-QtKXxOS1muhK8joMltjZ-ThYqRhA";
	readonly artifact: {
		readonly description: "Activated Field Device TUI for the consolidated demo.";
		readonly displayName: "Field Device Demo";
		readonly docs: {
			readonly markdown: "Declares the Field Device demo's service usage and local state for selected sites and draft inspections.";
			readonly summary: "Activated field device demo.";
		};
		readonly format: "trellis.participant.v1";
		readonly id: "demo.device@v1";
		readonly implements: {
			readonly self: {
				readonly api: "demo.device@v1";
				readonly apiDigest: "mEmDg58k8Xb_TdI_j8-cQK5KsPvLzxdYD3Hmm0O4yL8";
			};
		};
		readonly kind: "device";
		readonly schemas: {
			readonly DraftInspectionState: {
				readonly properties: {
					readonly checklistName: {
						readonly type: "string";
					};
					readonly inspectionId: {
						readonly type: "string";
					};
					readonly notes: {
						readonly type: "string";
					};
					readonly siteId: {
						readonly type: "string";
					};
					readonly updatedAt: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["inspectionId", "siteId", "checklistName", "notes", "updatedAt"];
				readonly type: "object";
			};
			readonly SelectedSiteState: {
				readonly properties: {
					readonly selectedAt: {
						readonly type: "string";
					};
					readonly siteId: {
						readonly type: "string";
					};
					readonly siteName: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["siteId", "siteName", "selectedAt"];
				readonly type: "object";
			};
		};
		readonly state: {
			readonly draftInspections: {
				readonly docs: {
					readonly markdown: "Stores editable inspection draft notes keyed by inspection id.";
					readonly summary: "Draft inspection state.";
				};
				readonly kind: "map";
				readonly schema: {
					readonly schema: "DraftInspectionState";
				};
				readonly stateVersion: "draft-inspection.v1";
			};
			readonly selectedSite: {
				readonly docs: {
					readonly markdown: "Stores the active site selected in the device TUI.";
					readonly summary: "Selected site state.";
				};
				readonly kind: "value";
				readonly schema: {
					readonly schema: "SelectedSiteState";
				};
				readonly stateVersion: "selected-site.v1";
			};
		};
		readonly uses: {
			readonly required: {
				readonly fieldOps: {
					readonly api: "demo.service@v1";
					readonly apiDigest: "qu_P04zYsryJycTKpriGBJIOAZ9N0xDwYZj8p9BR8eg";
					readonly events: {
						readonly subscribe: readonly ["Audit.Recorded", "Evidence.Uploaded", "Reports.Published", "Sites.Refreshed"];
					};
					readonly operations: {
						readonly cancel: readonly ["Reports.Generate"];
						readonly invoke: readonly ["Evidence.Upload", "Reports.Generate", "Sites.Refresh"];
						readonly observe: readonly ["Evidence.Upload", "Reports.Generate", "Sites.Refresh"];
					};
					readonly rpc: {
						readonly call: readonly ["Assignments.List", "Evidence.Download", "Evidence.List", "Sites.Get", "Sites.List"];
					};
				};
				readonly state: {
					readonly api: "trellis.state@v1";
					readonly apiDigest: "1WHxeF9WLJh3v-mmHiV5mql3a67tmPNpEUFxxUIF9-Y";
					readonly rpc: {
						readonly call: readonly ["State.Delete", "State.Get", "State.List", "State.Put"];
					};
				};
			};
		};
	};
	readonly api: typeof Api0.API;
	readonly apiDigest: typeof Api0.API_DIGEST;
	readonly referencedApis: readonly [typeof Api1.API, typeof Api2.API];
};
declare const __metadata: {
	readonly PARTICIPANT_RUNTIME: {
		readonly ownedApi: ReturnType<typeof runtimeApiFromActions<typeof __ownedActions>>;
		readonly usedApi: ReturnType<typeof runtimeApiFromActions<typeof __usedActions>>;
		readonly api: ReturnType<typeof runtimeApiFromActions<typeof __allActions>>;
		readonly actions: readonly [{
			readonly action: typeof Api1.ACTIONS["Assignments.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Audit.Recorded"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Evidence.Download"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Evidence.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Evidence.Upload"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Evidence.Uploaded"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Reports.Generate"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Reports.Published"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Sites.Get"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Sites.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Sites.Refresh"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Sites.Refreshed"]["subscribe"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.Delete"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.Get"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.List"];
			readonly optional: false;
		}, {
			readonly action: typeof Api2.ACTIONS["State.Put"];
			readonly optional: false;
		}];
	};
	readonly PARTICIPANT_STATE_METADATA: {
		readonly draftInspections: {
			readonly kind: "map";
			readonly value: Api0.DraftInspectionState;
			readonly schema: {
				readonly properties: {
					readonly checklistName: {
						readonly type: "string";
					};
					readonly inspectionId: {
						readonly type: "string";
					};
					readonly notes: {
						readonly type: "string";
					};
					readonly siteId: {
						readonly type: "string";
					};
					readonly updatedAt: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["inspectionId", "siteId", "checklistName", "notes", "updatedAt"];
				readonly type: "object";
			};
			readonly stateVersion: "draft-inspection.v1";
			readonly acceptedVersions: {};
		};
		readonly selectedSite: {
			readonly kind: "value";
			readonly value: Api0.SelectedSiteState;
			readonly schema: {
				readonly properties: {
					readonly selectedAt: {
						readonly type: "string";
					};
					readonly siteId: {
						readonly type: "string";
					};
					readonly siteName: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["siteId", "siteName", "selectedAt"];
				readonly type: "object";
			};
			readonly stateVersion: "selected-site.v1";
			readonly acceptedVersions: {};
		};
	};
};
export declare const participant: typeof __participant & {
	readonly [PARTICIPANT_RUNTIME]: typeof __metadata.PARTICIPANT_RUNTIME;
	readonly [PARTICIPANT_STATE_METADATA]: typeof __metadata.PARTICIPANT_STATE_METADATA;
};
export default participant;
