format = 1

[apis]
"trellis.demo-service@v1" = { version = "1.0.0", path = "../service/.trellis/generated/protocol/apis/trellis.demo-service@v1.json" }

[apis."trellis.state@v1"]
version = "^1.0.0"
path = "../../../rust/crates/runtime/.trellis/generated/protocol/apis/trellis.state@v1.json"
