// Generated by Trellis. Do not edit.
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_RUNTIME, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/test-client/mod.js";
import * as Api1 from "../../apis/test-events/mod.js";
declare const __ownedActions: readonly [];
declare const __usedActions: readonly [typeof Api1.ACTIONS["Alpha"]["publish"], typeof Api1.ACTIONS["DropAlpha"], typeof Api1.ACTIONS["Observed"]];
declare const __allActions: readonly [typeof Api1.ACTIONS["Alpha"]["publish"], typeof Api1.ACTIONS["DropAlpha"], typeof Api1.ACTIONS["Observed"]];
declare const __participant: {
	readonly id: "test.alpha";
	readonly digest: "TiNflLuVT8j5ztP_0o3xEAPqQ4C0ACVjfXpNLArNDvU";
	readonly artifact: {
		readonly description: "Caller-owned state.";
		readonly displayName: "Runtime caller";
		readonly format: "trellis.participant.v1";
		readonly id: "test.alpha";
		readonly implements: {
			readonly self: {
				readonly api: "test.client@v1";
				readonly apiDigest: "o8El02dTOgwoMQysX9wgZj3Tp4RHGljAroEj0Q1fGPw";
			};
		};
		readonly kind: "app";
		readonly schemas: {
			readonly Saved: {
				readonly properties: {
					readonly value: {
						readonly type: "string";
					};
				};
				readonly required: readonly ["value"];
				readonly type: "object";
			};
		};
		readonly uses: {
			readonly required: {
				readonly events: {
					readonly api: "test.events@v1";
					readonly apiDigest: "D2ZBsIpJt42ku6yDI4xFynOUY2UI7YkxadXfTqQpm0g";
					readonly events: {
						readonly publish: readonly ["Alpha"];
					};
					readonly rpc: {
						readonly call: readonly ["DropAlpha", "Observed"];
					};
				};
			};
		};
	};
	readonly api: typeof Api0.API;
	readonly apiDigest: typeof Api0.API_DIGEST;
	readonly referencedApis: readonly [typeof Api1.API];
};
declare const __metadata: {
	readonly PARTICIPANT_RUNTIME: {
		readonly ownedApi: ReturnType<typeof runtimeApiFromActions<typeof __ownedActions>>;
		readonly usedApi: ReturnType<typeof runtimeApiFromActions<typeof __usedActions>>;
		readonly api: ReturnType<typeof runtimeApiFromActions<typeof __allActions>>;
		readonly actions: readonly [{
			readonly action: typeof Api1.ACTIONS["Alpha"]["publish"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["DropAlpha"];
			readonly optional: false;
		}, {
			readonly action: typeof Api1.ACTIONS["Observed"];
			readonly optional: false;
		}];
	};
};
export declare const participant: typeof __participant & {
	readonly [PARTICIPANT_RUNTIME]: typeof __metadata.PARTICIPANT_RUNTIME;
};
export default participant;
