import { defineAppContract, optional } from "@qlever-llc/trellis/contracts";
import {
  AuthCapabilitiesList,
  AuthCapabilityGroupsDelete,
  AuthCapabilityGroupsGet,
  AuthCapabilityGroupsList,
  AuthCapabilityGroupsPut,
  AuthConnectionsKick,
  AuthConnectionsList,
  AuthDeploymentAuthorityAcceptMigration,
  AuthDeploymentAuthorityAcceptUpdate,
  AuthDeploymentAuthorityGet,
  AuthDeploymentAuthorityList,
  AuthDeploymentAuthorityPlan,
  AuthDeploymentAuthorityPlansGet,
  AuthDeploymentAuthorityPlansList,
  AuthDeploymentAuthorityReconcile,
  AuthDeploymentAuthorityReject,
  AuthDeploymentsCreate,
  AuthDeploymentsDisable,
  AuthDeploymentsEnable,
  AuthDeploymentsList,
  AuthDeploymentsRemove,
  AuthDevicesDisable,
  AuthDevicesEnable,
  AuthDevicesList,
  AuthDevicesProvision,
  AuthDevicesRemove,
  AuthDeviceUserAuthoritiesList,
  AuthDeviceUserAuthoritiesReviewsDecide,
  AuthDeviceUserAuthoritiesReviewsList,
  AuthDeviceUserAuthoritiesRevoke,
  AuthIdentityAuthorityGet,
  AuthIdentityAuthorityList,
  AuthIdentityAuthorityRevoke,
  AuthIdentityGrantsList,
  AuthIdentityGrantsRevoke,
  AuthPortalsGet,
  AuthPortalsGrantOverridesList,
  AuthPortalsGrantOverridesPut,
  AuthPortalsGrantOverridesRemove,
  AuthPortalsList,
  AuthPortalsLoginSettingsGet,
  AuthPortalsLoginSettingsUpdate,
  AuthPortalsPut,
  AuthPortalsRemove,
  AuthPortalsRoutesPut,
  AuthPortalsRoutesRemove,
  AuthServiceInstancesDisable,
  AuthServiceInstancesEnable,
  AuthServiceInstancesList,
  AuthServiceInstancesProvision,
  AuthServiceInstancesRemove,
  AuthSessionsList,
  AuthSessionsLogout,
  AuthSessionsMe,
  AuthSessionsRevoke,
  AuthUserIdentitiesList,
  AuthUsersCreate,
  AuthUsersIdentityLinkCreate,
  AuthUsersList,
  AuthUsersPasswordChange,
  AuthUsersPasswordResetCreate,
  AuthUsersUpdate,
} from "@qlever-llc/trellis/sdk/auth";
import {
  HealthInspect,
  HealthMetrics,
  HealthQuery,
  HealthWatch,
} from "@qlever-llc/trellis/sdk/health";
import {
  JobsCancel,
  JobsDismissDLQ,
  JobsInspect,
  JobsListDLQ,
  JobsListServices,
  JobsMetrics,
  JobsQuery,
  JobsReplayDLQ,
  JobsRetry,
  JobsWatch,
} from "@qlever-llc/trellis/sdk/jobs";
import {
  EventLogConsumersInspect,
  EventLogConsumersQuery,
  EventLogInspect,
  EventLogMetrics,
  EventLogQuery,
  EventLogWatch,
} from "../../../generated/packages/jsr/eventlog/mod.ts";

export const contract = defineAppContract(
  () => ({
    id: "trellis.console@v1",
    apiId: "trellis.console@v1",
    displayName: "Trellis Console",
    description:
      "Drive the Trellis admin console's contract-declared Auth, Health, and Jobs access.",
    uses: [
      AuthDeploymentsCreate,
      AuthDeviceUserAuthoritiesReviewsDecide,
      AuthDevicesDisable,
      AuthServiceInstancesDisable,
      AuthDeploymentsDisable,
      AuthDevicesEnable,
      AuthServiceInstancesEnable,
      AuthDeploymentsEnable,
      AuthDeploymentAuthorityList,
      AuthDeploymentAuthorityGet,
      AuthDeploymentAuthorityPlansList,
      AuthDeploymentAuthorityPlansGet,
      AuthDeploymentAuthorityPlan,
      AuthDeploymentAuthorityAcceptUpdate,
      AuthDeploymentAuthorityAcceptMigration,
      AuthDeploymentAuthorityReject,
      AuthDeploymentAuthorityReconcile,
      AuthConnectionsKick,
      AuthCapabilitiesList,
      AuthCapabilityGroupsDelete,
      AuthCapabilityGroupsGet,
      AuthCapabilityGroupsList,
      AuthCapabilityGroupsPut,
      AuthPortalsGrantOverridesList,
      AuthPortalsGrantOverridesPut,
      AuthPortalsGrantOverridesRemove,
      AuthIdentityGrantsList,
      AuthIdentityGrantsRevoke,
      AuthIdentityAuthorityGet,
      AuthIdentityAuthorityList,
      AuthIdentityAuthorityRevoke,
      AuthConnectionsList,
      AuthDeviceUserAuthoritiesReviewsList,
      AuthDeviceUserAuthoritiesList,
      AuthDevicesList,
      AuthDeploymentsList,
      AuthSessionsLogout,
      AuthSessionsMe,
      AuthServiceInstancesList,
      AuthSessionsList,
      AuthUserIdentitiesList,
      AuthUsersList,
      AuthUsersCreate,
      AuthUsersIdentityLinkCreate,
      AuthUsersPasswordChange,
      AuthUsersPasswordResetCreate,
      AuthDevicesProvision,
      AuthServiceInstancesProvision,
      AuthDevicesRemove,
      AuthDeploymentsRemove,
      AuthDeviceUserAuthoritiesRevoke,
      AuthSessionsRevoke,
      AuthServiceInstancesRemove,
      AuthUsersUpdate,
      AuthPortalsList,
      AuthPortalsGet,
      AuthPortalsPut,
      AuthPortalsRemove,
      AuthPortalsLoginSettingsGet,
      AuthPortalsLoginSettingsUpdate,
      AuthPortalsRoutesPut,
      AuthPortalsRoutesRemove,
      JobsInspect,
      JobsCancel,
      JobsRetry,
      JobsQuery,
      JobsMetrics,
      JobsListServices,
      JobsListDLQ,
      JobsReplayDLQ,
      JobsDismissDLQ,
      JobsWatch,
      optional(
        EventLogQuery,
        EventLogInspect,
        EventLogMetrics,
        EventLogConsumersQuery,
        EventLogConsumersInspect,
        EventLogWatch,
      ),
      optional(HealthQuery, HealthInspect, HealthMetrics, HealthWatch),
    ],
  }),
);

export default contract;
