FROM --platform=$BUILDPLATFORM docker.io/denoland/deno:2.9.4 AS build

WORKDIR /app

COPY ts /app/ts
COPY art /app/art

WORKDIR /app/ts/apps/console

RUN deno run -A npm:vite build

FROM docker.io/library/nginx:1.29-alpine

COPY ts/apps/console/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/ts/apps/console/docker-entrypoint.d/40-runtime-config.sh /docker-entrypoint.d/40-runtime-config.sh
COPY --from=build /app/ts/apps/console/build /usr/share/nginx/html

RUN chmod +x /docker-entrypoint.d/40-runtime-config.sh

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
