format = 1

[apis."trellis.core@v1"]
version = "^1.0"
path = "../../packages/trellis/.trellis/generated/protocol/apis/trellis.core@v1.json"

[apis."trellis.auth@v1"]
version = "^1.0"
path = "../../../rust/crates/runtime/.trellis/generated/protocol/apis/trellis.auth@v1.json"

[apis."trellis.eventlog@v1"]
version = "^1.0"
path = "../../../rust/crates/eventlog-runtime/.trellis/generated/protocol/apis/trellis.eventlog@v1.json"

[apis."trellis.health@v1"]
version = "^1.0"
path = "../../../rust/crates/runtime/.trellis/generated/protocol/apis/trellis.health@v1.json"

[apis."trellis.jobs@v1"]
version = "^1.0"
path = "../../../rust/crates/jobs-runtime/.trellis/generated/protocol/apis/trellis.jobs@v1.json"

[apis."trellis.state@v1"]
version = "^1.0"
path = "../../../rust/crates/runtime/.trellis/generated/protocol/apis/trellis.state@v1.json"
