// Generated by Trellis. Do not edit.
// Generated from test.admin@v1
export declare const API_ID: "test.admin@v1";
export declare const API_DIGEST: "5P5LEUZUAXsjyxXET1FRblEv0_v-mXtMczmF2zDDOaU";
export declare const API: {
	readonly description: "Admin participant used by live Trellis integration tests.";
	readonly displayName: "Trellis Test Admin";
	readonly format: "trellis.api.v1";
	readonly id: "test.admin@v1";
	readonly version: "1.0.0";
};
