// Generated by Trellis. Do not edit.
/// Owned facade for `test.events`.
use crate::apis::test_events as sdk;
/// Reusable owned participant vocabulary.
pub struct OwnedParticipant;
impl OwnedParticipant {
    pub const PARTICIPANT_ID: &'static str = super::participant::PARTICIPANT_ID;
    pub const PARTICIPANT_DIGEST: &'static str = super::participant::PARTICIPANT_DIGEST;
    pub const PARTICIPANT: &'static str = super::participant::PARTICIPANT;
    pub const PARTICIPANT_NEEDS_DIGEST: &'static str = super::participant::PARTICIPANT_NEEDS_DIGEST;
    pub const API_JSON: &'static str = sdk::API_JSON;
    pub const API_DIGEST: &'static str = sdk::API_DIGEST;
}
pub struct Client<'a> {
    inner: sdk::TestEventsClient<'a>,
}
impl<'a> Client<'a> {
    pub fn new(inner: &'a trellis_rs::generated::Caller) -> Self {
        Self {
            inner: sdk::TestEventsClient::new(inner),
        }
    }
    pub async fn drop_alpha(
        &self,
    ) -> Result<
        sdk::rpc::Empty,
        trellis_rs::generated::CallError<trellis_rs::generated::NoDeclaredError>,
    > {
        self.inner.rpc().drop_alpha().drop_alpha().await
    }
    pub async fn observed(
        &self,
    ) -> Result<
        sdk::ObservedResponse,
        trellis_rs::generated::CallError<trellis_rs::generated::NoDeclaredError>,
    > {
        self.inner.rpc().observed().observed().await
    }
    pub async fn publish_alpha(
        &self,
        event: &sdk::AlphaEvent,
    ) -> Result<(), trellis_rs::generated::TrellisClientError> {
        self.inner.event().alpha().alpha().publish(event).await
    }
    pub async fn publish_beta(
        &self,
        event: &sdk::BetaEvent,
    ) -> Result<(), trellis_rs::generated::TrellisClientError> {
        self.inner.event().beta().beta().publish(event).await
    }
}
pub struct Service<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Service<'a> {
    pub fn new(inner: &'a trellis_rs::generated::Caller) -> Self {
        Self { inner }
    }
    pub fn client(&self) -> Client<'a> {
        Client::new(self.inner)
    }
    pub async fn publish_alpha(
        &self,
        publisher: &trellis_rs::service::EventPublisher,
        event: &sdk::AlphaEvent,
    ) -> Result<(), trellis_rs::service::ServerError> {
        publisher
            .publish::<sdk::events::AlphaEventDescriptor>(event)
            .await
    }
    pub async fn publish_beta(
        &self,
        publisher: &trellis_rs::service::EventPublisher,
        event: &sdk::BetaEvent,
    ) -> Result<(), trellis_rs::service::ServerError> {
        publisher
            .publish::<sdk::events::BetaEventDescriptor>(event)
            .await
    }
}
/// Cloneable typed publisher for events owned by this service.
#[derive(Clone)]
pub struct Publisher {
    inner: trellis_rs::service::EventPublisher,
}
impl super::ConnectedService {
    /// Clone a typed publisher for owned events.
    pub fn publisher(&self) -> Publisher {
        Publisher {
            inner: self.inner.event_publisher(),
        }
    }
}
impl Publisher {
    /// Publish `Alpha`.
    pub async fn publish_alpha(
        &self,
        event: &sdk::AlphaEvent,
    ) -> Result<(), trellis_rs::service::ServerError> {
        self.inner
            .publish::<sdk::events::AlphaEventDescriptor>(event)
            .await
    }
    /// Publish `Beta`.
    pub async fn publish_beta(
        &self,
        event: &sdk::BetaEvent,
    ) -> Result<(), trellis_rs::service::ServerError> {
        self.inner
            .publish::<sdk::events::BetaEventDescriptor>(event)
            .await
    }
}
impl super::ConnectedService {
    pub fn handle(&mut self) -> ServiceHandle<'_> {
        ServiceHandle { service: self }
    }
}
pub struct ServiceHandle<'a> {
    service: &'a mut super::ConnectedService,
}
impl<'a> ServiceHandle<'a> {
    pub fn rpc(&mut self) -> ProviderRpc<'_> {
        ProviderRpc {
            service: self.service,
        }
    }
}
pub struct ProviderRpc<'a> {
    service: &'a mut super::ConnectedService,
}
impl<'a> ProviderRpc<'a> {
    pub fn drop_alpha(&mut self) -> DropAlphaProviderRpc<'_> {
        DropAlphaProviderRpc {
            service: self.service,
        }
    }
    pub fn observed(&mut self) -> ObservedProviderRpc<'_> {
        ObservedProviderRpc {
            service: self.service,
        }
    }
}
pub struct DropAlphaProviderRpc<'a> {
    service: &'a mut super::ConnectedService,
}
impl<'a> DropAlphaProviderRpc<'a> {
    pub fn drop_alpha<F, Fut>(&mut self, handler: F)
    where
        F: Fn(trellis_rs::service::ServiceHandlerContext, sdk::rpc::Empty) -> Fut
            + Send
            + Sync
            + 'static,
        Fut: std::future::Future<Output = trellis_rs::service::HandlerResult<sdk::rpc::Empty>>
            + Send
            + 'static,
    {
        self.service.register_drop_alpha(handler);
    }
}
pub struct ObservedProviderRpc<'a> {
    service: &'a mut super::ConnectedService,
}
impl<'a> ObservedProviderRpc<'a> {
    pub fn observed<F, Fut>(&mut self, handler: F)
    where
        F: Fn(trellis_rs::service::ServiceHandlerContext, sdk::rpc::Empty) -> Fut
            + Send
            + Sync
            + 'static,
        Fut: std::future::Future<Output = trellis_rs::service::HandlerResult<sdk::ObservedResponse>>
            + Send
            + 'static,
    {
        self.service.register_observed(handler);
    }
}
impl super::ConnectedService {
    fn register_drop_alpha<F, Fut>(&mut self, handler: F)
    where
        F: Fn(trellis_rs::service::ServiceHandlerContext, sdk::rpc::Empty) -> Fut
            + Send
            + Sync
            + 'static,
        Fut: std::future::Future<Output = trellis_rs::service::HandlerResult<sdk::rpc::Empty>>
            + Send
            + 'static,
    {
        self.runtime_mut()
            .register_rpc::<sdk::rpc::DropAlphaRpc, _, _>(handler);
    }
    fn register_observed<F, Fut>(&mut self, handler: F)
    where
        F: Fn(trellis_rs::service::ServiceHandlerContext, sdk::rpc::Empty) -> Fut
            + Send
            + Sync
            + 'static,
        Fut: std::future::Future<Output = trellis_rs::service::HandlerResult<sdk::ObservedResponse>>
            + Send
            + 'static,
    {
        self.runtime_mut()
            .register_rpc::<sdk::rpc::ObservedRpc, _, _>(handler);
    }
    pub async fn publish_alpha(
        &self,
        event: &sdk::AlphaEvent,
    ) -> Result<(), trellis_rs::service::ServerError> {
        self.inner
            .event_publisher()
            .publish::<sdk::events::AlphaEventDescriptor>(event)
            .await
    }
    pub async fn publish_beta(
        &self,
        event: &sdk::BetaEvent,
    ) -> Result<(), trellis_rs::service::ServerError> {
        self.inner
            .event_publisher()
            .publish::<sdk::events::BetaEventDescriptor>(event)
            .await
    }
}
