// Generated by Trellis. Do not edit.
//! Native participant metadata for `test.events`.
/// Participant id.
pub const PARTICIPANT_ID: &str = "test.events";
/// Semantic participant artifact digest.
pub const PARTICIPANT_DIGEST: &str = "o3awyoDoCj895_YcwEsP2GCbnvtVXz8JaWmvErHfy58";
/// Canonical participant artifact JSON.
pub const PARTICIPANT: &str = "{\"description\":\"Distinct publisher authority on one consumer.\",\"displayName\":\"Durable event acceptance\",\"eventConsumers\":{\"events\":{\"events\":{\"self\":[\"Alpha\",\"Beta\"]}}},\"format\":\"trellis.participant.v1\",\"id\":\"test.events\",\"implements\":{\"self\":{\"api\":\"test.events@v1\",\"apiDigest\":\"D2ZBsIpJt42ku6yDI4xFynOUY2UI7YkxadXfTqQpm0g\"}},\"kind\":\"service\",\"schemas\":{\"Empty\":{\"properties\":{},\"type\":\"object\"},\"Observed\":{\"properties\":{\"values\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"}},\"required\":[\"values\"],\"type\":\"object\"},\"Sample\":{\"properties\":{\"site\":{\"type\":\"string\"},\"value\":{\"type\":\"string\"}},\"required\":[\"site\",\"value\"],\"type\":\"object\"}}}";
/// Authoritative participant-needs digest.
pub const PARTICIPANT_NEEDS_DIGEST: &str = "l__b5pz151-cRYgMONPN38LAmBDzGaH9copiX2fv794";
/// Canonical owned API artifact JSON.
pub const API_JSON: &str = "{\"description\":\"Distinct publisher authority on one consumer.\",\"displayName\":\"Durable event acceptance\",\"events\":{\"Alpha\":{\"event\":{\"schema\":\"Sample\"},\"version\":\"v1\"},\"Beta\":{\"event\":{\"schema\":\"Sample\"},\"params\":[\"/site\"],\"version\":\"v1\"}},\"format\":\"trellis.api.v1\",\"id\":\"test.events@v1\",\"rpc\":{\"DropAlpha\":{\"input\":{\"schema\":\"Empty\"},\"output\":{\"schema\":\"Empty\"},\"version\":\"v1\"},\"Observed\":{\"input\":{\"schema\":\"Empty\"},\"output\":{\"schema\":\"Observed\"},\"version\":\"v1\"}},\"schemas\":{\"Empty\":{\"properties\":{},\"type\":\"object\"},\"Observed\":{\"properties\":{\"values\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"}},\"required\":[\"values\"],\"type\":\"object\"},\"Sample\":{\"properties\":{\"site\":{\"type\":\"string\"},\"value\":{\"type\":\"string\"}},\"required\":[\"site\",\"value\"],\"type\":\"object\"}},\"version\":\"1.0.0\"}";
/// Semantic owned API digest.
pub const API_DIGEST: &str = "D2ZBsIpJt42ku6yDI4xFynOUY2UI7YkxadXfTqQpm0g";
/// Exact referenced API JSON and digest evidence.
pub const REFERENCED_API_ARTIFACTS: &[(&str, &str)] = &[];
