// Generated by Trellis. Do not edit.
// Generated from trellis.state@v1
import { rpcAction, schema } from "@qlever-llc/trellis";
import * as Types from "./types.js";
declare const API_ID: "trellis.state@v1";
declare const __StateAdminDeleteDescriptor: {
	readonly subject: "rpc.v1.State.Admin.Delete";
	readonly permission: {
		readonly apiId: "trellis.state@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "State.Admin.Delete";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.StateAdminDeleteInput>>;
	readonly output: ReturnType<typeof schema<Types.StateAdminDeleteOutput>>;
	readonly callerCapabilities: readonly ["trellis.state::mutate"];
	readonly errors: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "AuthError";
		readonly fromSerializable: typeof Types.AuthError.fromSerializable;
	}, {
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const StateAdminDelete: ReturnType<typeof rpcAction<typeof API_ID, "State.Admin.Delete", typeof __StateAdminDeleteDescriptor>>;
declare const __StateAdminGetDescriptor: {
	readonly subject: "rpc.v1.State.Admin.Get";
	readonly permission: {
		readonly apiId: "trellis.state@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "State.Admin.Get";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.StateAdminGetInput>>;
	readonly output: ReturnType<typeof schema<Types.StateAdminGetOutput>>;
	readonly callerCapabilities: readonly ["trellis.state::read"];
	readonly errors: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "AuthError";
		readonly fromSerializable: typeof Types.AuthError.fromSerializable;
	}, {
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const StateAdminGet: ReturnType<typeof rpcAction<typeof API_ID, "State.Admin.Get", typeof __StateAdminGetDescriptor>>;
declare const __StateAdminListDescriptor: {
	readonly subject: "rpc.v1.State.Admin.List";
	readonly permission: {
		readonly apiId: "trellis.state@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "State.Admin.List";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.StateAdminListInput>>;
	readonly output: ReturnType<typeof schema<Types.StateAdminListOutput>>;
	readonly callerCapabilities: readonly ["trellis.state::read"];
	readonly errors: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "AuthError";
		readonly fromSerializable: typeof Types.AuthError.fromSerializable;
	}, {
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const StateAdminList: ReturnType<typeof rpcAction<typeof API_ID, "State.Admin.List", typeof __StateAdminListDescriptor>>;
declare const __StateDeleteDescriptor: {
	readonly subject: "rpc.v1.State.Delete";
	readonly permission: {
		readonly apiId: "trellis.state@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "State.Delete";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.StateDeleteInput>>;
	readonly output: ReturnType<typeof schema<Types.StateDeleteOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "AuthError";
		readonly fromSerializable: typeof Types.AuthError.fromSerializable;
	}, {
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const StateDelete: ReturnType<typeof rpcAction<typeof API_ID, "State.Delete", typeof __StateDeleteDescriptor>>;
declare const __StateGetDescriptor: {
	readonly subject: "rpc.v1.State.Get";
	readonly permission: {
		readonly apiId: "trellis.state@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "State.Get";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.StateGetInput>>;
	readonly output: ReturnType<typeof schema<Types.StateGetOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "AuthError";
		readonly fromSerializable: typeof Types.AuthError.fromSerializable;
	}, {
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const StateGet: ReturnType<typeof rpcAction<typeof API_ID, "State.Get", typeof __StateGetDescriptor>>;
declare const __StateListDescriptor: {
	readonly subject: "rpc.v1.State.List";
	readonly permission: {
		readonly apiId: "trellis.state@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "State.List";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.StateListInput>>;
	readonly output: ReturnType<typeof schema<Types.StateListOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "AuthError";
		readonly fromSerializable: typeof Types.AuthError.fromSerializable;
	}, {
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const StateList: ReturnType<typeof rpcAction<typeof API_ID, "State.List", typeof __StateListDescriptor>>;
declare const __StatePutDescriptor: {
	readonly subject: "rpc.v1.State.Put";
	readonly permission: {
		readonly apiId: "trellis.state@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "State.Put";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.StatePutInput>>;
	readonly output: ReturnType<typeof schema<Types.StatePutOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly declaredErrorTypes: readonly ["AuthError", "UnexpectedError", "ValidationError"];
	readonly runtimeErrors: readonly [{
		readonly type: "AuthError";
		readonly fromSerializable: typeof Types.AuthError.fromSerializable;
	}, {
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}, {
		readonly type: "ValidationError";
		readonly fromSerializable: typeof Types.ValidationError.fromSerializable;
	}];
};
export declare const StatePut: ReturnType<typeof rpcAction<typeof API_ID, "State.Put", typeof __StatePutDescriptor>>;
export declare const ACTIONS: {
	readonly "State.Admin.Delete": typeof StateAdminDelete;
	readonly "State.Admin.Get": typeof StateAdminGet;
	readonly "State.Admin.List": typeof StateAdminList;
	readonly "State.Delete": typeof StateDelete;
	readonly "State.Get": typeof StateGet;
	readonly "State.List": typeof StateList;
	readonly "State.Put": typeof StatePut;
};
export {};
