// Generated by Trellis. Do not edit.
//! Thin typed client helpers for `trellis.core@v1`.
/// Typed API wrapper for the `trellis.core@v1` contract.
pub struct CoreClient<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> CoreClient<'a> {
    /// Wrap an already connected low-level Trellis client.
    pub fn new(inner: &'a trellis_rs::generated::Caller) -> Self {
        Self { inner }
    }
    /// Access typed RPC calls.
    pub fn rpc(&self) -> Rpc<'a> {
        Rpc { _inner: self.inner }
    }
    /// Access typed events.
    pub fn event(&self) -> Event<'a> {
        Event { _inner: self.inner }
    }
    /// Access typed feeds.
    pub fn feed(&self) -> Feed<'a> {
        Feed { _inner: self.inner }
    }
    /// Access typed operations.
    pub fn operation(&self) -> Operation<'a> {
        Operation { _inner: self.inner }
    }
}
/// Typed RPC surface.
pub struct Rpc<'a> {
    pub(super) _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Rpc<'a> {
    /// Access the `trellis` RPC group.
    pub fn trellis(&self) -> TrellisRpc<'a> {
        TrellisRpc { inner: self._inner }
    }
}
/// Typed RPC methods in the `trellis` group.
pub struct TrellisRpc<'a> {
    inner: &'a trellis_rs::generated::Caller,
}
impl<'a> TrellisRpc<'a> {
    /// Call `Trellis.Surface.Status`.
    pub async fn surface_status(
        &self,
        input: &super::types::TrellisSurfaceStatusRequest,
    ) -> Result<
        super::types::TrellisSurfaceStatusResponse,
        trellis_rs::generated::CallError<super::rpc::TrellisSurfaceStatusError>,
    > {
        self.inner
            .call_typed::<
                super::rpc::TrellisSurfaceStatusRpc,
                super::rpc::TrellisSurfaceStatusError,
            >(input)
            .await
    }
}
/// Typed event surface.
pub struct Event<'a> {
    pub(super) _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Event<'a> {}
/// Typed feed surface.
pub struct Feed<'a> {
    pub(super) _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Feed<'a> {}
/// Typed operation surface.
pub struct Operation<'a> {
    pub(super) _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Operation<'a> {}
