// Generated by Trellis. Do not edit.
//! Service connection entry point for this participant.
use super::Service;
/// Runtime and credential options; participant evidence comes from [`Participant`].
pub use trellis_rs::service::ServiceConnectOptions;
/// Exact generated participant and API evidence used for service bootstrap.
pub struct Participant;
impl trellis_rs::service::GeneratedServiceParticipant for Participant {
    const PARTICIPANT_ID: &'static str = super::participant::PARTICIPANT_ID;
    const PARTICIPANT_DIGEST: &'static str = super::participant::PARTICIPANT_DIGEST;
    const PARTICIPANT_NEEDS_DIGEST: &'static str = super::participant::PARTICIPANT_NEEDS_DIGEST;
    const PARTICIPANT_JSON: &'static str = super::participant::PARTICIPANT;
    const API_JSON: &'static str = super::participant::API_JSON;
    const API_DIGEST: &'static str = super::participant::API_DIGEST;
    const REFERENCED_API_ARTIFACTS: &'static [(&'static str, &'static str)] =
        super::participant::REFERENCED_API_ARTIFACTS;
}
/// Connected service runtime for this participant contract.
pub struct ConnectedService {
    pub(super) inner: trellis_rs::service::ConnectedServiceRuntime<Participant>,
}
impl ConnectedService {
    /// Connect this service through Trellis bootstrap.
    pub async fn connect(
        opts: ServiceConnectOptions<'_>,
    ) -> Result<Self, trellis_rs::service::ServiceRuntimeError> {
        Ok(Self {
            inner: trellis_rs::service::ConnectedServiceRuntime::<Participant>::connect(opts)
                .await?,
        })
    }
    /// Access contract-shaped owned and used surfaces.
    pub fn service(&self) -> Service<'_> {
        Service::new(self.inner.caller())
    }
    /// Clone the service handle for providers that need resolved runtime resources.
    pub fn generated_handle(&self) -> trellis_rs::service::ServiceHandle {
        self.inner.generated_handle()
    }
    pub(super) fn runtime_mut(
        &mut self,
    ) -> &mut trellis_rs::service::ConnectedServiceRuntime<Participant> {
        &mut self.inner
    }
    /// Run all registered providers and service-private workers until shutdown.
    pub async fn run(self) -> Result<(), trellis_rs::service::ServiceRuntimeError> {
        self.inner.run().await
    }
}
/// Connect this service through Trellis bootstrap.
pub async fn connect(
    opts: ServiceConnectOptions<'_>,
) -> Result<ConnectedService, trellis_rs::service::ServiceRuntimeError> {
    ConnectedService::connect(opts).await
}
impl ConnectedService {}
