// Generated by Trellis. Do not edit.
//! Typed jobs descriptors for `demo.service@v1`.
use serde::{Deserialize, Serialize};
/// Generated schema type `SiteRefreshJobPayload`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SiteRefreshJobPayload {
    /// The `siteId` wire field.
    #[serde(rename = "siteId")]
    pub site_id: String,
}
/// Generated schema type `SiteRefreshJobResultSite`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SiteRefreshJobResultSite {
    /// The `lastReportAt` wire field.
    #[serde(rename = "lastReportAt")]
    pub last_report_at: String,
    /// The `latestStatus` wire field.
    #[serde(rename = "latestStatus")]
    pub latest_status: String,
    /// The `openInspections` wire field.
    #[serde(rename = "openInspections")]
    pub open_inspections: i64,
    /// The `overdueInspections` wire field.
    #[serde(rename = "overdueInspections")]
    pub overdue_inspections: i64,
    /// The `siteId` wire field.
    #[serde(rename = "siteId")]
    pub site_id: String,
    /// The `siteName` wire field.
    #[serde(rename = "siteName")]
    pub site_name: String,
}
/// Generated schema type `SiteRefreshJobResult`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SiteRefreshJobResult {
    /// The `refreshId` wire field.
    #[serde(rename = "refreshId")]
    pub refresh_id: String,
    /// The `site` wire field.
    pub site: SiteRefreshJobResultSite,
    /// The `status` wire field.
    pub status: String,
}
use trellis_rs::service::JobDescriptor;
/// Descriptor for jobs queue `refreshSiteSummary`.
pub struct RefreshSiteSummaryJob;
impl JobDescriptor for RefreshSiteSummaryJob {
    type Payload = super::jobs::SiteRefreshJobPayload;
    type Result = super::jobs::SiteRefreshJobResult;
    const QUEUE_TYPE: &'static str = "refreshSiteSummary";
    const PAYLOAD_SCHEMA_JSON: &'static str = "{\"properties\":{\"siteId\":{\"minLength\":1,\"type\":\"string\"}},\"required\":[\"siteId\"],\"type\":\"object\"}";
    const RESULT_SCHEMA_JSON: Option<&'static str> = Some(
        "{\"properties\":{\"refreshId\":{\"minLength\":1,\"type\":\"string\"},\"site\":{\"properties\":{\"lastReportAt\":{\"minLength\":1,\"type\":\"string\"},\"latestStatus\":{\"minLength\":1,\"type\":\"string\"},\"openInspections\":{\"minimum\":0,\"type\":\"integer\"},\"overdueInspections\":{\"minimum\":0,\"type\":\"integer\"},\"siteId\":{\"minLength\":1,\"type\":\"string\"},\"siteName\":{\"minLength\":1,\"type\":\"string\"}},\"required\":[\"siteId\",\"siteName\",\"openInspections\",\"overdueInspections\",\"latestStatus\",\"lastReportAt\"],\"type\":\"object\"},\"status\":{\"minLength\":1,\"type\":\"string\"}},\"required\":[\"refreshId\",\"site\",\"status\"],\"type\":\"object\"}",
    );
}
use trellis_rs::service::{ActiveJob, JobRef, JobsError};
/// Service-private jobs declared by this participant contract.
pub struct Jobs<'a> {
    service: &'a mut super::ConnectedService,
}
/// Cloneable service-private job submission facade.
#[derive(Clone)]
pub struct JobsClient {
    handle: trellis_rs::service::ServiceHandle,
}
impl<'a> Jobs<'a> {
    /// Access the `refreshSiteSummary` queue.
    pub fn refresh_site_summary(&mut self) -> RefreshSiteSummaryQueue<'_> {
        RefreshSiteSummaryQueue {
            service: self.service,
        }
    }
}
impl JobsClient {
    /// Access the `refreshSiteSummary` queue for submission.
    pub fn refresh_site_summary(&self) -> RefreshSiteSummaryQueueClient {
        RefreshSiteSummaryQueueClient {
            handle: self.handle.clone(),
        }
    }
}
impl super::ConnectedService {
    /// Access service-private jobs declared by this participant contract.
    pub fn jobs(&mut self) -> Jobs<'_> {
        Jobs { service: self }
    }
    /// Clone a service-private job submission facade for handlers and background tasks.
    pub fn jobs_client(&self) -> JobsClient {
        JobsClient {
            handle: self.inner.generated_handle(),
        }
    }
}
/// Typed `refreshSiteSummary` jobs queue.
pub struct RefreshSiteSummaryQueue<'a> {
    service: &'a mut super::ConnectedService,
}
impl RefreshSiteSummaryQueue<'_> {
    /// Submit one `refreshSiteSummary` job.
    pub async fn submit(
        &self,
        payload: <super::jobs::RefreshSiteSummaryJob as JobDescriptor>::Payload,
    ) -> Result<
        JobRef<
            <super::jobs::RefreshSiteSummaryJob as JobDescriptor>::Payload,
            <super::jobs::RefreshSiteSummaryJob as JobDescriptor>::Result,
        >,
        JobsError,
    > {
        self.service
            .inner
            .generated_submit_job::<super::jobs::RefreshSiteSummaryJob>(payload)
            .await
    }
    /// Register the worker handler for `refreshSiteSummary`.
    pub async fn handle<H, Fut, E>(&mut self, handler: H) -> Result<(), super::ServiceRuntimeError>
    where
        H: Fn(
                ActiveJob<
                    <super::jobs::RefreshSiteSummaryJob as JobDescriptor>::Payload,
                    <super::jobs::RefreshSiteSummaryJob as JobDescriptor>::Result,
                >,
            ) -> Fut
            + Clone
            + Send
            + Sync
            + 'static,
        Fut: std::future::Future<
                Output = Result<<super::jobs::RefreshSiteSummaryJob as JobDescriptor>::Result, E>,
            > + Send
            + 'static,
        E: ToString + Send + 'static,
    {
        self.service
            .runtime_mut()
            .register_generated_job_worker::<super::jobs::RefreshSiteSummaryJob, _, _, _>(handler)
            .await
    }
}
/// Cloneable `refreshSiteSummary` job submission queue.
#[derive(Clone)]
pub struct RefreshSiteSummaryQueueClient {
    handle: trellis_rs::service::ServiceHandle,
}
impl RefreshSiteSummaryQueueClient {
    /// Submit one `refreshSiteSummary` job.
    pub async fn submit(
        &self,
        payload: <super::jobs::RefreshSiteSummaryJob as JobDescriptor>::Payload,
    ) -> Result<
        JobRef<
            <super::jobs::RefreshSiteSummaryJob as JobDescriptor>::Payload,
            <super::jobs::RefreshSiteSummaryJob as JobDescriptor>::Result,
        >,
        JobsError,
    > {
        self.handle
            .generated_submit_job::<super::jobs::RefreshSiteSummaryJob>(payload)
            .await
    }
}
