// Generated by Trellis. Do not edit.
//! Typed RPC descriptors for `test.client@v1`.
use serde::{Deserialize, Serialize};
/// Empty request or response payload used by zero-argument RPCs.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct Empty {}
