// Generated by Trellis. Do not edit.
//! Shared request and response types for `test.client@v1`.
/// Marker emitted when this contract declares no shared wire types.
#[doc(hidden)]
pub struct GeneratedTypes;
