// Generated by Trellis. Do not edit.
//! Typed jobs descriptors for `test.provider`.
use serde::{Deserialize, Serialize};
/// Generated schema type `Value`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Value {
    /// The `value` wire field.
    pub value: String,
}
use trellis_rs::service::JobDescriptor;
/// Descriptor for jobs queue `work`.
pub struct WorkJob;
impl JobDescriptor for WorkJob {
    type Payload = super::jobs::Value;
    type Result = super::jobs::Value;
    const QUEUE_TYPE: &'static str = "work";
    const PAYLOAD_SCHEMA_JSON: &'static str = "{\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"type\":\"object\"}";
    const RESULT_SCHEMA_JSON: Option<&'static str> = Some(
        "{\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"type\":\"object\"}",
    );
}
use trellis_rs::service::{ActiveJob, JobRef, JobsError};
/// Service-private jobs declared by this participant contract.
pub struct Jobs<'a> {
    service: &'a mut super::ConnectedService,
}
/// Cloneable service-private job submission facade.
#[derive(Clone)]
pub struct JobsClient {
    handle: trellis_rs::service::ServiceHandle,
}
impl<'a> Jobs<'a> {
    /// Access the `work` queue.
    pub fn work(&mut self) -> WorkQueue<'_> {
        WorkQueue {
            service: self.service,
        }
    }
}
impl JobsClient {
    /// Access the `work` queue for submission.
    pub fn work(&self) -> WorkQueueClient {
        WorkQueueClient {
            handle: self.handle.clone(),
        }
    }
}
impl super::ConnectedService {
    /// Access service-private jobs declared by this participant contract.
    pub fn jobs(&mut self) -> Jobs<'_> {
        Jobs { service: self }
    }
    /// Clone a service-private job submission facade for handlers and background tasks.
    pub fn jobs_client(&self) -> JobsClient {
        JobsClient {
            handle: self.inner.generated_handle(),
        }
    }
}
/// Typed `work` jobs queue.
pub struct WorkQueue<'a> {
    service: &'a mut super::ConnectedService,
}
impl WorkQueue<'_> {
    /// Submit one `work` job.
    pub async fn submit(
        &self,
        payload: <super::jobs::WorkJob as JobDescriptor>::Payload,
    ) -> Result<
        JobRef<
            <super::jobs::WorkJob as JobDescriptor>::Payload,
            <super::jobs::WorkJob as JobDescriptor>::Result,
        >,
        JobsError,
    > {
        self.service
            .inner
            .generated_submit_job::<super::jobs::WorkJob>(payload)
            .await
    }
    /// Register the worker handler for `work`.
    pub async fn handle<H, Fut, E>(&mut self, handler: H) -> Result<(), super::ServiceRuntimeError>
    where
        H: Fn(
                ActiveJob<
                    <super::jobs::WorkJob as JobDescriptor>::Payload,
                    <super::jobs::WorkJob as JobDescriptor>::Result,
                >,
            ) -> Fut
            + Clone
            + Send
            + Sync
            + 'static,
        Fut: std::future::Future<Output = Result<<super::jobs::WorkJob as JobDescriptor>::Result, E>>
            + Send
            + 'static,
        E: ToString + Send + 'static,
    {
        self.service
            .runtime_mut()
            .register_generated_job_worker::<super::jobs::WorkJob, _, _, _>(handler)
            .await
    }
}
/// Cloneable `work` job submission queue.
#[derive(Clone)]
pub struct WorkQueueClient {
    handle: trellis_rs::service::ServiceHandle,
}
impl WorkQueueClient {
    /// Submit one `work` job.
    pub async fn submit(
        &self,
        payload: <super::jobs::WorkJob as JobDescriptor>::Payload,
    ) -> Result<
        JobRef<
            <super::jobs::WorkJob as JobDescriptor>::Payload,
            <super::jobs::WorkJob as JobDescriptor>::Result,
        >,
        JobsError,
    > {
        self.handle
            .generated_submit_job::<super::jobs::WorkJob>(payload)
            .await
    }
}
