// Generated by Trellis. Do not edit.
//! Native participant metadata for `test.provider`.
/// Participant id.
pub const PARTICIPANT_ID: &str = "test.provider";
/// Semantic participant artifact digest.
pub const PARTICIPANT_DIGEST: &str = "jjjPUXo5pPcKHlzyC5QoJdh4vDNyujkCTCCzH-tUR3s";
/// Canonical participant artifact JSON.
pub const PARTICIPANT: &str = "{\"description\":\"Small generated transport and durability fixture.\",\"displayName\":\"Runtime acceptance\",\"eventConsumers\":{\"events\":{\"events\":{\"self\":[\"Changed\"]}}},\"format\":\"trellis.participant.v1\",\"id\":\"test.provider\",\"implements\":{\"self\":{\"api\":\"test.runtime@v1\",\"apiDigest\":\"5CesKi4xQWw2TuBSzOaf_eF6_h9iUxh9SrYRfc6yK78\",\"operationTransfers\":{\"Upload\":{\"expiresInMs\":60000,\"key\":\"/value\",\"store\":\"files\"}}}},\"jobQueues\":{\"work\":{\"payload\":{\"schema\":\"Value\"},\"result\":{\"schema\":\"Value\"}}},\"kind\":\"service\",\"resources\":{\"store\":{\"files\":{\"maxObjectBytes\":262144,\"purpose\":\"Transfer acceptance bytes.\"}}},\"schemas\":{\"Empty\":{\"properties\":{},\"type\":\"object\"},\"Value\":{\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"type\":\"object\"}}}";
/// Authoritative participant-needs digest.
pub const PARTICIPANT_NEEDS_DIGEST: &str = "DTBJ9T6OAXuGnVqt_Jj7w5W9TlAv3iycBEqonqec840";
/// Canonical owned API artifact JSON.
pub const API_JSON: &str = "{\"description\":\"Small generated transport and durability fixture.\",\"displayName\":\"Runtime acceptance\",\"events\":{\"Changed\":{\"event\":{\"schema\":\"Value\"},\"version\":\"v1\"}},\"feeds\":{\"Watch\":{\"event\":{\"schema\":\"Value\"},\"input\":{\"schema\":\"Empty\"},\"version\":\"v1\"}},\"format\":\"trellis.api.v1\",\"id\":\"test.runtime@v1\",\"operations\":{\"Upload\":{\"input\":{\"schema\":\"Value\"},\"output\":{\"schema\":\"Value\"},\"transfer\":{\"direction\":\"send\"},\"version\":\"v1\"},\"Work\":{\"input\":{\"schema\":\"Value\"},\"output\":{\"schema\":\"Value\"},\"version\":\"v1\"}},\"rpc\":{\"Echo\":{\"input\":{\"schema\":\"Value\"},\"output\":{\"schema\":\"Value\"},\"version\":\"v1\"}},\"schemas\":{\"Empty\":{\"properties\":{},\"type\":\"object\"},\"Value\":{\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"type\":\"object\"}},\"version\":\"1.0.0\"}";
/// Semantic owned API digest.
pub const API_DIGEST: &str = "5CesKi4xQWw2TuBSzOaf_eF6_h9iUxh9SrYRfc6yK78";
/// Exact referenced API JSON and digest evidence.
pub const REFERENCED_API_ARTIFACTS: &[(&str, &str)] = &[];
