// Generated by Trellis. Do not edit.
// @ts-self-types="./descriptors.d.ts"
// Generated from test.events@v1
import { eventActions, rpcAction, schema } from "@qlever-llc/trellis";
import { EmptySchema, ObservedSchema, SampleSchema } from "./schemas.js";
import { API as ACTION_ARTIFACT, API_DIGEST as ACTION_DIGEST } from "./api.js";
const ACTION_SOURCE = {
	api: ACTION_ARTIFACT,
	apiDigest: ACTION_DIGEST
};
const API_ID = "test.events@v1";
const __DropAlphaDescriptor = {
	subject: "rpc.v1.DropAlpha",
	permission: Object.freeze({
		apiId: "test.events@v1",
		apiVersion: "v1",
		surfaceKind: "rpc",
		surfaceName: "DropAlpha",
		action: "call"
	}),
	input: schema(EmptySchema),
	output: schema(EmptySchema),
	callerCapabilities: []
};
export const DropAlpha = rpcAction(API_ID, "DropAlpha", __DropAlphaDescriptor, "DropAlpha", ACTION_SOURCE);
const __ObservedDescriptor = {
	subject: "rpc.v1.Observed",
	permission: Object.freeze({
		apiId: "test.events@v1",
		apiVersion: "v1",
		surfaceKind: "rpc",
		surfaceName: "Observed",
		action: "call"
	}),
	input: schema(EmptySchema),
	output: schema(ObservedSchema),
	callerCapabilities: []
};
export const Observed = rpcAction(API_ID, "Observed", __ObservedDescriptor, "Observed", ACTION_SOURCE);
const __AlphaDescriptor = {
	subject: "events.v1.Alpha",
	publishPermission: Object.freeze({
		apiId: "test.events@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Alpha",
		action: "publish"
	}),
	subscribePermission: Object.freeze({
		apiId: "test.events@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Alpha",
		action: "subscribe"
	}),
	event: schema(SampleSchema),
	publishCapabilities: [],
	subscribeCapabilities: []
};
export const Alpha = eventActions(API_ID, "Alpha", __AlphaDescriptor, "Alpha", true, ACTION_SOURCE);
const __BetaDescriptor = {
	subject: "events.v1.Beta.{/site}",
	publishPermission: Object.freeze({
		apiId: "test.events@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Beta",
		action: "publish"
	}),
	subscribePermission: Object.freeze({
		apiId: "test.events@v1",
		apiVersion: "v1",
		surfaceKind: "event",
		surfaceName: "Beta",
		action: "subscribe"
	}),
	params: ["/site"],
	event: schema(SampleSchema),
	publishCapabilities: [],
	subscribeCapabilities: []
};
export const Beta = eventActions(API_ID, "Beta", __BetaDescriptor, "Beta", true, ACTION_SOURCE);
export const ACTIONS = {
	"DropAlpha": DropAlpha,
	"Observed": Observed,
	"Alpha": Alpha,
	"Beta": Beta
};
