// Generated by Trellis. Do not edit.
// Generated from test.events@v1
export type DropAlphaInput = {};
export type DropAlphaOutput = {};
export type ObservedInput = {};
export type ObservedOutput = {
	values: Array<string>;
};
export type AlphaEvent = {
	site: string;
	value: string;
};
export type BetaEvent = {
	site: string;
	value: string;
};
