// Generated by Trellis. Do not edit.
// @ts-self-types="./mod.d.ts"
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_RUNTIME, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/app-portal/mod.js";
import * as Api1 from "../../apis/auth/mod.js";
function typeOnly() {
	return undefined;
}
const __ownedActions = [];
const __usedActions = [Api1.ACTIONS["Auth.DeviceUserAuthorities.Resolve"]];
const __allActions = [Api1.ACTIONS["Auth.DeviceUserAuthorities.Resolve"]];
const __participant = {
	id: "trellis-app.portal@v1",
	digest: "pzJdloFiTri5r-eGcXjdIDEWW85e9sh1di9phP73_f8",
	artifact: {
		"description": "Trellis built-in app for authenticated device activation over the Auth.DeviceUserAuthorities.Resolve operation.",
		"displayName": "Trellis Device Activation",
		"format": "trellis.participant.v1",
		"id": "trellis-app.portal@v1",
		"implements": { "self": {
			"api": "trellis-app.portal@v1",
			"apiDigest": "DReps_YCRCgd9JCCgTEKtxr7S9AunoqhMR-cz-rObg4"
		} },
		"kind": "app",
		"uses": { "required": { "trellis_auth_v1": {
			"api": "trellis.auth@v1",
			"apiDigest": "6k2TZ2r6d0H2y9qB-6y2PsCvJ9kq5KFlGvVOqM0nAEw",
			"operations": {
				"invoke": ["Auth.DeviceUserAuthorities.Resolve"],
				"observe": ["Auth.DeviceUserAuthorities.Resolve"]
			}
		} } }
	},
	api: Api0.API,
	apiDigest: Api0.API_DIGEST,
	referencedApis: [Api1.API]
};
const __metadata = { PARTICIPANT_RUNTIME: {
	ownedApi: runtimeApiFromActions(__ownedActions, {}),
	usedApi: runtimeApiFromActions(__usedActions),
	api: runtimeApiFromActions(__allActions, {}),
	actions: [{
		action: Api1.ACTIONS["Auth.DeviceUserAuthorities.Resolve"],
		optional: false
	}]
} };
export const participant = {
	...__participant,
	[PARTICIPANT_RUNTIME]: __metadata.PARTICIPANT_RUNTIME
};
export default participant;
