// Generated by Trellis. Do not edit.
// Generated from canonical Trellis participant artifacts.
import { PARTICIPANT_RUNTIME, runtimeApiFromActions } from "@qlever-llc/trellis";
import * as Api0 from "../../apis/app-portal/mod.js";
import * as Api1 from "../../apis/auth/mod.js";
declare const __ownedActions: readonly [];
declare const __usedActions: readonly [typeof Api1.ACTIONS["Auth.DeviceUserAuthorities.Resolve"]];
declare const __allActions: readonly [typeof Api1.ACTIONS["Auth.DeviceUserAuthorities.Resolve"]];
declare const __participant: {
	readonly id: "trellis-app.portal@v1";
	readonly digest: "pzJdloFiTri5r-eGcXjdIDEWW85e9sh1di9phP73_f8";
	readonly artifact: {
		readonly description: "Trellis built-in app for authenticated device activation over the Auth.DeviceUserAuthorities.Resolve operation.";
		readonly displayName: "Trellis Device Activation";
		readonly format: "trellis.participant.v1";
		readonly id: "trellis-app.portal@v1";
		readonly implements: {
			readonly self: {
				readonly api: "trellis-app.portal@v1";
				readonly apiDigest: "DReps_YCRCgd9JCCgTEKtxr7S9AunoqhMR-cz-rObg4";
			};
		};
		readonly kind: "app";
		readonly uses: {
			readonly required: {
				readonly trellis_auth_v1: {
					readonly api: "trellis.auth@v1";
					readonly apiDigest: "6k2TZ2r6d0H2y9qB-6y2PsCvJ9kq5KFlGvVOqM0nAEw";
					readonly operations: {
						readonly invoke: readonly ["Auth.DeviceUserAuthorities.Resolve"];
						readonly observe: readonly ["Auth.DeviceUserAuthorities.Resolve"];
					};
				};
			};
		};
	};
	readonly api: typeof Api0.API;
	readonly apiDigest: typeof Api0.API_DIGEST;
	readonly referencedApis: readonly [typeof Api1.API];
};
declare const __metadata: {
	readonly PARTICIPANT_RUNTIME: {
		readonly ownedApi: ReturnType<typeof runtimeApiFromActions<typeof __ownedActions>>;
		readonly usedApi: ReturnType<typeof runtimeApiFromActions<typeof __usedActions>>;
		readonly api: ReturnType<typeof runtimeApiFromActions<typeof __allActions>>;
		readonly actions: readonly [{
			readonly action: typeof Api1.ACTIONS["Auth.DeviceUserAuthorities.Resolve"];
			readonly optional: false;
		}];
	};
};
export declare const participant: typeof __participant & {
	readonly [PARTICIPANT_RUNTIME]: typeof __metadata.PARTICIPANT_RUNTIME;
};
export default participant;
