// Generated by Trellis. Do not edit.
/// Owned facade for `test.beta`.
/// Reusable native participant vocabulary for this participant.
pub struct OwnedParticipant;
impl OwnedParticipant {
    pub const PARTICIPANT_ID: &'static str = "test.beta";
    pub const PARTICIPANT_DIGEST: &'static str = "p_HZjQU57Cm9uGfYC3CsHsm5ZzIocS7hYwtUnn4bZV8";
    pub const PARTICIPANT_NEEDS_DIGEST: &'static str =
        "fGRImFQ9KOYV9QSwg2EtaeBMS6qzWdYOC9dE2owwudQ";
    pub const PARTICIPANT_JSON: &'static str = "{\"description\":\"Caller-owned state.\",\"displayName\":\"Runtime caller\",\"format\":\"trellis.participant.v1\",\"id\":\"test.beta\",\"implements\":{\"self\":{\"api\":\"test.client@v1\",\"apiDigest\":\"o8El02dTOgwoMQysX9wgZj3Tp4RHGljAroEj0Q1fGPw\"}},\"kind\":\"app\",\"schemas\":{\"Saved\":{\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"type\":\"object\"}},\"uses\":{\"required\":{\"events\":{\"api\":\"test.events@v1\",\"apiDigest\":\"D2ZBsIpJt42ku6yDI4xFynOUY2UI7YkxadXfTqQpm0g\",\"events\":{\"publish\":[\"Beta\"]}}}}}";
    pub const API_JSON: &'static str = "{\"description\":\"Caller-owned state.\",\"displayName\":\"Runtime caller\",\"format\":\"trellis.api.v1\",\"id\":\"test.client@v1\",\"schemas\":{\"Saved\":{\"properties\":{\"value\":{\"type\":\"string\"}},\"required\":[\"value\"],\"type\":\"object\"}},\"version\":\"1.0.0\"}";
    pub const API_DIGEST: &'static str = "o8El02dTOgwoMQysX9wgZj3Tp4RHGljAroEj0Q1fGPw";
}
pub struct Client<'a> {
    _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Client<'a> {
    pub fn new(inner: &'a trellis_rs::generated::Caller) -> Self {
        Self { _inner: inner }
    }
}
pub struct Service<'a> {
    _inner: &'a trellis_rs::generated::Caller,
}
impl<'a> Service<'a> {
    pub fn new(inner: &'a trellis_rs::generated::Caller) -> Self {
        Self { _inner: inner }
    }
}
