// Generated by Trellis. Do not edit.
//! API metadata for `test.events@v1`.
//! Generated from test.events@v1
/// Canonical Trellis API id.
pub const API_ID: &str = "test.events@v1";
/// Stable digest for the canonical API JSON.
pub const API_DIGEST: &str = "D2ZBsIpJt42ku6yDI4xFynOUY2UI7YkxadXfTqQpm0g";
/// Human-readable API name.
pub const API_NAME: &str = "Durable event acceptance";
/// Canonical API JSON embedded in the SDK crate.
pub const API_JSON: &str = "{\"description\":\"Distinct publisher authority on one consumer.\",\"displayName\":\"Durable event acceptance\",\"events\":{\"Alpha\":{\"event\":{\"schema\":\"Sample\"},\"version\":\"v1\"},\"Beta\":{\"event\":{\"schema\":\"Sample\"},\"params\":[\"/site\"],\"version\":\"v1\"}},\"format\":\"trellis.api.v1\",\"id\":\"test.events@v1\",\"rpc\":{\"DropAlpha\":{\"input\":{\"schema\":\"Empty\"},\"output\":{\"schema\":\"Empty\"},\"version\":\"v1\"},\"Observed\":{\"input\":{\"schema\":\"Empty\"},\"output\":{\"schema\":\"Observed\"},\"version\":\"v1\"}},\"schemas\":{\"Empty\":{\"properties\":{},\"type\":\"object\"},\"Observed\":{\"properties\":{\"values\":{\"items\":{\"type\":\"string\"},\"type\":\"array\"}},\"required\":[\"values\"],\"type\":\"object\"},\"Sample\":{\"properties\":{\"site\":{\"type\":\"string\"},\"value\":{\"type\":\"string\"}},\"required\":[\"site\",\"value\"],\"type\":\"object\"}},\"version\":\"1.0.0\"}";
/// Deserialize the embedded API artifact as JSON.
pub fn api_artifact() -> serde_json::Value {
    serde_json::from_str(API_JSON).expect("generated API JSON")
}
/// Register every generated RPC descriptor as router metadata.
pub fn register_rpc_metadata(router: &mut trellis_rs::service::Router) {
    router.set_api_id(API_ID);
    router.register_rpc_metadata::<super::rpc::DropAlphaRpc>();
    router.register_rpc_metadata::<super::rpc::ObservedRpc>();
}
