// Generated by Trellis. Do not edit.
//! Typed event descriptors for `test.events@v1`.
use trellis_rs::generated::EventDescriptor;
/// Descriptor for `Alpha`.
pub struct AlphaEventDescriptor;
impl EventDescriptor for AlphaEventDescriptor {
    type Event = super::types::AlphaEvent;
    const KEY: &'static str = "Alpha";
    const SUBJECT: &'static str = "events.v1.Alpha";
    const SUBSCRIBE_SUBJECT: &'static str = "events.v1.Alpha";
    const EVENT_SCHEMA_JSON: &'static str = super::schemas::ALPHA_EVENT_SCHEMA_JSON;
    const PUBLISH_CAPABILITIES: &'static [&'static str] = &[];
    const DELEGATED_PUBLISH: bool = false;
    const SUBSCRIBE_CAPABILITIES: &'static [&'static str] = &[];
}
/// Descriptor for `Beta`.
pub struct BetaEventDescriptor;
impl EventDescriptor for BetaEventDescriptor {
    type Event = super::types::BetaEvent;
    const KEY: &'static str = "Beta";
    const SUBJECT: &'static str = "events.v1.Beta.{/site}";
    const SUBSCRIBE_SUBJECT: &'static str = "events.v1.Beta.*";
    const EVENT_SCHEMA_JSON: &'static str = super::schemas::BETA_EVENT_SCHEMA_JSON;
    const PUBLISH_CAPABILITIES: &'static [&'static str] = &[];
    const DELEGATED_PUBLISH: bool = false;
    const SUBSCRIBE_CAPABILITIES: &'static [&'static str] = &[];
}
