// Generated by Trellis. Do not edit.
//! Typed RPC descriptors for `test.events@v1`.
use serde::{Deserialize, Serialize};
use trellis_rs::generated::RpcDescriptor;
/// Empty request or response payload used by zero-argument RPCs.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct Empty {}
/// Descriptor for `DropAlpha`.
pub struct DropAlphaRpc;
impl RpcDescriptor for DropAlphaRpc {
    type Input = Empty;
    type Output = Empty;
    const INPUT_SCHEMA_JSON: &'static str = super::schemas::DROP_ALPHA_INPUT_SCHEMA_JSON;
    const OUTPUT_SCHEMA_JSON: &'static str = super::schemas::DROP_ALPHA_OUTPUT_SCHEMA_JSON;
    const KEY: &'static str = "DropAlpha";
    const SUBJECT: &'static str = "rpc.v1.DropAlpha";
    const CALLER_CAPABILITIES: &'static [&'static str] = &[];
    const ERRORS: &'static [&'static str] = &[];
}
/// Descriptor for `Observed`.
pub struct ObservedRpc;
impl RpcDescriptor for ObservedRpc {
    type Input = Empty;
    type Output = super::types::ObservedResponse;
    const INPUT_SCHEMA_JSON: &'static str = super::schemas::OBSERVED_INPUT_SCHEMA_JSON;
    const OUTPUT_SCHEMA_JSON: &'static str = super::schemas::OBSERVED_OUTPUT_SCHEMA_JSON;
    const KEY: &'static str = "Observed";
    const SUBJECT: &'static str = "rpc.v1.Observed";
    const CALLER_CAPABILITIES: &'static [&'static str] = &[];
    const ERRORS: &'static [&'static str] = &[];
}
