// Generated by Trellis. Do not edit.
//! Shared request and response types for `test.events@v1`.
use serde::{Deserialize, Serialize};
/// Generated schema type `ObservedResponse`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ObservedResponse {
    /// The `values` wire field.
    pub values: Vec<String>,
}
/// Generated schema type `AlphaEvent`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AlphaEvent {
    /// The `site` wire field.
    pub site: String,
    /// The `value` wire field.
    pub value: String,
}
/// Generated schema type `BetaEvent`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct BetaEvent {
    /// The `site` wire field.
    pub site: String,
    /// The `value` wire field.
    pub value: String,
}
