// Generated by Trellis. Do not edit.
// Generated from demo.service@v1
import { eventActions, feedAction, operationAction, rpcAction, schema } from "@qlever-llc/trellis";
import * as Types from "./types.js";
declare const API_ID: "demo.service@v1";
declare const __AssignmentsListDescriptor: {
	readonly subject: "rpc.v1.Assignments.List";
	readonly permission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Assignments.List";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.AssignmentsListInput>>;
	readonly output: ReturnType<typeof schema<Types.AssignmentsListOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["UnexpectedError"];
	readonly declaredErrorTypes: readonly ["UnexpectedError"];
	readonly runtimeErrors: readonly [{
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}];
};
export declare const AssignmentsList: ReturnType<typeof rpcAction<typeof API_ID, "Assignments.List", typeof __AssignmentsListDescriptor>>;
declare const __EvidenceDeleteDescriptor: {
	readonly subject: "rpc.v1.Evidence.Delete";
	readonly permission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Evidence.Delete";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.EvidenceDeleteInput>>;
	readonly output: ReturnType<typeof schema<Types.EvidenceDeleteOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["UnexpectedError"];
	readonly declaredErrorTypes: readonly ["UnexpectedError"];
	readonly runtimeErrors: readonly [{
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}];
};
export declare const EvidenceDelete: ReturnType<typeof rpcAction<typeof API_ID, "Evidence.Delete", typeof __EvidenceDeleteDescriptor>>;
declare const __EvidenceDownloadDescriptor: {
	readonly subject: "rpc.v1.Evidence.Download";
	readonly permission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Evidence.Download";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.EvidenceDownloadInput>>;
	readonly output: ReturnType<typeof schema<Types.EvidenceDownloadOutput>>;
	readonly transfer: {
		readonly direction: "receive";
	};
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["TransferError", "UnexpectedError"];
	readonly declaredErrorTypes: readonly ["TransferError", "UnexpectedError"];
	readonly runtimeErrors: readonly [{
		readonly type: "TransferError";
		readonly fromSerializable: typeof Types.TransferError.fromSerializable;
	}, {
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}];
};
export declare const EvidenceDownload: ReturnType<typeof rpcAction<typeof API_ID, "Evidence.Download", typeof __EvidenceDownloadDescriptor>>;
declare const __EvidenceListDescriptor: {
	readonly subject: "rpc.v1.Evidence.List";
	readonly permission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Evidence.List";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.EvidenceListInput>>;
	readonly output: ReturnType<typeof schema<Types.EvidenceListOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["UnexpectedError"];
	readonly declaredErrorTypes: readonly ["UnexpectedError"];
	readonly runtimeErrors: readonly [{
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}];
};
export declare const EvidenceList: ReturnType<typeof rpcAction<typeof API_ID, "Evidence.List", typeof __EvidenceListDescriptor>>;
declare const __ReportsListDescriptor: {
	readonly subject: "rpc.v1.Reports.List";
	readonly permission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Reports.List";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.ReportsListInput>>;
	readonly output: ReturnType<typeof schema<Types.ReportsListOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["UnexpectedError"];
	readonly declaredErrorTypes: readonly ["UnexpectedError"];
	readonly runtimeErrors: readonly [{
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}];
};
export declare const ReportsList: ReturnType<typeof rpcAction<typeof API_ID, "Reports.List", typeof __ReportsListDescriptor>>;
declare const __SitesGetDescriptor: {
	readonly subject: "rpc.v1.Sites.Get";
	readonly permission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Sites.Get";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.SitesGetInput>>;
	readonly output: ReturnType<typeof schema<Types.SitesGetOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["UnexpectedError"];
	readonly declaredErrorTypes: readonly ["UnexpectedError"];
	readonly runtimeErrors: readonly [{
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}];
};
export declare const SitesGet: ReturnType<typeof rpcAction<typeof API_ID, "Sites.Get", typeof __SitesGetDescriptor>>;
declare const __SitesListDescriptor: {
	readonly subject: "rpc.v1.Sites.List";
	readonly permission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "rpc";
		readonly surfaceName: "Sites.List";
		readonly action: "call";
	};
	readonly input: ReturnType<typeof schema<Types.SitesListInput>>;
	readonly output: ReturnType<typeof schema<Types.SitesListOutput>>;
	readonly callerCapabilities: readonly [];
	readonly errors: readonly ["UnexpectedError"];
	readonly declaredErrorTypes: readonly ["UnexpectedError"];
	readonly runtimeErrors: readonly [{
		readonly type: "UnexpectedError";
		readonly fromSerializable: typeof Types.UnexpectedError.fromSerializable;
	}];
};
export declare const SitesList: ReturnType<typeof rpcAction<typeof API_ID, "Sites.List", typeof __SitesListDescriptor>>;
declare const __EvidenceUploadDescriptor: {
	readonly subject: "operations.v1.Evidence.Upload";
	readonly permissions: {
		readonly invoke: {
			readonly apiId: "demo.service@v1";
			readonly apiVersion: "v1";
			readonly surfaceKind: "operation";
			readonly surfaceName: "Evidence.Upload";
			readonly action: "invoke";
		};
		readonly observe: {
			readonly apiId: "demo.service@v1";
			readonly apiVersion: "v1";
			readonly surfaceKind: "operation";
			readonly surfaceName: "Evidence.Upload";
			readonly action: "observe";
		};
		readonly cancel: {
			readonly apiId: "demo.service@v1";
			readonly apiVersion: "v1";
			readonly surfaceKind: "operation";
			readonly surfaceName: "Evidence.Upload";
			readonly action: "cancel";
		};
		readonly control: {};
	};
	readonly input: ReturnType<typeof schema<Types.EvidenceUploadInput>>;
	readonly progress: ReturnType<typeof schema<Types.EvidenceUploadProgress>>;
	readonly output: ReturnType<typeof schema<Types.EvidenceUploadOutput>>;
	readonly transfer: {
		readonly direction: "send";
	};
	readonly callerCapabilities: readonly [];
	readonly observeCapabilities: readonly [];
	readonly cancelCapabilities: readonly [];
	readonly controlCapabilities: readonly [];
};
export declare const EvidenceUpload: ReturnType<typeof operationAction<typeof API_ID, "Evidence.Upload", typeof __EvidenceUploadDescriptor>>;
declare const __ReportsGenerateDescriptor: {
	readonly subject: "operations.v1.Reports.Generate";
	readonly permissions: {
		readonly invoke: {
			readonly apiId: "demo.service@v1";
			readonly apiVersion: "v1";
			readonly surfaceKind: "operation";
			readonly surfaceName: "Reports.Generate";
			readonly action: "invoke";
		};
		readonly observe: {
			readonly apiId: "demo.service@v1";
			readonly apiVersion: "v1";
			readonly surfaceKind: "operation";
			readonly surfaceName: "Reports.Generate";
			readonly action: "observe";
		};
		readonly cancel: {
			readonly apiId: "demo.service@v1";
			readonly apiVersion: "v1";
			readonly surfaceKind: "operation";
			readonly surfaceName: "Reports.Generate";
			readonly action: "cancel";
		};
		readonly control: {};
	};
	readonly input: ReturnType<typeof schema<Types.ReportsGenerateInput>>;
	readonly progress: ReturnType<typeof schema<Types.ReportsGenerateProgress>>;
	readonly output: ReturnType<typeof schema<Types.ReportsGenerateOutput>>;
	readonly callerCapabilities: readonly [];
	readonly observeCapabilities: readonly [];
	readonly cancelCapabilities: readonly [];
	readonly controlCapabilities: readonly [];
	readonly cancel: true;
};
export declare const ReportsGenerate: ReturnType<typeof operationAction<typeof API_ID, "Reports.Generate", typeof __ReportsGenerateDescriptor>>;
declare const __SitesRefreshDescriptor: {
	readonly subject: "operations.v1.Sites.Refresh";
	readonly permissions: {
		readonly invoke: {
			readonly apiId: "demo.service@v1";
			readonly apiVersion: "v1";
			readonly surfaceKind: "operation";
			readonly surfaceName: "Sites.Refresh";
			readonly action: "invoke";
		};
		readonly observe: {
			readonly apiId: "demo.service@v1";
			readonly apiVersion: "v1";
			readonly surfaceKind: "operation";
			readonly surfaceName: "Sites.Refresh";
			readonly action: "observe";
		};
		readonly cancel: {
			readonly apiId: "demo.service@v1";
			readonly apiVersion: "v1";
			readonly surfaceKind: "operation";
			readonly surfaceName: "Sites.Refresh";
			readonly action: "cancel";
		};
		readonly control: {};
	};
	readonly input: ReturnType<typeof schema<Types.SitesRefreshInput>>;
	readonly progress: ReturnType<typeof schema<Types.SitesRefreshProgress>>;
	readonly output: ReturnType<typeof schema<Types.SitesRefreshOutput>>;
	readonly callerCapabilities: readonly [];
	readonly observeCapabilities: readonly [];
	readonly cancelCapabilities: readonly [];
	readonly controlCapabilities: readonly [];
};
export declare const SitesRefresh: ReturnType<typeof operationAction<typeof API_ID, "Sites.Refresh", typeof __SitesRefreshDescriptor>>;
declare const __AuditRecordedDescriptor: {
	readonly subject: "events.v1.Audit.Recorded";
	readonly publishPermission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Audit.Recorded";
		readonly action: "publish";
	};
	readonly subscribePermission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Audit.Recorded";
		readonly action: "subscribe";
	};
	readonly event: ReturnType<typeof schema<Types.AuditRecordedEvent>>;
	readonly publishCapabilities: readonly [];
	readonly subscribeCapabilities: readonly [];
};
export declare const AuditRecorded: ReturnType<typeof eventActions<typeof API_ID, "Audit.Recorded", typeof __AuditRecordedDescriptor, true>>;
declare const __EvidenceUploadedDescriptor: {
	readonly subject: "events.v1.Evidence.Uploaded";
	readonly publishPermission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Evidence.Uploaded";
		readonly action: "publish";
	};
	readonly subscribePermission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Evidence.Uploaded";
		readonly action: "subscribe";
	};
	readonly event: ReturnType<typeof schema<Types.EvidenceUploadedEvent>>;
	readonly publishCapabilities: readonly [];
	readonly subscribeCapabilities: readonly [];
};
export declare const EvidenceUploaded: ReturnType<typeof eventActions<typeof API_ID, "Evidence.Uploaded", typeof __EvidenceUploadedDescriptor, true>>;
declare const __ReportsPublishedDescriptor: {
	readonly subject: "events.v1.Reports.Published";
	readonly publishPermission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Reports.Published";
		readonly action: "publish";
	};
	readonly subscribePermission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Reports.Published";
		readonly action: "subscribe";
	};
	readonly event: ReturnType<typeof schema<Types.ReportsPublishedEvent>>;
	readonly publishCapabilities: readonly [];
	readonly subscribeCapabilities: readonly [];
};
export declare const ReportsPublished: ReturnType<typeof eventActions<typeof API_ID, "Reports.Published", typeof __ReportsPublishedDescriptor, true>>;
declare const __SitesRefreshedDescriptor: {
	readonly subject: "events.v1.Sites.Refreshed";
	readonly publishPermission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Sites.Refreshed";
		readonly action: "publish";
	};
	readonly subscribePermission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "event";
		readonly surfaceName: "Sites.Refreshed";
		readonly action: "subscribe";
	};
	readonly event: ReturnType<typeof schema<Types.SitesRefreshedEvent>>;
	readonly publishCapabilities: readonly [];
	readonly subscribeCapabilities: readonly [];
};
export declare const SitesRefreshed: ReturnType<typeof eventActions<typeof API_ID, "Sites.Refreshed", typeof __SitesRefreshedDescriptor, true>>;
declare const __AuditFeedDescriptor: {
	readonly subject: "feed.v1.Audit.Feed";
	readonly permission: {
		readonly apiId: "demo.service@v1";
		readonly apiVersion: "v1";
		readonly surfaceKind: "feed";
		readonly surfaceName: "Audit.Feed";
		readonly action: "subscribe";
	};
	readonly input: ReturnType<typeof schema<Types.AuditFeedInput>>;
	readonly event: ReturnType<typeof schema<Types.AuditFeedEvent>>;
	readonly subscribeCapabilities: readonly [];
};
export declare const AuditFeed: ReturnType<typeof feedAction<typeof API_ID, "Audit.Feed", typeof __AuditFeedDescriptor>>;
export declare const ACTIONS: {
	readonly "Assignments.List": typeof AssignmentsList;
	readonly "Evidence.Delete": typeof EvidenceDelete;
	readonly "Evidence.Download": typeof EvidenceDownload;
	readonly "Evidence.List": typeof EvidenceList;
	readonly "Reports.List": typeof ReportsList;
	readonly "Sites.Get": typeof SitesGet;
	readonly "Sites.List": typeof SitesList;
	readonly "Evidence.Upload": typeof EvidenceUpload;
	readonly "Reports.Generate": typeof ReportsGenerate;
	readonly "Sites.Refresh": typeof SitesRefresh;
	readonly "Audit.Recorded": typeof AuditRecorded;
	readonly "Evidence.Uploaded": typeof EvidenceUploaded;
	readonly "Reports.Published": typeof ReportsPublished;
	readonly "Sites.Refreshed": typeof SitesRefreshed;
	readonly "Audit.Feed": typeof AuditFeed;
};
export {};
