/**
 * @module
 *
 * Trellis server-side authentication library for session-key based authentication.
 *
 * - Session keys are Ed25519 keys represented as base64url (32-byte raw public key).
 * - Proofs are Ed25519 signatures over SHA-256(buildProofInput(...)).
 * - Services load their session key seed from `TRELLIS_SESSION_KEY_SEED`.
 */

export {
  type AuthDeviceUserAuthoritiesListInput,
  type AuthDeviceUserAuthoritiesListOutput,
  type AuthDeviceUserAuthoritiesRevokeInput,
  type AuthDeviceUserAuthoritiesRevokeResponse,
  type AuthResolveDeviceUserAuthoritiesInput,
  type AuthResolveDeviceUserAuthoritiesOperation,
  type AuthResolveDeviceUserAuthoritiesOutput,
  type AuthResolveDeviceUserAuthoritiesProgress,
  buildDeviceActivationPayload,
  buildDeviceWaitProofInput,
  createDeviceActivationClient,
  createDeviceNatsAuthToken,
  deriveDeviceConfirmationCode,
  deriveDeviceIdentity,
  deriveDeviceQrMac,
  type DeviceActivationPayload,
  type DeviceActivationTransport,
  type DeviceActivationWaitRequest,
  type DeviceIdentity,
  encodeDeviceActivationPayload,
  getDeviceConnectInfo,
  type GetDeviceConnectInfoInput,
  type GetDeviceConnectInfoOutput,
  parseDeviceActivationPayload,
  signDeviceWaitRequest,
  startDeviceActivationRequest,
  verifyDeviceConfirmationCode,
  verifyDeviceWaitSignature,
  waitForDeviceActivation,
  type WaitForDeviceActivationResponse,
} from "./device_activation.ts";
export {
  type AuthConfig,
  bindFlow,
  type BrowserAuthRecoveryClassification,
  type BrowserAuthRecoveryKind,
  buildLoginUrl,
  classifyBrowserAuthError,
  clearSessionKey,
  completeSessionLogout,
  type CompleteSessionLogoutArgs,
  createRpcProof,
  fetchPortalFlowState,
  generateSessionKey,
  getOrCreateSessionKey,
  getPublicSessionKey,
  hasSessionKey,
  isBindSuccessResponse,
  isRecoverableBrowserAuthError,
  loadSessionKey,
  logoutSession,
  logoutSessionSig,
  natsConnectSigForIat,
  portalFlowIdFromUrl,
  portalProviderLoginUrl,
  portalRedirectLocation,
  type SessionKeyHandle,
  type SessionKeyOptions,
  type SessionKeyPersistenceMode,
  signBytes,
  startAuthRequest,
  submitPortalApproval,
} from "./browser.ts";
export {
  buildEventProofInput,
  buildProofInput,
  createEventProof,
  createProof,
  type EventProofParams,
  type ProofParams,
  verifyEventProof,
  verifyProof,
} from "./proof.ts";
export {
  ApprovalRecordViewSchema,
  AuthCapabilitiesListResponseSchema,
  AuthCapabilitiesListSchema,
  AuthCapabilityGroupsDeleteResponseSchema,
  AuthCapabilityGroupsDeleteSchema,
  AuthCapabilityGroupsGetResponseSchema,
  AuthCapabilityGroupsGetSchema,
  AuthCapabilityGroupsListResponseSchema,
  AuthCapabilityGroupsListSchema,
  AuthCapabilityGroupsPutResponseSchema,
  AuthCapabilityGroupsPutSchema,
  AuthCatalogIssuesResolveResponseSchema,
  AuthCatalogIssuesResolveSchema,
  type AuthDeployment,
  type AuthDeploymentAuthorityAcceptMigrationInput,
  AuthDeploymentAuthorityAcceptMigrationSchema,
  type AuthDeploymentAuthorityAcceptResponse,
  AuthDeploymentAuthorityAcceptResponseSchema,
  type AuthDeploymentAuthorityAcceptUpdateInput,
  AuthDeploymentAuthorityAcceptUpdateSchema,
  type AuthDeploymentAuthorityGetInput,
  type AuthDeploymentAuthorityGetResponse,
  AuthDeploymentAuthorityGetResponseSchema,
  AuthDeploymentAuthorityGetSchema,
  type AuthDeploymentAuthorityGrantOverridesListInput,
  type AuthDeploymentAuthorityGrantOverridesListResponse,
  AuthDeploymentAuthorityGrantOverridesListResponseSchema,
  AuthDeploymentAuthorityGrantOverridesListSchema,
  type AuthDeploymentAuthorityGrantOverridesPutInput,
  AuthDeploymentAuthorityGrantOverridesPutSchema,
  type AuthDeploymentAuthorityGrantOverridesRemoveInput,
  AuthDeploymentAuthorityGrantOverridesRemoveSchema,
  type AuthDeploymentAuthorityGrantOverridesResponse,
  AuthDeploymentAuthorityGrantOverridesResponseSchema,
  type AuthDeploymentAuthorityListInput,
  type AuthDeploymentAuthorityListResponse,
  AuthDeploymentAuthorityListResponseSchema,
  AuthDeploymentAuthorityListSchema,
  type AuthDeploymentAuthorityPlanInput,
  type AuthDeploymentAuthorityPlanResponse,
  AuthDeploymentAuthorityPlanResponseSchema,
  AuthDeploymentAuthorityPlanSchema,
  type AuthDeploymentAuthorityPlansGetInput,
  type AuthDeploymentAuthorityPlansGetResponse,
  AuthDeploymentAuthorityPlansGetResponseSchema,
  AuthDeploymentAuthorityPlansGetSchema,
  type AuthDeploymentAuthorityPlansListInput,
  type AuthDeploymentAuthorityPlansListResponse,
  AuthDeploymentAuthorityPlansListResponseSchema,
  AuthDeploymentAuthorityPlansListSchema,
  type AuthDeploymentAuthorityReconcileInput,
  type AuthDeploymentAuthorityReconcileResponse,
  AuthDeploymentAuthorityReconcileResponseSchema,
  AuthDeploymentAuthorityReconcileSchema,
  type AuthDeploymentAuthorityRejectInput,
  type AuthDeploymentAuthorityRejectResponse,
  AuthDeploymentAuthorityRejectResponseSchema,
  AuthDeploymentAuthorityRejectSchema,
  type AuthDeploymentKind,
  AuthDeploymentKindSchema,
  AuthDeploymentSchema,
  AuthDeploymentsCreateResponseSchema,
  AuthDeploymentsCreateSchema,
  AuthDeploymentsDisableResponseSchema,
  AuthDeploymentsDisableSchema,
  AuthDeploymentsEnableResponseSchema,
  AuthDeploymentsEnableSchema,
  AuthDeploymentsListResponseSchema,
  AuthDeploymentsListSchema,
  AuthDeploymentsRemoveResponseSchema,
  AuthDeploymentsRemoveSchema,
  AuthDevicesConnectInfoGetResponseSchema,
  AuthDevicesConnectInfoGetSchema,
  AuthDevicesDisableResponseSchema,
  AuthDevicesDisableSchema,
  AuthDevicesEnableResponseSchema,
  AuthDevicesEnableSchema,
  AuthDevicesListResponseSchema,
  AuthDevicesListSchema,
  AuthDevicesProvisionResponseSchema,
  AuthDevicesProvisionSchema,
  AuthDevicesRemoveResponseSchema,
  AuthDevicesRemoveSchema,
  AuthDeviceUserAuthoritiesApprovedEventSchema,
  AuthDeviceUserAuthoritiesListResponseSchema,
  AuthDeviceUserAuthoritiesListSchema,
  AuthDeviceUserAuthoritiesRequestedEventSchema,
  AuthDeviceUserAuthoritiesResolvedEventSchema,
  AuthDeviceUserAuthoritiesReviewRequestedEventSchema,
  AuthDeviceUserAuthoritiesReviewsDecideResponseSchema,
  AuthDeviceUserAuthoritiesReviewsDecideSchema,
  AuthDeviceUserAuthoritiesReviewsListResponseSchema,
  AuthDeviceUserAuthoritiesReviewsListSchema,
  AuthDeviceUserAuthoritiesRevokeResponseSchema,
  AuthDeviceUserAuthoritiesRevokeSchema,
  type AuthenticatedDevice,
  AuthenticatedDeviceSchema,
  type AuthenticatedService,
  type AuthenticatedUser,
  type AuthEventConsumerBinding,
  AuthEventConsumerBindingSchema,
  type AuthEventConsumersListInput,
  type AuthEventConsumersListResponse,
  AuthEventConsumersListResponseSchema,
  AuthEventConsumersListSchema,
  AuthEventsValidateResponseSchema,
  AuthEventsValidateSchema,
  AuthIdentitiesListResponseSchema,
  AuthIdentitiesListSchema,
  AuthIdentityGrantsListResponseSchema,
  AuthIdentityGrantsListSchema,
  AuthIdentityGrantsRevokeResponseSchema,
  AuthIdentityGrantsRevokeSchema,
  AuthPortalsGetResponseSchema,
  AuthPortalsGetSchema,
  AuthPortalsListResponseSchema,
  AuthPortalsListSchema,
  AuthPortalsLoginSettingsGetSchema,
  AuthPortalsLoginSettingsResponseSchema,
  AuthPortalsLoginSettingsUpdateSchema,
  AuthPortalsPutResponseSchema,
  AuthPortalsPutSchema,
  AuthPortalsRemoveResponseSchema,
  AuthPortalsRemoveSchema,
  AuthPortalsRoutesPutResponseSchema,
  AuthPortalsRoutesPutSchema,
  AuthPortalsRoutesRemoveResponseSchema,
  AuthPortalsRoutesRemoveSchema,
  AuthRequestsValidateResponseSchema,
  AuthRequestsValidateSchema,
  AuthResolveDeviceUserAuthoritiesProgressSchema,
  AuthResolveDeviceUserAuthoritiesResponseSchema,
  AuthResolveDeviceUserAuthoritiesSchema,
  AuthServiceInstancesDisableResponseSchema,
  AuthServiceInstancesDisableSchema,
  AuthServiceInstancesEnableResponseSchema,
  AuthServiceInstancesEnableSchema,
  AuthServiceInstancesListResponseSchema,
  AuthServiceInstancesListSchema,
  AuthServiceInstancesProvisionResponseSchema,
  AuthServiceInstancesProvisionSchema,
  AuthServiceInstancesRemoveResponseSchema,
  AuthServiceInstancesRemoveSchema,
  type AuthSessionsMeResponse,
  AuthSessionsMeResponseSchema,
  AuthSessionsMeSchema,
  AuthUserIdentitiesListResponseSchema,
  AuthUserIdentitiesListSchema,
  AuthUserIdentitiesUnlinkResponseSchema,
  AuthUserIdentitiesUnlinkSchema,
  AuthUsersAccountFlowCreateResponseSchema,
  AuthUsersCreateResponseSchema,
  AuthUsersCreateSchema,
  AuthUsersGetResponseSchema,
  AuthUsersGetSchema,
  AuthUsersIdentityLinkCreateSchema,
  AuthUsersListResponseSchema,
  AuthUsersListSchema,
  AuthUsersPasswordChangeResponseSchema,
  AuthUsersPasswordChangeSchema,
  AuthUsersPasswordResetCreateSchema,
  AuthUsersResolveResponseSchema,
  AuthUsersResolveSchema,
  AuthUsersUpdateResponseSchema,
  AuthUsersUpdateSchema,
  CallerViewSchema,
  ContractAnalysisSchema,
  ContractAnalysisSummarySchema,
  type DeploymentAuthority,
  type DeploymentAuthorityCapability,
  type DeploymentAuthorityCapabilityNeed,
  DeploymentAuthorityCapabilityNeedSchema,
  DeploymentAuthorityCapabilitySchema,
  type DeploymentAuthorityContractNeed,
  DeploymentAuthorityContractNeedSchema,
  type DeploymentAuthorityGrantOverride,
  DeploymentAuthorityGrantOverrideSchema,
  type DeploymentAuthorityKind,
  DeploymentAuthorityKindSchema,
  type DeploymentAuthorityMaterialization,
  DeploymentAuthorityMaterializationSchema,
  type DeploymentAuthorityMigration,
  DeploymentAuthorityMigrationSchema,
  type DeploymentAuthorityNeeds,
  DeploymentAuthorityNeedsSchema,
  type DeploymentAuthorityPlan,
  type DeploymentAuthorityPlanBreakingChange,
  DeploymentAuthorityPlanBreakingChangeSchema,
  DeploymentAuthorityPlanSchema,
  type DeploymentAuthorityProposal,
  DeploymentAuthorityProposalSchema,
  type DeploymentAuthorityReconciliationStatus,
  DeploymentAuthorityReconciliationStatusSchema,
  type DeploymentAuthorityResource,
  DeploymentAuthorityResourceKindSchema,
  type DeploymentAuthorityResourceNeed,
  DeploymentAuthorityResourceNeedSchema,
  DeploymentAuthorityResourceSchema,
  DeploymentAuthoritySchema,
  type DeploymentAuthoritySurface,
  DeploymentAuthoritySurfaceActionSchema,
  DeploymentAuthoritySurfaceKindSchema,
  type DeploymentAuthoritySurfaceNeed,
  DeploymentAuthoritySurfaceNeedSchema,
  DeploymentAuthoritySurfaceSchema,
  type DeploymentAuthorityUpdate,
  DeploymentAuthorityUpdateSchema,
  DeploymentPortalRouteSchema,
  DeploymentResourceBindingSchema,
  DeviceActivationActorSchema,
  type DeviceActivationRecord,
  DeviceActivationRecordSchema,
  DeviceActivationReviewSchema,
  DeviceConnectInfoSchema,
  DeviceDeploymentSchema,
  DeviceSchema,
  DigestSchema,
  type FlowRegistrationAvailability,
  FlowRegistrationAvailabilitySchema,
  IdentityGrantViewSchema,
  ImplementationOfferSchema,
  type LoginPortalRecord,
  LoginPortalRecordSchema,
  type LoginPortalRoute,
  LoginPortalRouteSchema,
  type LoginPortalSettings,
  LoginPortalSettingsSchema,
  type LoginPortalSummary,
  LoginPortalSummarySchema,
  type MaterializedAuthorityCapabilityGrant,
  MaterializedAuthorityCapabilityGrantSchema,
  type MaterializedAuthorityGrant,
  type MaterializedAuthorityGrants,
  MaterializedAuthorityGrantsSchema,
  type MaterializedAuthorityNatsGrant,
  MaterializedAuthorityNatsGrantSchema,
  type MaterializedAuthorityNatsGrantSource,
  MaterializedAuthorityNatsGrantSourceSchema,
  type MaterializedAuthoritySurfaceGrant,
  MaterializedAuthoritySurfaceGrantSchema,
  OpenObjectSchema,
  type ParticipantKind,
  ParticipantKindSchema,
  type PortalFlowApp,
  type PortalFlowApproval,
  type PortalFlowApprovalDeniedState,
  type PortalFlowApprovalRequiredState,
  type PortalFlowChooseProviderState,
  type PortalFlowExpiredState,
  type PortalFlowInsufficientCapabilitiesState,
  type PortalFlowProvider,
  type PortalFlowRedirectState,
  type PortalFlowState,
  PortalFlowStateSchema,
  type PortalFlowUser,
  ResolvedUserLabelSchema,
  ServiceDeploymentSchema,
  ServiceInstanceSchema,
  UserViewSchema,
  WaitForDeviceActivationRequestSchema,
  WaitForDeviceActivationResponseSchema,
} from "./protocol.ts";
export {
  approvalCapabilityKeys,
  type ApprovalDecision,
  ApprovalDecisionSchema,
  type AuthLogoutRequest,
  AuthLogoutRequestSchema,
  type AuthLogoutResponse,
  type AuthLogoutResponseMode,
  AuthLogoutResponseModeSchema,
  AuthLogoutResponseSchema,
  type AuthStartFlowResponse,
  AuthStartFlowResponseSchema,
  type AuthStartRequest,
  AuthStartRequestSchema,
  type AuthStartResponse,
  AuthStartResponseSchema,
  type BindResponse,
  BindResponseSchema,
  type BindSuccessResponse,
  BindSuccessResponseSchema,
  buildLogoutSignaturePayload,
  type ClientTransportEndpoints,
  ClientTransportEndpointsSchema,
  type ClientTransports,
  ClientTransportsSchema,
  type ContractApproval,
  type ContractApprovalCapability,
  ContractApprovalSchema,
  type LogoutSignaturePayloadInput,
  type NatsAuthTokenV1,
  NatsAuthTokenV1Schema,
  type SentinelCreds,
  SentinelCredsSchema,
  type UserParticipantKind,
  UserParticipantKindSchema,
} from "./schemas.ts";
export {
  buildNatsConnectSignaturePayload,
  createAuth,
  type NatsConnectOptions,
  type TrellisAuth,
} from "./session_auth.ts";
export { correctedIatSeconds, estimateMidpointClockOffsetMs } from "./time.ts";
export { trellisIdFromOriginId } from "./trellis_id.ts";
export {
  base64urlDecode,
  base64urlEncode,
  canonicalizeJsonValue,
  sha256,
  toArrayBuffer,
  utf8,
} from "./utils.ts";
