// Generated by Trellis. Do not edit.
// Generated from acme.orders-caller@v1
export declare const API_ID: "acme.orders-caller@v1";
export declare const API_DIGEST: "YyZR1x1FTKntHUadRY4zF_iUdi_ekGixH5zKBcyq7nA";
export declare const API: {
	readonly description: "Caller for the service walkthrough.";
	readonly displayName: "Orders caller";
	readonly format: "trellis.api.v1";
	readonly id: "acme.orders-caller@v1";
	readonly version: "1.0.0";
};
