// Generated by Trellis. Do not edit.
// @ts-self-types="./api.d.ts"
// Generated from test.client@v1
export const API_ID = "test.client@v1";
export const API_DIGEST = "o8El02dTOgwoMQysX9wgZj3Tp4RHGljAroEj0Q1fGPw";
export const API = {
	"description": "Caller-owned state.",
	"displayName": "Runtime caller",
	"format": "trellis.api.v1",
	"id": "test.client@v1",
	"schemas": { "Saved": {
		"properties": { "value": { "type": "string" } },
		"required": ["value"],
		"type": "object"
	} },
	"version": "1.0.0"
};
